package main_test

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerator(t *testing.T) {
	root := filepath.Clean(filepath.Join("..", "..", ".."))
	binDir := t.TempDir()
	binary := filepath.Join(binDir, "geninterp")
	build := exec.CommandContext(t.Context(), "go", "build", "-o", binary, "./internal/cmd/geninterp")
	build.Dir = root
	output, err := build.CombinedOutput()
	require.NoError(t, err, string(output))

	temp := t.TempDir()
	command := exec.CommandContext(t.Context(), binary)
	command.Dir = temp
	output, err = command.CombinedOutput()
	require.NoError(t, err, string(output))
	require.Equal(t, "interp/threaded.go\n", string(output))

	path := filepath.Join(temp, "interp", "threaded.go")
	golden, err := os.ReadFile(path)
	require.NoError(t, err)
	require.True(t, bytes.HasPrefix(golden, []byte("// Code generated by internal/cmd/geninterp; DO NOT EDIT.\n")))

	cases := []struct {
		name     string
		content  []byte // nil means the file is absent
		wantErr  bool
		contains string
		after    func(t *testing.T, out string)
	}{
		{
			name:    "up to date output passes silently",
			content: golden,
		},
		{
			name:     "stale output is rejected without being rewritten",
			content:  []byte("stale"),
			wantErr:  true,
			contains: "interp/threaded.go is stale",
			after: func(t *testing.T, out string) {
				actual, err := os.ReadFile(out)
				require.NoError(t, err)
				require.Equal(t, []byte("stale"), actual)
			},
		},
		{
			name:     "missing output fails to read",
			wantErr:  true,
			contains: "read interp/threaded.go",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			out := filepath.Join(dir, "interp", "threaded.go")
			require.NoError(t, os.MkdirAll(filepath.Dir(out), 0o755))
			if tc.content != nil {
				require.NoError(t, os.WriteFile(out, tc.content, 0o644))
			}

			command := exec.CommandContext(t.Context(), binary, "-check")
			command.Dir = dir
			output, err := command.CombinedOutput()
			if tc.wantErr {
				require.Error(t, err)
				require.Contains(t, string(output), tc.contains)
			} else {
				require.NoError(t, err, string(output))
				require.Empty(t, output)
			}
			if tc.after != nil {
				tc.after(t, out)
			}
		})
	}

	file, err := parser.ParseFile(token.NewFileSet(), path, golden, 0)
	require.NoError(t, err)
	require.Equal(t, "interp", file.Name.Name)

	forbidden := map[string]struct{}{
		"arrayGetAt": {}, "branchIf": {}, "callHost": {}, "finish": {},
		"refGet": {}, "releaseArgs": {}, "resume": {}, "ret": {},
		"structGetAt": {}, "suspend": {}, "tail": {},
	}
	foundThreader := false
	foundInit := false
	foundCompile := false
	ast.Inspect(file, func(node ast.Node) bool {
		switch node := node.(type) {
		case *ast.TypeSpec:
			_, structure := node.Type.(*ast.StructType)
			foundThreader = foundThreader || node.Name.Name == "threader" && structure
		case *ast.FuncDecl:
			if node.Recv == nil {
				foundInit = foundInit || node.Name.Name == "init"
				return true
			}
			for _, field := range node.Recv.List {
				name := field.Type
				if star, ok := name.(*ast.StarExpr); ok {
					name = star.X
				}
				ident, ok := name.(*ast.Ident)
				if !ok {
					continue
				}
				if ident.Name == "Interpreter" {
					require.Fail(t, "generated Interpreter method", path+":"+node.Name.Name)
				}
				if pointer, ok := field.Type.(*ast.StarExpr); ok {
					ident, ok := pointer.X.(*ast.Ident)
					foundCompile = foundCompile || ok && ident.Name == "threader" && node.Name.Name == "Compile"
				}
			}
		case *ast.CallExpr:
			selector, ok := node.Fun.(*ast.SelectorExpr)
			if ok {
				_, found := forbidden[selector.Sel.Name]
				require.False(t, found, path+":"+selector.Sel.Name)
			}
		}
		return true
	})
	require.True(t, foundThreader)
	require.True(t, foundInit)
	require.True(t, foundCompile)
}
