package codegen

import (
	"github.com/dave/jennifer/jen"
)

func yield() jen.Code {
	return handler(underflow(1),
		next(),
		jen.If(jen.Id("i").Dot("fp").Op("==").Lit(1)).Block(jen.Panic(jen.Id("errYield"))),
		jen.Block(jen.Id("f").Op(":=").Id("i").Dot("fr"),
			jen.Id("coAddr").Op(":=").Id("f").Dot("coro"),
			jen.List(jen.Id("co"), jen.Id("ok")).Op(":=").Id("i").Dot("heap").Index(jen.Id("coAddr")).Assert(jen.Op("*").Id("coroutine")),
			jen.If(jen.Op("!").Id("ok")).Block(jen.Panic(jen.Id("ErrTypeMismatch"))),
			jen.Id("i").Dot("sp").Op("--"),
			jen.Id("co").Dot("value").Op("=").Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")),
			jen.Id("co").Dot("addr").Op("=").Id("f").Dot("addr"),
			jen.Id("co").Dot("ref").Op("=").Id("f").Dot("ref"),
			jen.Id("co").Dot("returns").Op("=").Id("f").Dot("returns"),
			jen.Id("co").Dot("release").Op("=").Id("f").Dot("release"),
			jen.Id("co").Dot("ip").Op("=").Id("f").Dot("ip"),
			jen.Id("co").Dot("upvals").Op("=").Id("f").Dot("upvals"),
			jen.Id("co").Dot("image").Op("=").Id("append").Call(jen.Id("co").Dot("image").Index(jen.Empty().Op(":").Lit(0)), jen.Id("i").Dot("stack").Index(jen.Id("f").Dot("bp").Op(":").Id("i").Dot("sp")).Op("...")),
			jen.Id("bp").Op(":=").Id("f").Dot("bp"),
			jen.Id("clear").Call(jen.Id("i").Dot("stack").Index(jen.Id("bp").Op(":").Id("i").Dot("sp"))),
			jen.Id("f").Dot("code").Op("=").Add(jen.Nil()),
			jen.Id("f").Dot("upvals").Op("=").Add(jen.Nil()),
			jen.Id("f").Dot("coro").Op("=").Lit(0),
			jen.Id("i").Dot("fp").Op("--"),
			jen.Id("i").Dot("fr").Op("=").Op("&").Id("i").Dot("frames").Index(jen.Id("i").Dot("fp").Op("-").Add(jen.Lit(1))),
			jen.Id("i").Dot("stack").Index(jen.Id("bp")).Op("=").Qual(typesPkg, "BoxRef").Call(jen.Id("coAddr")),
			jen.Id("i").Dot("sp").Op("=").Id("bp").Op("+").Lit(1)))
}

func resume() jen.Code {
	return handler(jen.Block(underflow(2),
		jen.If(jen.Id("i").Dot("fp").Op("==").Id("len").Call(jen.Id("i").Dot("frames"))).Block(jen.Panic(jen.Id("ErrFrameOverflow"))),
		jen.Id("in").Op(":=").Add(top(1)),
		jen.Id("box").Op(":=").Add(top(2)),
		reference(jen.Id("box")),
		jen.Id("coAddr").Op(":=").Id("box").Dot("Ref").Call(),
		jen.Switch(jen.Id("co").Op(":=").Id("i").Dot("heap").Index(jen.Id("coAddr")).Assert(jen.Type())).Block(jen.Case(jen.Op("*").Id("coroutine")).Block(jen.Block(jen.Id("coAddr").Op(":=").Id("coAddr"),
			jen.Id("co").Op(":=").Id("co"),
			jen.Id("in").Op(":=").Id("in"),
			jen.If(jen.Id("co").Dot("done")).Block(jen.Panic(jen.Id("ErrCoroutineDone"))),
			jen.Id("i").Dot("sp").Op("-=").Lit(2),
			jen.Id("base").Op(":=").Id("i").Dot("sp"),
			jen.If(jen.Id("base").Op("+").Id("len").Call(jen.Id("co").Dot("image")).Op("+").Lit(1).Op(">").Id("len").Call(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("i").Dot("releaseBox").Call(jen.Id("co").Dot("value")),
			jen.Id("co").Dot("value").Op("=").Qual(typesPkg, "Boxed").Call(jen.Lit(0)),
			jen.Id("copy").Call(jen.Id("i").Dot("stack").Index(jen.Id("base").Op(":").Add(jen.Empty())), jen.Id("co").Dot("image")),
			jen.Id("i").Dot("sp").Op("=").Id("base").Op("+").Id("len").Call(jen.Id("co").Dot("image")),
			jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Id("in"),
			jen.Id("i").Dot("sp").Op("++"),
			jen.Id("f").Op(":=").Op("&").Id("i").Dot("frames").Index(jen.Id("i").Dot("fp")),
			jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Id("co").Dot("addr")),
			jen.Id("f").Dot("upvals").Op("=").Id("co").Dot("upvals"),
			jen.Id("f").Dot("addr").Op("=").Id("co").Dot("addr"),
			jen.Id("f").Dot("ref").Op("=").Id("co").Dot("ref"),
			jen.Id("f").Dot("returns").Op("=").Id("co").Dot("returns"),
			jen.Id("f").Dot("release").Op("=").Id("co").Dot("release"),
			jen.Id("f").Dot("ip").Op("=").Id("co").Dot("ip"),
			jen.Id("f").Dot("bp").Op("=").Id("base"),
			jen.Id("f").Dot("coro").Op("=").Id("coAddr"),
			jen.Id("co").Dot("image").Op("=").Id("co").Dot("image").Index(jen.Empty().Op(":").Lit(0)),
			jen.Id("co").Dot("upvals").Op("=").Add(jen.Nil()),
			jen.Id("co").Dot("ref").Op("=").Lit(0),
			jen.Id("co").Dot("release").Op("=").Id("false"),
			next(),
			jen.Id("i").Dot("fp").Op("++"),
			jen.Id("i").Dot("fr").Op("=").Id("f"),
		)),
			jen.Case(jen.Qual(typesPkg, "Iterator")).Block(jen.Block(jen.Id("iter").Op(":=").Id("co"),
				jen.Id("in").Op(":=").Id("in"),
				jen.If(jen.Id("iter").Dot("Done").Call()).Block(jen.Panic(jen.Id("ErrCoroutineDone"))),
				jen.Id("i").Dot("releaseBox").Call(jen.Id("in")),
				jen.Block(jen.Id("iter").Op(":=").Id("iter"),
					jen.If(jen.Id("iter").Dot("Done").Call()).Block(jen.Goto().Id("inlineReleaseiteratorcurrent7")),
					jen.If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").Id("iter").Assert(jen.Op("*").Qual(typesPkg, "MapIterator")), jen.Id("ok")).Block(jen.Block(jen.Id("val").Op(":=").Id("iter").Dot("Current").Call(),
						jen.Switch(jen.Id("val").Op(":=").Id("val").Assert(jen.Type())).Block(jen.Case(jen.Qual(typesPkg, "Boxed")).Block(jen.Id("i").Dot("releaseBox").Call(jen.Id("val"))),
							jen.Case(jen.Qual(typesPkg, "Ref")).Block(jen.Id("i").Dot("release").Call(jen.Id("int").Call(jen.Id("val"))))))),
					jen.Id("inlineReleaseiteratorcurrent7").Op(":").Add(jen.Null())),
				jen.Id("iter").Dot("Next").Call(),
				jen.Block(jen.Id("iter").Op(":=").Id("iter"),
					jen.If(jen.Id("iter").Dot("Done").Call()).Block(jen.Goto().Id("inlineRetainiteratorcurrent8")),
					jen.If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").Id("iter").Assert(jen.Op("*").Qual(typesPkg, "MapIterator")), jen.Id("ok")).Block(jen.Block(jen.Id("val").Op(":=").Id("iter").Dot("Current").Call(),
						jen.Switch(jen.Id("val").Op(":=").Id("val").Assert(jen.Type())).Block(jen.Case(jen.Qual(typesPkg, "Boxed")).Block(jen.Id("i").Dot("retainBox").Call(jen.Id("val"))),
							jen.Case(jen.Qual(typesPkg, "Ref")).Block(jen.Id("i").Dot("retain").Call(jen.Id("int").Call(jen.Id("val"))))))),
					jen.Id("inlineRetainiteratorcurrent8").Op(":").Add(jen.Null())),
				jen.Id("i").Dot("sp").Op("--"),
				next())),
			jen.Default().Block(jen.Panic(jen.Id("ErrTypeMismatch"))))))
}

func coroDone() jen.Code {
	return handler(underflow(1),
		jen.Id("ref").Op(":=").Add(top(1)),
		reference(jen.Id("ref")),
		jen.Id("done").Op(":=").Id("int32").Call(jen.Lit(0)),
		jen.Switch(jen.Id("co").Op(":=").Id("i").Dot("heap").Index(jen.Id("ref").Dot("Ref").Call()).Assert(jen.Type())).Block(jen.Case(jen.Op("*").Id("coroutine")).Block(jen.If(jen.Id("co").Dot("done")).Block(jen.Id("done").Op("=").Lit(1))),
			jen.Case(jen.Qual(typesPkg, "Iterator")).Block(jen.If(jen.Id("co").Dot("Done").Call()).Block(jen.Id("done").Op("=").Lit(1))),
			jen.Default().Block(jen.Panic(jen.Id("ErrTypeMismatch")))),
		top(1).Op("=").Qual(typesPkg, "BoxI1").Call(jen.Id("done").Op("!=").Lit(0)),
		next())
}

func coroValue() jen.Code {
	return handler(underflow(1),
		jen.Id("box").Op(":=").Add(top(1)),
		reference(jen.Id("box")),
		jen.Var().Id("val").Qual(typesPkg, "Boxed"),
		jen.Switch(jen.Id("co").Op(":=").Id("i").Dot("heap").Index(jen.Id("box").Dot("Ref").Call()).Assert(jen.Type())).Block(jen.Case(jen.Op("*").Id("coroutine")).Block(jen.Id("val").Op("=").Id("co").Dot("value"),
			jen.Id("i").Dot("retainBox").Call(jen.Id("val"))),
			jen.Case(jen.Qual(typesPkg, "Iterator")).Block(jen.Id("current").Op(":=").Id("co").Dot("Current").Call(),
				jen.If(jen.Id("current").Op("==").Add(jen.Nil())).Block(jen.Id("i").Dot("retain").Call(jen.Lit(0)),
					jen.Id("val").Op("=").Qual(typesPkg, "BoxedNull")).Else().Block(jen.Id("val").Op("=").Id("i").Dot("box").Call(jen.Id("current")),
					jen.Switch(jen.Id("current").Op(":=").Id("current").Assert(jen.Type())).Block(jen.Case(jen.Qual(typesPkg, "Boxed")).Block(jen.Id("i").Dot("retainBox").Call(jen.Id("current"))),
						jen.Case(jen.Qual(typesPkg, "Ref")).Block(jen.Id("i").Dot("retain").Call(jen.Id("int").Call(jen.Id("current"))))))),
			jen.Default().Block(jen.Panic(jen.Id("ErrTypeMismatch")))),
		jen.Id("i").Dot("releaseBox").Call(jen.Id("box")),
		top(1).Op("=").Id("val"),
		next())
}
