package codegen

import (
	"github.com/dave/jennifer/jen"
)

func coroDone() jen.Code {
	return jen.Func().Params(jen.Id("c").Add(jen.Op("*").Add(jen.Id("threader")))).Params(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter"))))).Block(jen.Id("c").Dot("ip").Op("++"),
		jen.Return(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter")))).Block(jen.If(jen.Id("i").Dot("sp").Op("==").Add(jen.Lit(0))).Block(jen.Id("panic").Call(jen.Id("ErrStackUnderflow"))),
			jen.List(jen.Id("ref")).Op(":=").List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Add(jen.Lit(1)))),
			jen.If(jen.Id("ref").Dot("Kind").Call().Op("!=").Add(jen.Id("types").Dot("KindRef"))).Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch"))),
			jen.List(jen.Id("done")).Op(":=").List(jen.Id("int32").Call(jen.Lit(0))),
			jen.Switch(jen.List(jen.Id("co")).Op(":=").List(jen.Id("i").Dot("heap").Index(jen.Id("ref").Dot("Ref").Call()).Assert(jen.Type()))).Block(jen.Case(jen.Op("*").Add(jen.Id("coroutine"))).Block(jen.If(jen.Id("co").Dot("done")).Block(jen.List(jen.Id("done")).Op("=").List(jen.Lit(1)))),
				jen.Case(jen.Id("types").Dot("Iterator")).Block(jen.If(jen.Id("co").Dot("Done").Call()).Block(jen.List(jen.Id("done")).Op("=").List(jen.Lit(1)))),
				jen.Default().Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch")))),
			jen.List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Add(jen.Lit(1)))).Op("=").List(jen.Id("types").Dot("BoxI1").Call(jen.Id("done").Op("!=").Add(jen.Lit(0)))),
			jen.Id("i").Dot("fr").Dot("ip").Op("++"))))
}

func coroValue() jen.Code {
	return jen.Func().Params(jen.Id("c").Add(jen.Op("*").Add(jen.Id("threader")))).Params(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter"))))).Block(jen.Id("c").Dot("ip").Op("++"),
		jen.Return(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter")))).Block(jen.If(jen.Id("i").Dot("sp").Op("==").Add(jen.Lit(0))).Block(jen.Id("panic").Call(jen.Id("ErrStackUnderflow"))),
			jen.List(jen.Id("box")).Op(":=").List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Add(jen.Lit(1)))),
			jen.If(jen.Id("box").Dot("Kind").Call().Op("!=").Add(jen.Id("types").Dot("KindRef"))).Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch"))),
			jen.Var().Add(jen.List(jen.Id("val"))).Add(jen.Id("types").Dot("Boxed")),
			jen.Switch(jen.List(jen.Id("co")).Op(":=").List(jen.Id("i").Dot("heap").Index(jen.Id("box").Dot("Ref").Call()).Assert(jen.Type()))).Block(jen.Case(jen.Op("*").Add(jen.Id("coroutine"))).Block(jen.List(jen.Id("val")).Op("=").List(jen.Id("co").Dot("value")),
				jen.Id("i").Dot("retainBox").Call(jen.Id("val"))),
				jen.Case(jen.Id("types").Dot("Iterator")).Block(jen.List(jen.Id("current")).Op(":=").List(jen.Id("co").Dot("Current").Call()),
					jen.If(jen.Id("current").Op("==").Add(jen.Id("nil"))).Block(jen.Id("i").Dot("retain").Call(jen.Lit(0)),
						jen.List(jen.Id("val")).Op("=").List(jen.Id("types").Dot("BoxedNull"))).Else().Block(jen.List(jen.Id("val")).Op("=").List(jen.Id("i").Dot("box").Call(jen.Id("current"))),
						jen.Switch(jen.List(jen.Id("current")).Op(":=").List(jen.Id("current").Assert(jen.Type()))).Block(jen.Case(jen.Id("types").Dot("Boxed")).Block(jen.Id("i").Dot("retainBox").Call(jen.Id("current"))),
							jen.Case(jen.Id("types").Dot("Ref")).Block(jen.Id("i").Dot("retain").Call(jen.Id("int").Call(jen.Id("current"))))))),
				jen.Default().Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch")))),
			jen.Id("i").Dot("releaseBox").Call(jen.Id("box")),
			jen.List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Add(jen.Lit(1)))).Op("=").List(jen.Id("val")),
			jen.Id("i").Dot("fr").Dot("ip").Op("++"))))
}

func resume() jen.Code {
	return jen.Func().Params(jen.Id("c").Add(jen.Op("*").Add(jen.Id("threader")))).Params(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter"))))).Block(jen.Id("c").Dot("ip").Op("++"),
		jen.Return(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter")))).Block(jen.Block(jen.If(jen.Id("i").Dot("sp").Op("<").Add(jen.Lit(2))).Block(jen.Id("panic").Call(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("fp").Op("==").Add(jen.Id("len").Call(jen.Id("i").Dot("frames")))).Block(jen.Id("panic").Call(jen.Id("ErrFrameOverflow"))),
			jen.List(jen.Id("in")).Op(":=").List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Add(jen.Lit(1)))),
			jen.List(jen.Id("box")).Op(":=").List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Add(jen.Lit(2)))),
			jen.If(jen.Id("box").Dot("Kind").Call().Op("!=").Add(jen.Id("types").Dot("KindRef"))).Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch"))),
			jen.List(jen.Id("coAddr")).Op(":=").List(jen.Id("box").Dot("Ref").Call()),
			jen.Switch(jen.List(jen.Id("co")).Op(":=").List(jen.Id("i").Dot("heap").Index(jen.Id("coAddr")).Assert(jen.Type()))).Block(jen.Case(jen.Op("*").Add(jen.Id("coroutine"))).Block(jen.Block(jen.List(jen.Id("coAddr")).Op(":=").List(jen.Id("coAddr")),
				jen.List(jen.Id("co")).Op(":=").List(jen.Id("co")),
				jen.List(jen.Id("in")).Op(":=").List(jen.Id("in")),
				jen.If(jen.Id("co").Dot("done")).Block(jen.Id("panic").Call(jen.Id("ErrCoroutineDone"))),
				jen.List(jen.Id("i").Dot("sp")).Op("-=").List(jen.Lit(2)),
				jen.List(jen.Id("base")).Op(":=").List(jen.Id("i").Dot("sp")),
				jen.If(jen.Id("base").Op("+").Add(jen.Id("len").Call(jen.Id("co").Dot("image"))).Op("+").Add(jen.Lit(1)).Op(">").Add(jen.Id("len").Call(jen.Id("i").Dot("stack")))).Block(jen.Id("panic").Call(jen.Id("ErrStackOverflow"))),
				jen.Id("i").Dot("releaseBox").Call(jen.Id("co").Dot("value")),
				jen.List(jen.Id("co").Dot("value")).Op("=").List(jen.Id("types").Dot("Boxed").Call(jen.Lit(0))),
				jen.Id("copy").Call(jen.Id("i").Dot("stack").Index(jen.Id("base").Op(":").Add(jen.Empty())), jen.Id("co").Dot("image")),
				jen.List(jen.Id("i").Dot("sp")).Op("=").List(jen.Id("base").Op("+").Add(jen.Id("len").Call(jen.Id("co").Dot("image")))),
				jen.List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp"))).Op("=").List(jen.Id("in")),
				jen.Id("i").Dot("sp").Op("++"),
				jen.List(jen.Id("f")).Op(":=").List(jen.Op("&").Add(jen.Id("i").Dot("frames").Index(jen.Id("i").Dot("fp")))),
				jen.List(jen.Id("f").Dot("code")).Op("=").List(jen.Id("i").Dot("code").Index(jen.Id("co").Dot("addr"))),
				jen.List(jen.Id("f").Dot("upvals")).Op("=").List(jen.Id("co").Dot("upvals")),
				jen.List(jen.Id("f").Dot("addr")).Op("=").List(jen.Id("co").Dot("addr")),
				jen.List(jen.Id("f").Dot("ref")).Op("=").List(jen.Id("co").Dot("ref")),
				jen.List(jen.Id("f").Dot("returns")).Op("=").List(jen.Id("co").Dot("returns")),
				jen.List(jen.Id("f").Dot("release")).Op("=").List(jen.Id("co").Dot("release")),
				jen.List(jen.Id("f").Dot("ip")).Op("=").List(jen.Id("co").Dot("ip")),
				jen.List(jen.Id("f").Dot("bp")).Op("=").List(jen.Id("base")),
				jen.List(jen.Id("f").Dot("coro")).Op("=").List(jen.Id("coAddr")),
				jen.List(jen.Id("co").Dot("image")).Op("=").List(jen.Id("co").Dot("image").Index(jen.Empty().Op(":").Add(jen.Lit(0)))),
				jen.List(jen.Id("co").Dot("upvals")).Op("=").List(jen.Id("nil")),
				jen.List(jen.Id("co").Dot("ref")).Op("=").List(jen.Lit(0)),
				jen.List(jen.Id("co").Dot("release")).Op("=").List(jen.Id("false")),
				jen.Id("i").Dot("fr").Dot("ip").Op("++"),
				jen.Id("i").Dot("fp").Op("++"),
				jen.List(jen.Id("i").Dot("fr")).Op("=").List(jen.Id("f")),
				frameEntered())),
				jen.Case(jen.Id("types").Dot("Iterator")).Block(jen.Block(jen.List(jen.Id("iter")).Op(":=").List(jen.Id("co")),
					jen.List(jen.Id("in")).Op(":=").List(jen.Id("in")),
					jen.If(jen.Id("iter").Dot("Done").Call()).Block(jen.Id("panic").Call(jen.Id("ErrCoroutineDone"))),
					jen.Id("i").Dot("releaseBox").Call(jen.Id("in")),
					jen.Block(jen.List(jen.Id("iter")).Op(":=").List(jen.Id("iter")),
						jen.If(jen.Id("iter").Dot("Done").Call()).Block(jen.Goto().Id("inlineReleaseiteratorcurrent7")),
						jen.If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").List(jen.Id("iter").Assert(jen.Op("*").Add(jen.Id("types").Dot("MapIterator")))), jen.Id("ok")).Block(jen.Block(jen.List(jen.Id("val")).Op(":=").List(jen.Id("iter").Dot("Current").Call()),
							jen.Switch(jen.List(jen.Id("val")).Op(":=").List(jen.Id("val").Assert(jen.Type()))).Block(jen.Case(jen.Id("types").Dot("Boxed")).Block(jen.Id("i").Dot("releaseBox").Call(jen.Id("val"))),
								jen.Case(jen.Id("types").Dot("Ref")).Block(jen.Id("i").Dot("release").Call(jen.Id("int").Call(jen.Id("val"))))))),
						jen.Id("inlineReleaseiteratorcurrent7").Op(":").Add(jen.Null())),
					jen.Id("iter").Dot("Next").Call(),
					jen.Block(jen.List(jen.Id("iter")).Op(":=").List(jen.Id("iter")),
						jen.If(jen.Id("iter").Dot("Done").Call()).Block(jen.Goto().Id("inlineRetainiteratorcurrent8")),
						jen.If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").List(jen.Id("iter").Assert(jen.Op("*").Add(jen.Id("types").Dot("MapIterator")))), jen.Id("ok")).Block(jen.Block(jen.List(jen.Id("val")).Op(":=").List(jen.Id("iter").Dot("Current").Call()),
							jen.Switch(jen.List(jen.Id("val")).Op(":=").List(jen.Id("val").Assert(jen.Type()))).Block(jen.Case(jen.Id("types").Dot("Boxed")).Block(jen.Id("i").Dot("retainBox").Call(jen.Id("val"))),
								jen.Case(jen.Id("types").Dot("Ref")).Block(jen.Id("i").Dot("retain").Call(jen.Id("int").Call(jen.Id("val"))))))),
						jen.Id("inlineRetainiteratorcurrent8").Op(":").Add(jen.Null())),
					jen.Id("i").Dot("sp").Op("--"),
					jen.Id("i").Dot("fr").Dot("ip").Op("++"))),
				jen.Default().Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch"))))))))
}

func yield() jen.Code {
	return jen.Func().Params(jen.Id("c").Add(jen.Op("*").Add(jen.Id("threader")))).Params(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter"))))).Block(jen.Id("c").Dot("ip").Op("++"),
		jen.Return(jen.Func().Params(jen.Id("i").Add(jen.Op("*").Add(jen.Id("Interpreter")))).Block(jen.If(jen.Id("i").Dot("sp").Op("==").Add(jen.Lit(0))).Block(jen.Id("panic").Call(jen.Id("ErrStackUnderflow"))),
			jen.Id("i").Dot("fr").Dot("ip").Op("++"),
			jen.If(jen.Id("i").Dot("fp").Op("==").Add(jen.Lit(1))).Block(jen.Id("panic").Call(jen.Id("errYield"))),
			jen.Block(jen.List(jen.Id("f")).Op(":=").List(jen.Id("i").Dot("fr")),
				jen.List(jen.Id("coAddr")).Op(":=").List(jen.Id("f").Dot("coro")),
				jen.List(jen.Id("co"), jen.Id("ok")).Op(":=").List(jen.Id("i").Dot("heap").Index(jen.Id("coAddr")).Assert(jen.Op("*").Add(jen.Id("coroutine")))),
				jen.If(jen.Op("!").Add(jen.Id("ok"))).Block(jen.Id("panic").Call(jen.Id("ErrTypeMismatch"))),
				jen.Id("i").Dot("sp").Op("--"),
				jen.List(jen.Id("co").Dot("value")).Op("=").List(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp"))),
				jen.List(jen.Id("co").Dot("addr")).Op("=").List(jen.Id("f").Dot("addr")),
				jen.List(jen.Id("co").Dot("ref")).Op("=").List(jen.Id("f").Dot("ref")),
				jen.List(jen.Id("co").Dot("returns")).Op("=").List(jen.Id("f").Dot("returns")),
				jen.List(jen.Id("co").Dot("release")).Op("=").List(jen.Id("f").Dot("release")),
				jen.List(jen.Id("co").Dot("ip")).Op("=").List(jen.Id("f").Dot("ip")),
				jen.List(jen.Id("co").Dot("upvals")).Op("=").List(jen.Id("f").Dot("upvals")),
				jen.List(jen.Id("co").Dot("image")).Op("=").List(jen.Id("append").Call(jen.Id("co").Dot("image").Index(jen.Empty().Op(":").Add(jen.Lit(0))), jen.Id("i").Dot("stack").Index(jen.Id("f").Dot("bp").Op(":").Add(jen.Id("i").Dot("sp"))).Op("..."))),
				jen.List(jen.Id("bp")).Op(":=").List(jen.Id("f").Dot("bp")),
				jen.Id("clear").Call(jen.Id("i").Dot("stack").Index(jen.Id("bp").Op(":").Add(jen.Id("i").Dot("sp")))),
				jen.List(jen.Id("f").Dot("code")).Op("=").List(jen.Id("nil")),
				jen.List(jen.Id("f").Dot("upvals")).Op("=").List(jen.Id("nil")),
				jen.List(jen.Id("f").Dot("coro")).Op("=").List(jen.Lit(0)),
				jen.Id("i").Dot("fp").Op("--"),
				jen.List(jen.Id("i").Dot("fr")).Op("=").List(jen.Op("&").Add(jen.Id("i").Dot("frames").Index(jen.Id("i").Dot("fp").Op("-").Add(jen.Lit(1))))),
				jen.List(jen.Id("i").Dot("stack").Index(jen.Id("bp"))).Op("=").List(jen.Id("types").Dot("BoxRef").Call(jen.Id("coAddr"))),
				jen.List(jen.Id("i").Dot("sp")).Op("=").List(jen.Id("bp").Op("+").Add(jen.Lit(1)))))))
}
