package codegen_test

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"regexp"
	"testing"

	"github.com/siyul-park/minivm/internal/codegen"
	"github.com/stretchr/testify/require"
)

func TestGenerate(t *testing.T) {
	t.Run("output", func(t *testing.T) {
		files, err := codegen.Generate()
		require.NoError(t, err)
		require.Len(t, files, 1)
		require.Equal(t, "interp/threaded.go", files[0].Path)
		require.True(t, bytes.HasPrefix(files[0].Data, []byte("// Code generated by internal/cmd/codegen; DO NOT EDIT.\n")))

		file, err := parser.ParseFile(token.NewFileSet(), files[0].Path, files[0].Data, 0)
		require.NoError(t, err)
		require.Equal(t, "interp", file.Name.Name)

		foundThreader := false
		foundInit := false
		foundCompile := false
		forbidden := map[string]struct{}{
			"arrayGetAt": {}, "branchIf": {}, "callHost": {}, "finish": {},
			"refGet": {}, "releaseArgs": {}, "resume": {}, "ret": {},
			"structGetAt": {}, "suspend": {}, "tail": {},
		}
		ast.Inspect(file, func(node ast.Node) bool {
			switch node := node.(type) {
			case *ast.TypeSpec:
				_, structure := node.Type.(*ast.StructType)
				foundThreader = foundThreader || node.Name.Name == "threader" && structure
			case *ast.FuncDecl:
				if node.Recv == nil {
					foundInit = foundInit || node.Name.Name == "init"
					return true
				}
				for _, field := range node.Recv.List {
					name := field.Type
					if star, ok := name.(*ast.StarExpr); ok {
						name = star.X
					}
					ident, ok := name.(*ast.Ident)
					if !ok {
						continue
					}
					if ident.Name == "Interpreter" {
						require.Fail(t, "generated Interpreter method")
					}
					if pointer, ok := field.Type.(*ast.StarExpr); ok {
						ident, ok := pointer.X.(*ast.Ident)
						foundCompile = foundCompile || ok && ident.Name == "threader" && node.Name.Name == "Compile"
					}
				}
			case *ast.CallExpr:
				selector, ok := node.Fun.(*ast.SelectorExpr)
				if ok {
					_, found := forbidden[selector.Sel.Name]
					require.False(t, found)
				}
			}
			return true
		})
		require.True(t, foundThreader)
		require.True(t, foundInit)
		require.True(t, foundCompile)
	})

	t.Run("deterministic", func(t *testing.T) {
		first, err := codegen.Generate()
		require.NoError(t, err)
		second, err := codegen.Generate()
		require.NoError(t, err)
		require.Equal(t, first, second)
	})

	t.Run("local names", func(t *testing.T) {
		files, err := codegen.Generate()
		require.NoError(t, err)
		file, err := parser.ParseFile(token.NewFileSet(), files[0].Path, files[0].Data, 0)
		require.NoError(t, err)

		allowed := regexp.MustCompile("^v[0-9]+$")
		var bad []string
		check := func(idents ...*ast.Ident) {
			for _, ident := range idents {
				if ident != nil && ident.Name != "_" && !allowed.MatchString(ident.Name) {
					bad = append(bad, ident.Name)
				}
			}
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			ast.Inspect(fn.Body, func(node ast.Node) bool {
				switch node := node.(type) {
				case *ast.AssignStmt:
					if node.Tok == token.DEFINE {
						for _, left := range node.Lhs {
							if ident, ok := left.(*ast.Ident); ok {
								check(ident)
							}
						}
					}
				case *ast.GenDecl:
					if node.Tok == token.VAR {
						for _, spec := range node.Specs {
							value, ok := spec.(*ast.ValueSpec)
							if ok {
								check(value.Names...)
							}
						}
					}
				case *ast.RangeStmt:
					if node.Tok == token.DEFINE {
						key, _ := node.Key.(*ast.Ident)
						value, _ := node.Value.(*ast.Ident)
						check(key, value)
					}
				}
				return true
			})
		}
		require.Empty(t, bad)
	})
}
