package codegen_test

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"github.com/siyul-park/minivm/internal/codegen"
	"github.com/stretchr/testify/require"
)

func TestGenerate(t *testing.T) {
	files, err := codegen.Generate()
	require.NoError(t, err)
	require.Len(t, files, 1)

	generated := files[0]
	require.Equal(t, "interp/threaded.go", generated.Path)
	require.True(t, bytes.HasPrefix(generated.Data, []byte("// Code generated by internal/cmd/codegen; DO NOT EDIT.\n")))

	t.Run("output is deterministic", func(t *testing.T) {
		again, err := codegen.Generate()
		require.NoError(t, err)
		require.Len(t, again, 1)
		require.Equal(t, generated.Path, again[0].Path)
		require.Equal(t, generated.Data, again[0].Data)
	})

	t.Run("output declares the threader dispatch surface", func(t *testing.T) {
		file, err := parser.ParseFile(token.NewFileSet(), generated.Path, generated.Data, 0)
		require.NoError(t, err)
		require.Equal(t, "interp", file.Name.Name)

		forbidden := map[string]struct{}{
			"arrayGetAt": {}, "branchIf": {}, "callHost": {}, "finish": {},
			"refGet": {}, "releaseArgs": {}, "resume": {}, "ret": {},
			"structGetAt": {}, "suspend": {}, "tail": {},
		}
		foundThreader := false
		foundInit := false
		foundCompile := false
		ast.Inspect(file, func(node ast.Node) bool {
			switch node := node.(type) {
			case *ast.TypeSpec:
				_, structure := node.Type.(*ast.StructType)
				foundThreader = foundThreader || node.Name.Name == "threader" && structure
			case *ast.FuncDecl:
				if node.Recv == nil {
					foundInit = foundInit || node.Name.Name == "init"
					return true
				}
				for _, field := range node.Recv.List {
					name := field.Type
					if star, ok := name.(*ast.StarExpr); ok {
						name = star.X
					}
					ident, ok := name.(*ast.Ident)
					if !ok {
						continue
					}
					if ident.Name == "Interpreter" {
						require.Fail(t, "generated Interpreter method", generated.Path+":"+node.Name.Name)
					}
					if pointer, ok := field.Type.(*ast.StarExpr); ok {
						ident, ok := pointer.X.(*ast.Ident)
						foundCompile = foundCompile || ok && ident.Name == "threader" && node.Name.Name == "Compile"
					}
				}
			case *ast.CallExpr:
				selector, ok := node.Fun.(*ast.SelectorExpr)
				if ok {
					_, found := forbidden[selector.Sel.Name]
					require.False(t, found, generated.Path+":"+selector.Sel.Name)
				}
			}
			return true
		})
		require.True(t, foundThreader)
		require.True(t, foundInit)
		require.True(t, foundCompile)
	})
}
