// Package codegen renders interp/threaded.go from the fusion pattern catalog.
package codegen

import (
	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/imports"
)

// File is one generated source file.
type File struct {
	Path string
	Data []byte
}

// Generate validates the fusion catalog and renders every generated file.
func Generate() ([]File, error) {
	patterns := catalog()
	if err := validate(patterns); err != nil {
		return nil, err
	}
	threaded, err := render(patterns)
	if err != nil {
		return nil, err
	}
	threaded, err = imports.Process("", threaded, nil)
	if err != nil {
		return nil, err
	}
	return []File{{Path: "interp/threaded.go", Data: threaded}}, nil
}

func render(patterns []pattern) ([]byte, error) {
	file := jen.NewFile("interp")
	file.HeaderComment("Code generated by internal/cmd/codegen; DO NOT EDIT.")
	file.ImportName("github.com/siyul-park/minivm/instr", "instr")
	file.ImportName("github.com/siyul-park/minivm/types", "types")

	threaderType(file)
	table, err := fusionTable(patterns)
	if err != nil {
		return nil, err
	}
	file.Var().Defs(
		jen.Id("threaded").Op("=").Add(handlerTable()),
		jen.Id("fusions").Op("=").Add(table),
		jen.Id("invalid").Op("=").Func().Params(jen.Id("_").Op("*").Id("Interpreter")).Block(jen.Panic(jen.Id("ErrUnknownOpcode"))),
	)
	fallbackInit(file)
	compileMethod(file)
	file.Line()
	threaderMethods(file)
	return []byte(file.GoString()), nil
}
