//go:build arm64

// Code generated by internal/cmd/genfusion; DO NOT EDIT.

package interp

import (
	"github.com/siyul-park/minivm/asm"
	"github.com/siyul-park/minivm/asm/arm64"
	"github.com/siyul-park/minivm/instr"
	"github.com/siyul-park/minivm/types"
)

func (l arm64Lowerer) fusion(ctx *lowering, ops, tail []step, idx int) (int, bool) {
	v0 := l.match(ctx, ops, idx)
	if v0 == 0 {
		return 0, true
	}
	r0 := ops[idx]
	r1 := ops[idx+1]
	if r0.op == instr.CONST_GET && (r1.op == instr.CALL || r1.op == instr.RETURN_CALL) {
		f := ctx.frame()
		i3 := int(uint16(f.code[r0.ip+1]) | uint16(f.code[r0.ip+2])<<8)
		if i3 >= len(ctx.constants) || ctx.constants[i3].Kind() != types.KindRef {
			return 0, true
		}
		r4 := ctx.constants[i3].Ref()
		if r4 < 0 || r4 >= len(ctx.heap) {
			return 0, true
		}
		callee := r4
		if closure, ok := ctx.heap[r4].(*types.Closure); ok {
			callee = int(closure.Fn)
		} else if _, ok := ctx.heap[r4].(*types.Function); !ok {
			return 0, true
		}
		if callee != r1.callee || ctx.funcs[callee] == nil {
			return 0, true
		}
		ctx.push(value{
			fn:   callee,
			kind: types.KindRef,
			raw:  true,
			ref:  r4,
		})
		if r1.op == instr.CALL {
			if !l.call(ctx, r1) {
				return 0, false
			}
		} else if r1.callee == ctx.addr {
			if !l.tailLoop(ctx, r1) {
				return 0, false
			}
		} else if !l.tailMorph(ctx, r1) {
			return 0, false
		}
		return 2, true
	}
	r2 := step{}
	if v0 == 3 {
		r2 = ops[idx+2]
	}
	f := ctx.frame()
	var (
		i0 int
		i1 int
		i2 int
		i3 int
		i4 int
		r3 types.Boxed
	)
	switch r0.op {
	case instr.LOCAL_GET:
		i0 = int(f.code[r0.ip+1])
		if i0 >= len(f.kinds) || f.kinds[i0] != types.KindRef {
			return 0, true
		}
	case instr.GLOBAL_GET:
		i1 = int(uint16(f.code[r0.ip+1]) | uint16(f.code[r0.ip+2])<<8)
		if i1 >= len(ctx.globals) || i1 > 4095 || ctx.globals[i1] != types.KindRef {
			return 0, true
		}
	case instr.UPVAL_GET:
		i2 = int(f.code[r0.ip+1])
		if i2 >= len(f.upvals) || f.upvals[i2] != types.KindRef {
			return 0, true
		}
	case instr.CONST_GET:
		i3 = int(uint16(f.code[r0.ip+1]) | uint16(f.code[r0.ip+2])<<8)
		if i3 >= len(ctx.constants) || ctx.constants[i3].Kind() != types.KindRef {
			return 0, true
		}
		r3 = ctx.constants[i3]
		i4 = r3.Ref()
		if i4 < 0 || i4 >= len(ctx.heap) {
			return 0, true
		}
		if _, stringConstant := ctx.heap[i4].(types.String); stringConstant {
			return 0, true
		}
	case instr.REF_NULL:
	case instr.DUP:
		if ctx.count() < 1 || ctx.values[len(ctx.values)-1].kind != types.KindRef {
			return 0, true
		}
	default:
		return 0, true
	}
	r4 := asm.VReg{}
	switch r0.op {
	case instr.LOCAL_GET:
		if r1.op == instr.DROP {
			return 2, true
		}
		if !l.loadLocal(ctx, f, i0, r0.ip) {
			return 0, false
		}
		r4 = f.locals[i0].reg
	case instr.GLOBAL_GET:
		if r1.op == instr.DROP {
			return 2, true
		}
		r4 = ctx.assembler.Reg(asm.RegTypeInt, asm.Width64)
		ctx.assembler.Emit(arm64.LDR(r4, ctx.pin(scratchGlobals), int16(i1*8)))
	case instr.UPVAL_GET:
		if r1.op == instr.DROP {
			return 2, true
		}
		r4 = ctx.assembler.Reg(asm.RegTypeInt, asm.Width64)
		ctx.assembler.Emit(arm64.LDR(r4, l.upvalBase(ctx), int16(i2*8)))
	case instr.CONST_GET:
		if r1.op == instr.DROP {
			return 2, true
		}
		r4 = ctx.assembler.Reg(asm.RegTypeInt, asm.Width64)
		ctx.assembler.Emit(arm64.LDI(r4, uint64(r3))...)
	case instr.REF_NULL:
		if r1.op == instr.DROP {
			return 2, true
		}
		r4 = ctx.assembler.Reg(asm.RegTypeInt, asm.Width64)
		ctx.assembler.Emit(arm64.LDI(r4, uint64(types.BoxedNull))...)
	case instr.DUP:
		if r1.op == instr.DROP {
			return 2, true
		}
		var ok bool
		r4, ok = l.box(ctx, ctx.values[len(ctx.values)-1])
		if !ok {
			return 0, false
		}
	default:
		return 0, true
	}
	r5 := ctx.assembler.Reg(asm.RegTypeInt, asm.Width64)
	r6 := ctx.assembler.Reg(asm.RegTypeInt, asm.Width64)
	ctx.assembler.Emit(arm64.LDI(r6, uint64(types.BoxedNull))...)
	ctx.assembler.Emit(arm64.CMP(r4, r6), arm64.CSET(r5, arm64.CondEQ))
	ctx.push(value{
		kind: types.KindI1,
		raw:  true,
		reg:  r5,
	})
	if v0 == 3 && !l.brIf(ctx, r2, l.callerTail(ops, idx+2, tail)) {
		return 0, false
	}
	return v0, true
}

func (l arm64Lowerer) match(ctx *lowering, ops []step, idx int) int {
	if idx+1 >= len(ops) || !l.adjacent(ops[idx], ops[idx+1]) {
		return 0
	}
	r0 := ops[idx]
	r1 := ops[idx+1]
	var v0 int
	switch uint16(r0.op)<<8 | uint16(r1.op) {
	case uint16(instr.GLOBAL_GET)<<8 | uint16(instr.REF_IS_NULL):
		v0 = 2
		if idx+2 < len(ops) && l.adjacent(r1, ops[idx+2]) && ops[idx+2].op == instr.BR_IF && (!ctx.loop || ops[idx+2].target != ctx.tree.root.anchor.ip) {
			v0 = 3
		}
	case uint16(instr.LOCAL_GET)<<8 | uint16(instr.REF_IS_NULL):
		v0 = 2
		if idx+2 < len(ops) && l.adjacent(r1, ops[idx+2]) && ops[idx+2].op == instr.BR_IF && (!ctx.loop || ops[idx+2].target != ctx.tree.root.anchor.ip) {
			v0 = 3
		}
	case uint16(instr.CONST_GET)<<8 | uint16(instr.REF_IS_NULL):
		v0 = 2
		if idx+2 < len(ops) && l.adjacent(r1, ops[idx+2]) && ops[idx+2].op == instr.BR_IF && (!ctx.loop || ops[idx+2].target != ctx.tree.root.anchor.ip) {
			v0 = 3
		}
	case uint16(instr.UPVAL_GET)<<8 | uint16(instr.REF_IS_NULL):
		v0 = 2
		if idx+2 < len(ops) && l.adjacent(r1, ops[idx+2]) && ops[idx+2].op == instr.BR_IF && (!ctx.loop || ops[idx+2].target != ctx.tree.root.anchor.ip) {
			v0 = 3
		}
	case uint16(instr.REF_NULL)<<8 | uint16(instr.REF_IS_NULL):
		v0 = 2
		if idx+2 < len(ops) && l.adjacent(r1, ops[idx+2]) && ops[idx+2].op == instr.BR_IF && (!ctx.loop || ops[idx+2].target != ctx.tree.root.anchor.ip) {
			v0 = 3
		}
	case uint16(instr.DUP)<<8 | uint16(instr.REF_IS_NULL):
		v0 = 2
		if idx+2 < len(ops) && l.adjacent(r1, ops[idx+2]) && ops[idx+2].op == instr.BR_IF && (!ctx.loop || ops[idx+2].target != ctx.tree.root.anchor.ip) {
			v0 = 3
		}
	case uint16(instr.GLOBAL_GET)<<8 | uint16(instr.DROP):
		v0 = 2
	case uint16(instr.LOCAL_GET)<<8 | uint16(instr.DROP):
		v0 = 2
	case uint16(instr.CONST_GET)<<8 | uint16(instr.RETURN_CALL):
		v0 = 2
	case uint16(instr.CONST_GET)<<8 | uint16(instr.CALL):
		v0 = 2
	case uint16(instr.CONST_GET)<<8 | uint16(instr.DROP):
		v0 = 2
	case uint16(instr.UPVAL_GET)<<8 | uint16(instr.DROP):
		v0 = 2
	case uint16(instr.REF_NULL)<<8 | uint16(instr.DROP):
		v0 = 2
	case uint16(instr.DUP)<<8 | uint16(instr.DROP):
		v0 = 2
	}
	return v0
}

func (l arm64Lowerer) adjacent(a, b step) bool {
	if a.fn != b.fn || a.depth != b.depth {
		return false
	}
	width := 1
	for _, operand := range instr.TypeOf(a.op).Widths {
		if operand < 0 {
			return false
		}
		width += operand
	}
	return b.ip == a.ip+width
}
