// Code generated by internal/cmd/genfusion; DO NOT EDIT.
//go:build arm64

package interp

import (
	"testing"

	"github.com/siyul-park/minivm/instr"
	"github.com/stretchr/testify/require"
)

func TestARM64Lowerer_FusionRules(t *testing.T) {
	tests := []struct {
		name string
		ops  []instr.Opcode
	}{
		{name: "global.get/ref.is_null/br_if", ops: []instr.Opcode{instr.GLOBAL_GET, instr.REF_IS_NULL, instr.BR_IF}},
		{name: "local.get/ref.is_null/br_if", ops: []instr.Opcode{instr.LOCAL_GET, instr.REF_IS_NULL, instr.BR_IF}},
		{name: "const.get[not types.String]/ref.is_null/br_if", ops: []instr.Opcode{instr.CONST_GET, instr.REF_IS_NULL, instr.BR_IF}},
		{name: "upval.get/ref.is_null/br_if", ops: []instr.Opcode{instr.UPVAL_GET, instr.REF_IS_NULL, instr.BR_IF}},
		{name: "ref.null/ref.is_null/br_if", ops: []instr.Opcode{instr.REF_NULL, instr.REF_IS_NULL, instr.BR_IF}},
		{name: "dup/ref.is_null/br_if", ops: []instr.Opcode{instr.DUP, instr.REF_IS_NULL, instr.BR_IF}},
		{name: "global.get/drop", ops: []instr.Opcode{instr.GLOBAL_GET, instr.DROP}},
		{name: "global.get/ref.is_null", ops: []instr.Opcode{instr.GLOBAL_GET, instr.REF_IS_NULL}},
		{name: "local.get/drop", ops: []instr.Opcode{instr.LOCAL_GET, instr.DROP}},
		{name: "local.get/ref.is_null", ops: []instr.Opcode{instr.LOCAL_GET, instr.REF_IS_NULL}},
		{name: "const.get/return_call", ops: []instr.Opcode{instr.CONST_GET, instr.RETURN_CALL}},
		{name: "const.get/call", ops: []instr.Opcode{instr.CONST_GET, instr.CALL}},
		{name: "const.get[not types.String]/drop", ops: []instr.Opcode{instr.CONST_GET, instr.DROP}},
		{name: "const.get[not types.String]/ref.is_null", ops: []instr.Opcode{instr.CONST_GET, instr.REF_IS_NULL}},
		{name: "upval.get/drop", ops: []instr.Opcode{instr.UPVAL_GET, instr.DROP}},
		{name: "upval.get/ref.is_null", ops: []instr.Opcode{instr.UPVAL_GET, instr.REF_IS_NULL}},
		{name: "ref.null/drop", ops: []instr.Opcode{instr.REF_NULL, instr.DROP}},
		{name: "ref.null/ref.is_null", ops: []instr.Opcode{instr.REF_NULL, instr.REF_IS_NULL}},
		{name: "dup/drop", ops: []instr.Opcode{instr.DUP, instr.DROP}},
		{name: "dup/ref.is_null", ops: []instr.Opcode{instr.DUP, instr.REF_IS_NULL}},
	}
	width := func(op instr.Opcode) int {
		width := 1
		for _, operand := range instr.TypeOf(op).Widths {
			width += operand
		}
		return width
	}
	l := arm64Lowerer{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ops := make([]step, len(tt.ops))
			ip := 0
			for i, op := range tt.ops {
				ops[i] = step{op: op, ip: ip}
				ip += width(op)
			}
			ctx := &lowering{tree: &tree{root: &trace{anchor: anchor{ip: -1}}}}
			require.Equal(t, len(tt.ops), l.match(ctx, ops, 0))
		})
	}
}

func TestARM64Lowerer_FusionRejectsUndeclaredPair(t *testing.T) {
	ops := []step{{op: instr.I32_CONST, ip: 0}, {op: instr.DROP, ip: 5}}
	ctx := &lowering{tree: &tree{root: &trace{anchor: anchor{ip: -1}}}}
	require.Zero(t, (arm64Lowerer{}).match(ctx, ops, 0))
}
