package arm64

import "github.com/siyul-park/minivm/asm"

var (
	X0  = asm.NewPReg(0, asm.RegTypeInt, asm.Width64)
	X1  = asm.NewPReg(1, asm.RegTypeInt, asm.Width64)
	X2  = asm.NewPReg(2, asm.RegTypeInt, asm.Width64)
	X3  = asm.NewPReg(3, asm.RegTypeInt, asm.Width64)
	X4  = asm.NewPReg(4, asm.RegTypeInt, asm.Width64)
	X5  = asm.NewPReg(5, asm.RegTypeInt, asm.Width64)
	X6  = asm.NewPReg(6, asm.RegTypeInt, asm.Width64)
	X7  = asm.NewPReg(7, asm.RegTypeInt, asm.Width64)
	X8  = asm.NewPReg(8, asm.RegTypeInt, asm.Width64)
	X9  = asm.NewPReg(9, asm.RegTypeInt, asm.Width64)
	X10 = asm.NewPReg(10, asm.RegTypeInt, asm.Width64)
	X11 = asm.NewPReg(11, asm.RegTypeInt, asm.Width64)
	X12 = asm.NewPReg(12, asm.RegTypeInt, asm.Width64)
	X13 = asm.NewPReg(13, asm.RegTypeInt, asm.Width64)
	X14 = asm.NewPReg(14, asm.RegTypeInt, asm.Width64)
	X15 = asm.NewPReg(15, asm.RegTypeInt, asm.Width64)
	X16 = asm.NewPReg(16, asm.RegTypeInt, asm.Width64)
	X17 = asm.NewPReg(17, asm.RegTypeInt, asm.Width64)
	X18 = asm.NewPReg(18, asm.RegTypeInt, asm.Width64)
	X19 = asm.NewPReg(19, asm.RegTypeInt, asm.Width64)
	X20 = asm.NewPReg(20, asm.RegTypeInt, asm.Width64)
	X21 = asm.NewPReg(21, asm.RegTypeInt, asm.Width64)
	X22 = asm.NewPReg(22, asm.RegTypeInt, asm.Width64)
	X23 = asm.NewPReg(23, asm.RegTypeInt, asm.Width64)
	X24 = asm.NewPReg(24, asm.RegTypeInt, asm.Width64)
	X25 = asm.NewPReg(25, asm.RegTypeInt, asm.Width64)
	X26 = asm.NewPReg(26, asm.RegTypeInt, asm.Width64)
	X27 = asm.NewPReg(27, asm.RegTypeInt, asm.Width64)
	X28 = asm.NewPReg(28, asm.RegTypeInt, asm.Width64)
	X29 = asm.NewPReg(29, asm.RegTypeInt, asm.Width64) // FP (Frame Pointer)
	X30 = asm.NewPReg(30, asm.RegTypeInt, asm.Width64) // LR (Link Register)

	FP  = X29
	LR  = X30
	XZR = asm.NewPReg(31, asm.RegTypeInt, asm.Width64)
	// SP shares register id 31 with XZR. In data-processing instructions
	// field 31 reads as the zero register; in add/subtract-immediate and
	// load/store forms it encodes the stack pointer. Use SP where the stack
	// pointer is meant so call sites do not appear to clobber XZR.
	SP = asm.NewPReg(31, asm.RegTypeInt, asm.Width64)

	W0  = asm.NewPReg(0, asm.RegTypeInt, asm.Width32)
	W1  = asm.NewPReg(1, asm.RegTypeInt, asm.Width32)
	W2  = asm.NewPReg(2, asm.RegTypeInt, asm.Width32)
	W3  = asm.NewPReg(3, asm.RegTypeInt, asm.Width32)
	W4  = asm.NewPReg(4, asm.RegTypeInt, asm.Width32)
	W5  = asm.NewPReg(5, asm.RegTypeInt, asm.Width32)
	W6  = asm.NewPReg(6, asm.RegTypeInt, asm.Width32)
	W7  = asm.NewPReg(7, asm.RegTypeInt, asm.Width32)
	W8  = asm.NewPReg(8, asm.RegTypeInt, asm.Width32)
	W9  = asm.NewPReg(9, asm.RegTypeInt, asm.Width32)
	W10 = asm.NewPReg(10, asm.RegTypeInt, asm.Width32)
	W11 = asm.NewPReg(11, asm.RegTypeInt, asm.Width32)
	W12 = asm.NewPReg(12, asm.RegTypeInt, asm.Width32)
	W13 = asm.NewPReg(13, asm.RegTypeInt, asm.Width32)
	W14 = asm.NewPReg(14, asm.RegTypeInt, asm.Width32)
	W15 = asm.NewPReg(15, asm.RegTypeInt, asm.Width32)
	W16 = asm.NewPReg(16, asm.RegTypeInt, asm.Width32)
	W17 = asm.NewPReg(17, asm.RegTypeInt, asm.Width32)
	W18 = asm.NewPReg(18, asm.RegTypeInt, asm.Width32)
	W19 = asm.NewPReg(19, asm.RegTypeInt, asm.Width32)
	W20 = asm.NewPReg(20, asm.RegTypeInt, asm.Width32)
	W21 = asm.NewPReg(21, asm.RegTypeInt, asm.Width32)
	W22 = asm.NewPReg(22, asm.RegTypeInt, asm.Width32)
	W23 = asm.NewPReg(23, asm.RegTypeInt, asm.Width32)
	W24 = asm.NewPReg(24, asm.RegTypeInt, asm.Width32)
	W25 = asm.NewPReg(25, asm.RegTypeInt, asm.Width32)
	W26 = asm.NewPReg(26, asm.RegTypeInt, asm.Width32)
	W27 = asm.NewPReg(27, asm.RegTypeInt, asm.Width32)
	W28 = asm.NewPReg(28, asm.RegTypeInt, asm.Width32)
	W29 = asm.NewPReg(29, asm.RegTypeInt, asm.Width32)
	W30 = asm.NewPReg(30, asm.RegTypeInt, asm.Width32)
	WZR = asm.NewPReg(31, asm.RegTypeInt, asm.Width32)

	D0  = asm.NewPReg(0, asm.RegTypeFloat, asm.Width64)
	D1  = asm.NewPReg(1, asm.RegTypeFloat, asm.Width64)
	D2  = asm.NewPReg(2, asm.RegTypeFloat, asm.Width64)
	D3  = asm.NewPReg(3, asm.RegTypeFloat, asm.Width64)
	D4  = asm.NewPReg(4, asm.RegTypeFloat, asm.Width64)
	D5  = asm.NewPReg(5, asm.RegTypeFloat, asm.Width64)
	D6  = asm.NewPReg(6, asm.RegTypeFloat, asm.Width64)
	D7  = asm.NewPReg(7, asm.RegTypeFloat, asm.Width64)
	D8  = asm.NewPReg(8, asm.RegTypeFloat, asm.Width64)
	D9  = asm.NewPReg(9, asm.RegTypeFloat, asm.Width64)
	D10 = asm.NewPReg(10, asm.RegTypeFloat, asm.Width64)
	D11 = asm.NewPReg(11, asm.RegTypeFloat, asm.Width64)
	D12 = asm.NewPReg(12, asm.RegTypeFloat, asm.Width64)
	D13 = asm.NewPReg(13, asm.RegTypeFloat, asm.Width64)
	D14 = asm.NewPReg(14, asm.RegTypeFloat, asm.Width64)
	D15 = asm.NewPReg(15, asm.RegTypeFloat, asm.Width64)
	D16 = asm.NewPReg(16, asm.RegTypeFloat, asm.Width64)
	D17 = asm.NewPReg(17, asm.RegTypeFloat, asm.Width64)
	D18 = asm.NewPReg(18, asm.RegTypeFloat, asm.Width64)
	D19 = asm.NewPReg(19, asm.RegTypeFloat, asm.Width64)
	D20 = asm.NewPReg(20, asm.RegTypeFloat, asm.Width64)
	D21 = asm.NewPReg(21, asm.RegTypeFloat, asm.Width64)
	D22 = asm.NewPReg(22, asm.RegTypeFloat, asm.Width64)
	D23 = asm.NewPReg(23, asm.RegTypeFloat, asm.Width64)
	D24 = asm.NewPReg(24, asm.RegTypeFloat, asm.Width64)
	D25 = asm.NewPReg(25, asm.RegTypeFloat, asm.Width64)
	D26 = asm.NewPReg(26, asm.RegTypeFloat, asm.Width64)
	D27 = asm.NewPReg(27, asm.RegTypeFloat, asm.Width64)
	D28 = asm.NewPReg(28, asm.RegTypeFloat, asm.Width64)
	D29 = asm.NewPReg(29, asm.RegTypeFloat, asm.Width64)
	D30 = asm.NewPReg(30, asm.RegTypeFloat, asm.Width64)
	D31 = asm.NewPReg(31, asm.RegTypeFloat, asm.Width64)

	S0  = asm.NewPReg(0, asm.RegTypeFloat, asm.Width32)
	S1  = asm.NewPReg(1, asm.RegTypeFloat, asm.Width32)
	S2  = asm.NewPReg(2, asm.RegTypeFloat, asm.Width32)
	S3  = asm.NewPReg(3, asm.RegTypeFloat, asm.Width32)
	S4  = asm.NewPReg(4, asm.RegTypeFloat, asm.Width32)
	S5  = asm.NewPReg(5, asm.RegTypeFloat, asm.Width32)
	S6  = asm.NewPReg(6, asm.RegTypeFloat, asm.Width32)
	S7  = asm.NewPReg(7, asm.RegTypeFloat, asm.Width32)
	S8  = asm.NewPReg(8, asm.RegTypeFloat, asm.Width32)
	S9  = asm.NewPReg(9, asm.RegTypeFloat, asm.Width32)
	S10 = asm.NewPReg(10, asm.RegTypeFloat, asm.Width32)
	S11 = asm.NewPReg(11, asm.RegTypeFloat, asm.Width32)
	S12 = asm.NewPReg(12, asm.RegTypeFloat, asm.Width32)
	S13 = asm.NewPReg(13, asm.RegTypeFloat, asm.Width32)
	S14 = asm.NewPReg(14, asm.RegTypeFloat, asm.Width32)
	S15 = asm.NewPReg(15, asm.RegTypeFloat, asm.Width32)
	S16 = asm.NewPReg(16, asm.RegTypeFloat, asm.Width32)
	S17 = asm.NewPReg(17, asm.RegTypeFloat, asm.Width32)
	S18 = asm.NewPReg(18, asm.RegTypeFloat, asm.Width32)
	S19 = asm.NewPReg(19, asm.RegTypeFloat, asm.Width32)
	S20 = asm.NewPReg(20, asm.RegTypeFloat, asm.Width32)
	S21 = asm.NewPReg(21, asm.RegTypeFloat, asm.Width32)
	S22 = asm.NewPReg(22, asm.RegTypeFloat, asm.Width32)
	S23 = asm.NewPReg(23, asm.RegTypeFloat, asm.Width32)
	S24 = asm.NewPReg(24, asm.RegTypeFloat, asm.Width32)
	S25 = asm.NewPReg(25, asm.RegTypeFloat, asm.Width32)
	S26 = asm.NewPReg(26, asm.RegTypeFloat, asm.Width32)
	S27 = asm.NewPReg(27, asm.RegTypeFloat, asm.Width32)
	S28 = asm.NewPReg(28, asm.RegTypeFloat, asm.Width32)
	S29 = asm.NewPReg(29, asm.RegTypeFloat, asm.Width32)
	S30 = asm.NewPReg(30, asm.RegTypeFloat, asm.Width32)
	S31 = asm.NewPReg(31, asm.RegTypeFloat, asm.Width32)

	IntRets = []asm.PReg{X0, X1}
)
