package prof

// Frontend identifies the compiler frontend that produced native code.
type Frontend uint8

// Trigger identifies why compilation started.
type Trigger uint8

// EntryKind identifies a native entry point's role.
type EntryKind uint8

// CaptureOutcome identifies the result of a trace capture attempt.
type CaptureOutcome uint8

// CaptureReason identifies why trace capture did not complete normally.
type CaptureReason uint8

// CompileOutcome identifies the result of a compile attempt.
type CompileOutcome uint8

// CompileReason identifies why compilation did not emit native code.
type CompileReason uint8

// ExitReason identifies why native execution returned to the interpreter.
type ExitReason uint8

// Counter is a pre-resolved runtime metric handle.
type Counter struct {
	value uint64
}

const (
	FrontendNone Frontend = iota
	FrontendStatic
	FrontendTrace
)

const (
	TriggerNone Trigger = iota
	TriggerHot
	TriggerSideExit
)

const (
	EntryNone EntryKind = iota
	EntryStart
	EntryCall
	EntryLoop
)

const (
	CaptureOutcomeNone CaptureOutcome = iota
	CaptureOutcomePublished
	CaptureOutcomePartial
	CaptureOutcomeRejected
)

const (
	CaptureReasonNone CaptureReason = iota
	CaptureReasonAttemptLimit
	CaptureReasonInvalidAnchor
	CaptureReasonHostCall
	CaptureReasonTailClosure
	CaptureReasonUnsupportedOp
	CaptureReasonNestedTerminal
	CaptureReasonStepTrap
	CaptureReasonOpLimit
)

const (
	CompileOutcomeNone CompileOutcome = iota
	CompileOutcomeEmitted
	CompileOutcomeEmpty
	CompileOutcomeRejected
	CompileOutcomeError
)

const (
	CompileReasonNone CompileReason = iota
	CompileReasonNoInput
	CompileReasonNoPlan
	CompileReasonInvalidPlan
	CompileReasonLoweringRejected
	CompileReasonRegisterPressure
	CompileReasonBranchRange
	CompileReasonBackendUnavailable
	CompileReasonError
)

const (
	ExitNone ExitReason = iota
	ExitGuardKind
	ExitGuardShape
	ExitGuardBounds
	ExitGuardValue
	ExitColdBranch
	ExitTraceCut
	ExitTerminalOp
	ExitLoop
)

// OpcodeNone marks an exit that cannot be attributed to an opcode.
const OpcodeNone = -1

// RecordCapture records one cold-path trace capture result.
func (c *Collector) RecordCapture(fn, ip int, outcome CaptureOutcome, reason CaptureReason) {
	key := captureKey{fn: fn, ip: ip, outcome: outcome, reason: reason}
	counterFor(&c.jit.captures, key).value++
}

// RecordCompile records one cold-path compile result.
func (c *Collector) RecordCompile(
	fn, ip int,
	trigger Trigger,
	frontend Frontend,
	outcome CompileOutcome,
	reason CompileReason,
) {
	key := compileKey{
		fn: fn, ip: ip,
		trigger: trigger, frontend: frontend,
		outcome: outcome, reason: reason,
	}
	counterFor(&c.jit.compiles, key).value++
}

// RecordEmit records one emitted native entry and its generated byte count.
func (c *Collector) RecordEmit(fn, ip int, kind EntryKind, frontend Frontend, size int) {
	key := entryKey{fn: fn, ip: ip, kind: kind, frontend: frontend}
	if c.jit.emits == nil {
		c.jit.emits = make(map[entryKey]*emitCounters)
	}
	counters := c.jit.emits[key]
	if counters == nil {
		counters = &emitCounters{}
		c.jit.emits[key] = counters
	}
	counters.emits.value++
	if size > 0 {
		counters.bytes.value += uint64(size)
	}
}

// RegisterEntry returns the stable counter for one native entry row.
func (c *Collector) RegisterEntry(fn, ip int, kind EntryKind, frontend Frontend) *Counter {
	key := entryKey{fn: fn, ip: ip, kind: kind, frontend: frontend}
	return counterFor(&c.jit.entries, key)
}

// RegisterExit returns the stable counter for one native exit row.
func (c *Collector) RegisterExit(
	fn, ip int,
	kind EntryKind,
	frontend Frontend,
	reason ExitReason,
	opcode int,
) *Counter {
	if opcode < 0 || opcode > 255 {
		opcode = OpcodeNone
	}
	key := exitKey{
		entryKey: entryKey{fn: fn, ip: ip, kind: kind, frontend: frontend},
		reason:   reason,
		opcode:   opcode,
	}
	return counterFor(&c.jit.exits, key)
}

// RegisterYield returns the stable counter for one native yield row.
func (c *Collector) RegisterYield(fn, ip int, kind EntryKind, frontend Frontend) *Counter {
	key := entryKey{fn: fn, ip: ip, kind: kind, frontend: frontend}
	return counterFor(&c.jit.yields, key)
}

// Inc increments a pre-resolved counter without allocating.
func (c *Counter) Inc() {
	c.value++
}
