package main

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/siyul-park/minivm/instr"
)

type output struct {
	path string
	data []byte
}

type renderedNumericSource struct {
	pre   []jen.Code
	load  []jen.Code
	width int
}

func generate() ([]output, error) {
	rules, err := expandAll(declarations())
	if err != nil {
		return nil, err
	}
	if err := validate(rules); err != nil {
		return nil, err
	}
	data, err := renderThreaded(rules)
	if err != nil {
		return nil, err
	}
	test, err := renderThreadedTest(rules)
	if err != nil {
		return nil, err
	}
	arm64, err := renderARM64(rules)
	if err != nil {
		return nil, err
	}
	arm64Test, err := renderARM64Test(rules)
	if err != nil {
		return nil, err
	}
	outputs := []output{
		{path: "interp/fusion_gen.go", data: data},
		{path: "interp/fusion_gen_test.go", data: test},
		{path: "interp/jit_fusion_gen_arm64.go", data: arm64},
		{path: "interp/jit_fusion_gen_arm64_test.go", data: arm64Test},
	}
	return outputs, nil
}

func supportsARM64(pattern []operation) bool {
	if len(pattern) < 2 || len(pattern) > 3 {
		return false
	}
	source := pattern[0].op
	consumer := pattern[1].op
	if consumer == instr.CALL || consumer == instr.RETURN_CALL {
		return len(pattern) == 2 && source == instr.CONST_GET && pattern[1].op == consumer
	}
	if (consumer != instr.DROP && consumer != instr.REF_IS_NULL) || pattern[1].op != consumer {
		return false
	}
	if len(pattern) == 3 && (consumer != instr.REF_IS_NULL || pattern[2].op != instr.BR_IF) {
		return false
	}
	switch source {
	case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.REF_NULL, instr.DUP:
		return true
	default:
		return false
	}
}

func renderThreadedTest(rules []rule) ([]byte, error) {
	var cases strings.Builder
	for _, rule := range rules {
		kind, err := testRuleKind(rule)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&cases, "\t{name: %q, ops: []instr.Opcode{%s}, kind: types.%s},\n", testRuleName(rule), testOpcodes(rule.pattern), kind)
	}
	return format.Source([]byte(fmt.Sprintf(`// Code generated by internal/cmd/genfusion; DO NOT EDIT.

package interp

import (
	"testing"

	"github.com/siyul-park/minivm/instr"
	"github.com/siyul-park/minivm/program"
	"github.com/siyul-park/minivm/types"
	"github.com/stretchr/testify/require"
)

func TestThreader_FusionRules(t *testing.T) {
	tests := []struct {
		name string
		ops  []instr.Opcode
		kind types.Kind
	}{
%s	}
	instruction := func(op instr.Opcode) instr.Instruction {
		switch op {
		case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.BR_IF:
			return instr.New(op, 0)
		case instr.I32_CONST, instr.I64_CONST, instr.F32_CONST, instr.F64_CONST:
			return instr.New(op, 2)
		default:
			return instr.New(op)
		}
	}
	constant := func(kind types.Kind) ([]types.Boxed, []types.Value, []bool) {
		switch kind {
		case types.KindI32:
			return []types.Boxed{types.BoxI32(2)}, nil, nil
		case types.KindI64:
			return []types.Boxed{types.BoxI64(2)}, nil, nil
		case types.KindF32:
			return []types.Boxed{types.BoxF32(2)}, nil, nil
		case types.KindF64:
			return []types.Boxed{types.BoxF64(2)}, nil, nil
		default:
			fn := types.NewFunctionBuilder(&types.FunctionType{}).MustBuild()
			return []types.Boxed{types.BoxRef(0)}, []types.Value{fn}, []bool{false}
		}
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			code := make([]instr.Instruction, len(tt.ops))
			for i, op := range tt.ops {
				code[i] = instruction(op)
			}
			prog := program.New(code)
			c := threader{code: prog.Code}
			for _, op := range tt.ops {
				switch op {
				case instr.LOCAL_GET:
					c.locals = []types.Kind{tt.kind}
				case instr.GLOBAL_GET:
					c.globals = []types.Kind{tt.kind}
				case instr.UPVAL_GET:
					c.captures = []types.Kind{tt.kind}
				case instr.CONST_GET:
					c.constants, c.heap, c.coros = constant(tt.kind)
				}
			}
			require.NotNil(t, c.fusion())
		})
	}
}
`, cases.String())))
}

func testRuleKind(rule rule) (string, error) {
	for i := len(rule.pattern) - 1; i >= 0; i-- {
		switch rule.pattern[i].op {
		case instr.ARRAY_GET, instr.STRUCT_GET:
			return "KindI32", nil
		}
		if kind, ok := numericKind(rule.pattern[i].op); ok {
			return "Kind" + kind, nil
		}
	}
	for _, operation := range rule.pattern {
		switch operation.op {
		case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.REF_NULL, instr.DUP, instr.CALL, instr.RETURN_CALL, instr.CLOSURE_NEW:
			return "KindRef", nil
		}
	}
	return "", fmt.Errorf("no test kind for %s", patternKey(rule.pattern))
}

func testRuleName(rule rule) string {
	parts := make([]string, len(rule.pattern))
	for i, operation := range rule.pattern {
		parts[i] = instr.TypeOf(operation.op).Mnemonic
		if operation.guard != nil {
			if operation.guard.negations == 1 {
				parts[i] += "[not " + operation.guard.typeOf.String() + "]"
			} else {
				parts[i] += "[" + operation.guard.typeOf.String() + "]"
			}
		}
	}
	return strings.Join(parts, "/")
}

func testOpcodes(pattern []operation) string {
	parts := make([]string, len(pattern))
	for i, operation := range pattern {
		parts[i] = "instr." + opcodeName(operation.op)
	}
	return strings.Join(parts, ", ")
}

func renderThreaded(rules []rule) ([]byte, error) {
	file := jen.NewFile("interp")
	file.HeaderComment("Code generated by internal/cmd/genfusion; DO NOT EDIT.")

	var groups [256][]rule
	for _, rule := range rules {
		groups[rule.pattern[0].op] = append(groups[rule.pattern[0].op], rule)
	}

	var cases []jen.Code
	nextLabel := 0
	for opcode, rules := range groups {
		if len(rules) == 0 {
			continue
		}
		var body []jen.Code
		for _, rule := range rules {
			label := fmt.Sprintf("l%d", nextLabel)
			nextLabel++
			total := patternWidth(rule.pattern)
			statements, err := renderThreadedRule(rule, total, label)
			if err != nil {
				return nil, err
			}
			if rule.pattern[len(rule.pattern)-1].op == instr.BR_IF {
				offset := total - opcodeWidth(instr.BR_IF) + 1
				statements = append([]jen.Code{jen.Id("offset").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseI16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(offset))}, statements...)
			}
			body = append(body, jen.If(jen.Op("!").Parens(renderPattern(rule.pattern))).Block(jen.Goto().Id(label)))
			body = append(body, jen.Block(statements...))
			body = append(body, jen.Id(label).Op(":"))
		}
		body = append(body, jen.Break())
		cases = append(cases, jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", opcodeName(instr.Opcode(opcode)))).Block(body...))
	}

	body := []jen.Code{
		jen.Id("start").Op(":=").Id("c").Dot("ip"),
		jen.If(jen.Id("start").Op(">=").Len(jen.Id("c").Dot("code"))).Block(jen.Return(jen.Nil())),
		jen.Switch(jen.Qual("github.com/siyul-park/minivm/instr", "Opcode").Call(jen.Id("c").Dot("code").Index(jen.Id("start")))).Block(cases...),
		jen.Return(jen.Nil()),
	}
	file.Func().Params(jen.Id("c").Op("*").Id("threader")).Id("fusion").Params().Func().Params(jen.Op("*").Id("Interpreter")).Block(body...)
	return formatGenerated([]byte(file.GoString()))
}

func reject(label string) jen.Code {
	if label != "" {
		return jen.Goto().Id(label)
	}
	return jen.Return(jen.Nil())
}

func renderThreadedRule(rule rule, total int, label string) ([]jen.Code, error) {
	last := rule.pattern[len(rule.pattern)-1].op
	consumer := last
	if last == instr.BR_IF && len(rule.pattern) > 1 {
		consumer = rule.pattern[len(rule.pattern)-2].op
	}
	if consumer == instr.CALL || consumer == instr.RETURN_CALL || consumer == instr.CLOSURE_NEW {
		return renderCall(rule, label)
	}
	if consumer == instr.DROP || consumer == instr.REF_IS_NULL {
		return renderRefFusion(rule, total, label)
	}
	if consumer == instr.ARRAY_GET || consumer == instr.STRUCT_GET {
		return renderThreadedIndex(rule, total, label)
	}
	if len(rule.pattern) == 2 && rule.pattern[0].op == instr.I32_CONST && last == instr.BR_IF {
		return renderI32ConstBranch(total), nil
	}
	if _, _, ok := numericConsumer(consumer); ok {
		return renderNumericFusion(rule, total, label)
	}
	return nil, fmt.Errorf("no threaded renderer for %s", instr.TypeOf(consumer).Mnemonic)
}

func renderI32ConstBranch(total int) []jen.Code {
	return []jen.Code{
		jen.Id("value").Op(":=").Add(numericImmediate("I32", jen.Id("start"))),
		jen.Id("c").Dot("ip").Op("+=").Lit(opcodeWidth(instr.I32_CONST)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("i").Dot("branchIf").Call(jen.Id("value").Op("!=").Lit(0), jen.Id("offset"), jen.Lit(total)),
		)),
	}
}

func renderPattern(pattern []operation) jen.Code {
	total := patternWidth(pattern)
	condition := jen.Id("start").Op("+").Lit(total).Op("<=").Len(jen.Id("c").Dot("code"))
	offset := opcodeWidth(pattern[0].op)
	for _, operation := range pattern[1:] {
		condition = condition.Op("&&").Qual("github.com/siyul-park/minivm/instr", "Opcode").Call(jen.Id("c").Dot("code").Index(add(jen.Id("start"), offset))).Op("==").Qual("github.com/siyul-park/minivm/instr", opcodeName(operation.op))
		offset += opcodeWidth(operation.op)
	}
	return condition
}

func opcodeName(op instr.Opcode) string {
	return strings.ToUpper(strings.ReplaceAll(instr.TypeOf(op).Mnemonic, ".", "_"))
}

func patternWidth(pattern []operation) int {
	total := 0
	for _, operation := range pattern {
		total += opcodeWidth(operation.op)
	}
	return total
}

// renderARM64 renders the ARM64-marked concrete rules. The emitted matcher
// selects a declared specialization before any lowering state is mutated.
func renderARM64(rules []rule) ([]byte, error) {
	arm64 := make([]rule, 0, len(rules))
	for _, rule := range rules {
		if rule.arm64 {
			arm64 = append(arm64, rule)
		}
	}

	file := jen.NewFile("interp")
	file.HeaderComment("Code generated by internal/cmd/genfusion; DO NOT EDIT.")
	file.Func().Params(jen.Id("l").Id("arm64Lowerer")).Id("fusion").Params(
		jen.Id("ctx").Op("*").Id("lowering"),
		jen.Id("ops"), jen.Id("tail").Index().Id("step"),
		jen.Id("idx").Int(),
	).Params(jen.Int(), jen.Bool()).Block(arm64FusionBody()...)
	file.Line()
	file.Func().Params(jen.Id("l").Id("arm64Lowerer")).Id("match").Params(
		jen.Id("ctx").Op("*").Id("lowering"),
		jen.Id("ops").Index().Id("step"),
		jen.Id("idx").Int(),
	).Int().Block(arm64MatchBody(arm64)...)
	file.Line()
	file.Func().Params(jen.Id("l").Id("arm64Lowerer")).Id("adjacent").Params(jen.Id("a"), jen.Id("b").Id("step")).Bool().Block(
		jen.If(jen.Id("a").Dot("fn").Op("!=").Id("b").Dot("fn").Op("||").Id("a").Dot("depth").Op("!=").Id("b").Dot("depth")).Block(jen.Return(jen.False())),
		jen.Id("width").Op(":=").Lit(1),
		jen.For(jen.List(jen.Id("_"), jen.Id("operand")).Op(":=").Range().Qual("github.com/siyul-park/minivm/instr", "TypeOf").Call(jen.Id("a").Dot("op")).Dot("Widths")).Block(
			jen.If(jen.Id("operand").Op("<").Lit(0)).Block(jen.Return(jen.False())),
			jen.Id("width").Op("+=").Id("operand"),
		),
		jen.Return(jen.Id("b").Dot("ip").Op("==").Id("a").Dot("ip").Op("+").Id("width")),
	)
	return formatARM64(file)
}

func arm64FusionBody() []jen.Code {
	return []jen.Code{
		jen.Id("v0").Op(":=").Id("l").Dot("match").Call(jen.Id("ctx"), jen.Id("ops"), jen.Id("idx")),
		jen.If(jen.Id("v0").Op("==").Lit(0)).Block(jen.Return(jen.Lit(0), jen.True())),
		jen.Id("r0").Op(":=").Id("ops").Index(jen.Id("idx")),
		jen.Id("r1").Op(":=").Id("ops").Index(jen.Id("idx").Op("+").Lit(1)),
		jen.If(jen.Id("r0").Dot("op").Op("==").Qual("github.com/siyul-park/minivm/instr", "CONST_GET").Op("&&").Parens(
			jen.Id("r1").Dot("op").Op("==").Qual("github.com/siyul-park/minivm/instr", "CALL").Op("||").Id("r1").Dot("op").Op("==").Qual("github.com/siyul-park/minivm/instr", "RETURN_CALL"),
		)).Block(arm64ConstantCall()...),
		jen.Id("r2").Op(":=").Id("step").Values(),
		jen.If(jen.Id("v0").Op("==").Lit(3)).Block(jen.Id("r2").Op("=").Id("ops").Index(jen.Id("idx").Op("+").Lit(2))),
		jen.Id("f").Op(":=").Id("ctx").Dot("frame").Call(),
		jen.Var().Defs(
			jen.Id("i0").Int(), jen.Id("i1").Int(), jen.Id("i2").Int(), jen.Id("i3").Int(), jen.Id("i4").Int(),
			jen.Id("r3").Qual("github.com/siyul-park/minivm/types", "Boxed"),
		),
		jen.Switch(jen.Id("r0").Dot("op")).Block(arm64RefPreflightCases()...),
		jen.Id("r4").Op(":=").Qual("github.com/siyul-park/minivm/asm", "VReg").Values(),
		jen.Switch(jen.Id("r0").Dot("op")).Block(arm64RefCases()...),
		jen.Id("r5").Op(":=").Id("ctx").Dot("assembler").Dot("Reg").Call(jen.Qual("github.com/siyul-park/minivm/asm", "RegTypeInt"), jen.Qual("github.com/siyul-park/minivm/asm", "Width64")),
		jen.Id("r6").Op(":=").Id("ctx").Dot("assembler").Dot("Reg").Call(jen.Qual("github.com/siyul-park/minivm/asm", "RegTypeInt"), jen.Qual("github.com/siyul-park/minivm/asm", "Width64")),
		jen.Id("ctx").Dot("assembler").Dot("Emit").Call(jen.Qual("github.com/siyul-park/minivm/asm/arm64", "LDI").Call(jen.Id("r6"), jen.Uint64().Parens(jen.Qual("github.com/siyul-park/minivm/types", "BoxedNull"))).Op("...")),
		jen.Id("ctx").Dot("assembler").Dot("Emit").Call(jen.Qual("github.com/siyul-park/minivm/asm/arm64", "CMP").Call(jen.Id("r4"), jen.Id("r6")), jen.Qual("github.com/siyul-park/minivm/asm/arm64", "CSET").Call(jen.Id("r5"), jen.Qual("github.com/siyul-park/minivm/asm/arm64", "CondEQ"))),
		jen.Id("ctx").Dot("push").Call(jen.Id("value").Values(jen.Dict{jen.Id("reg"): jen.Id("r5"), jen.Id("kind"): jen.Qual("github.com/siyul-park/minivm/types", "KindI1"), jen.Id("raw"): jen.True()})),
		jen.If(jen.Id("v0").Op("==").Lit(3).Op("&&").Op("!").Id("l").Dot("brIf").Call(jen.Id("ctx"), jen.Id("r2"), jen.Id("l").Dot("callerTail").Call(jen.Id("ops"), jen.Id("idx").Op("+").Lit(2), jen.Id("tail")))).Block(jen.Return(jen.Lit(0), jen.False())),
		jen.Return(jen.Id("v0"), jen.True()),
	}
}

func arm64MatchBody(rules []rule) []jen.Code {
	return []jen.Code{
		jen.If(jen.Id("idx").Op("+").Lit(1).Op(">=").Len(jen.Id("ops")).Op("||").Op("!").Id("l").Dot("adjacent").Call(jen.Id("ops").Index(jen.Id("idx")), jen.Id("ops").Index(jen.Id("idx").Op("+").Lit(1)))).Block(jen.Return(jen.Lit(0))),
		jen.Id("r0").Op(":=").Id("ops").Index(jen.Id("idx")),
		jen.Id("r1").Op(":=").Id("ops").Index(jen.Id("idx").Op("+").Lit(1)),
		jen.Var().Id("v0").Int(),
		jen.Switch(jen.Uint16().Parens(jen.Id("r0").Dot("op")).Op("<<").Lit(8).Op("|").Uint16().Parens(jen.Id("r1").Dot("op"))).Block(arm64Cases(rules)...),
		jen.Return(jen.Id("v0")),
	}
}

func arm64Cases(rules []rule) []jen.Code {
	type pairRule struct {
		base      bool
		extension instr.Opcode
		extended  bool
	}

	var pairs [][2]instr.Opcode
	matched := make(map[[2]instr.Opcode]pairRule)
	for _, rule := range rules {
		pair := [2]instr.Opcode{rule.pattern[0].op, rule.pattern[1].op}
		match, ok := matched[pair]
		if !ok {
			pairs = append(pairs, pair)
		}
		if len(rule.pattern) == 2 {
			match.base = true
		} else {
			match.extension = rule.pattern[2].op
			match.extended = true
		}
		matched[pair] = match
	}

	cases := make([]jen.Code, 0, len(pairs))
	for _, pair := range pairs {
		match := matched[pair]
		var body []jen.Code
		if match.base {
			body = append(body, jen.Id("v0").Op("=").Lit(2))
		}
		if match.extended {
			next := jen.Id("ops").Index(jen.Id("idx").Op("+").Lit(2))
			body = append(body, jen.If(
				jen.Id("idx").Op("+").Lit(2).Op("<").Len(jen.Id("ops")).Op("&&").
					Id("l").Dot("adjacent").Call(jen.Id("r1"), next).Op("&&").
					Add(next).Dot("op").Op("==").Qual("github.com/siyul-park/minivm/instr", opcodeName(match.extension)).Op("&&").
					Parens(jen.Op("!").Id("ctx").Dot("loop").Op("||").Add(next).Dot("target").Op("!=").Id("ctx").Dot("tree").Dot("root").Dot("anchor").Dot("ip")),
			).Block(jen.Id("v0").Op("=").Lit(3)))
		}
		key := jen.Uint16().Parens(jen.Qual("github.com/siyul-park/minivm/instr", opcodeName(pair[0]))).Op("<<").Lit(8).Op("|").Uint16().Parens(jen.Qual("github.com/siyul-park/minivm/instr", opcodeName(pair[1])))
		cases = append(cases, jen.Case(key).Block(body...))
	}
	return cases
}

// arm64RefPreflightCases emits only reads and local scalar assignments. It is
// the selection boundary: no register, IR, symbolic stack, fact, label, exit,
// or journal state may be changed before this switch accepts a candidate.
func arm64RefPreflightCases() []jen.Code {
	return []jen.Code{
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "LOCAL_GET")).Block(
			jen.Id("i0").Op("=").Int().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(1))),
			jen.If(jen.Id("i0").Op(">=").Len(jen.Id("f").Dot("kinds")).Op("||").Id("f").Dot("kinds").Index(jen.Id("i0")).Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(jen.Return(jen.Lit(0), jen.True())),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "GLOBAL_GET")).Block(
			jen.Id("i1").Op("=").Int().Parens(jen.Uint16().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(1))).Op("|").Uint16().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(2))).Op("<<").Lit(8)),
			jen.If(jen.Id("i1").Op(">=").Len(jen.Id("ctx").Dot("globals")).Op("||").Id("i1").Op(">").Lit(4095).Op("||").Id("ctx").Dot("globals").Index(jen.Id("i1")).Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(jen.Return(jen.Lit(0), jen.True())),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "UPVAL_GET")).Block(
			jen.Id("i2").Op("=").Int().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(1))),
			jen.If(jen.Id("i2").Op(">=").Len(jen.Id("f").Dot("upvals")).Op("||").Id("f").Dot("upvals").Index(jen.Id("i2")).Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(jen.Return(jen.Lit(0), jen.True())),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "CONST_GET")).Block(
			jen.Id("i3").Op("=").Int().Parens(jen.Uint16().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(1))).Op("|").Uint16().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(2))).Op("<<").Lit(8)),
			jen.If(jen.Id("i3").Op(">=").Len(jen.Id("ctx").Dot("constants")).Op("||").Id("ctx").Dot("constants").Index(jen.Id("i3")).Dot("Kind").Call().Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(jen.Return(jen.Lit(0), jen.True())),
			jen.Id("r3").Op("=").Id("ctx").Dot("constants").Index(jen.Id("i3")),
			jen.Id("i4").Op("=").Id("r3").Dot("Ref").Call(),
			jen.If(jen.Id("i4").Op("<").Lit(0).Op("||").Id("i4").Op(">=").Len(jen.Id("ctx").Dot("heap"))).Block(jen.Return(jen.Lit(0), jen.True())),
			jen.If(jen.List(jen.Id("_"), jen.Id("stringConstant")).Op(":=").Id("ctx").Dot("heap").Index(jen.Id("i4")).Assert(jen.Qual("github.com/siyul-park/minivm/types", "String")), jen.Id("stringConstant")).Block(jen.Return(jen.Lit(0), jen.True())),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "REF_NULL")),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "DUP")).Block(
			jen.If(jen.Id("ctx").Dot("count").Call().Op("<").Lit(1).Op("||").Id("ctx").Dot("values").Index(jen.Len(jen.Id("ctx").Dot("values")).Op("-").Lit(1)).Dot("kind").Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(jen.Return(jen.Lit(0), jen.True())),
		),
		jen.Default().Block(jen.Return(jen.Lit(0), jen.True())),
	}
}

func arm64ConstantCall() []jen.Code {
	return []jen.Code{
		jen.Id("f").Op(":=").Id("ctx").Dot("frame").Call(),
		jen.Id("i3").Op(":=").Int().Parens(jen.Uint16().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(1))).Op("|").Uint16().Parens(jen.Id("f").Dot("code").Index(jen.Id("r0").Dot("ip").Op("+").Lit(2))).Op("<<").Lit(8)),
		jen.If(jen.Id("i3").Op(">=").Len(jen.Id("ctx").Dot("constants")).Op("||").Id("ctx").Dot("constants").Index(jen.Id("i3")).Dot("Kind").Call().Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(jen.Return(jen.Lit(0), jen.True())),
		jen.Id("r4").Op(":=").Id("ctx").Dot("constants").Index(jen.Id("i3")).Dot("Ref").Call(),
		jen.If(jen.Id("r4").Op("<").Lit(0).Op("||").Id("r4").Op(">=").Len(jen.Id("ctx").Dot("heap"))).Block(jen.Return(jen.Lit(0), jen.True())),
		jen.Id("callee").Op(":=").Id("r4"),
		jen.If(jen.List(jen.Id("closure"), jen.Id("ok")).Op(":=").Id("ctx").Dot("heap").Index(jen.Id("r4")).Assert(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Closure")), jen.Id("ok")).Block(jen.Id("callee").Op("=").Int().Parens(jen.Id("closure").Dot("Fn"))).Else().If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").Id("ctx").Dot("heap").Index(jen.Id("r4")).Assert(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")), jen.Op("!").Id("ok")).Block(jen.Return(jen.Lit(0), jen.True())),
		jen.If(jen.Id("callee").Op("!=").Id("r1").Dot("callee").Op("||").Id("ctx").Dot("funcs").Index(jen.Id("callee")).Op("==").Nil()).Block(jen.Return(jen.Lit(0), jen.True())),
		jen.Id("ctx").Dot("push").Call(jen.Id("value").Values(jen.Dict{jen.Id("kind"): jen.Qual("github.com/siyul-park/minivm/types", "KindRef"), jen.Id("raw"): jen.True(), jen.Id("fn"): jen.Id("callee"), jen.Id("ref"): jen.Id("r4")})),
		jen.If(jen.Id("r1").Dot("op").Op("==").Qual("github.com/siyul-park/minivm/instr", "CALL")).Block(jen.If(jen.Op("!").Id("l").Dot("call").Call(jen.Id("ctx"), jen.Id("r1"))).Block(jen.Return(jen.Lit(0), jen.False()))).Else().If(jen.Id("r1").Dot("callee").Op("==").Id("ctx").Dot("addr")).Block(jen.If(jen.Op("!").Id("l").Dot("tailLoop").Call(jen.Id("ctx"), jen.Id("r1"))).Block(jen.Return(jen.Lit(0), jen.False()))).Else().If(jen.Op("!").Id("l").Dot("tailMorph").Call(jen.Id("ctx"), jen.Id("r1"))).Block(jen.Return(jen.Lit(0), jen.False())),
		jen.Return(jen.Lit(2), jen.True()),
	}
}

func arm64RefCases() []jen.Code {
	drop := func() jen.Code {
		return jen.If(jen.Id("r1").Dot("op").Op("==").Qual("github.com/siyul-park/minivm/instr", "DROP")).Block(jen.Return(jen.Lit(2), jen.True()))
	}
	reg := func() jen.Code {
		return jen.Id("r4").Op("=").Id("ctx").Dot("assembler").Dot("Reg").Call(jen.Qual("github.com/siyul-park/minivm/asm", "RegTypeInt"), jen.Qual("github.com/siyul-park/minivm/asm", "Width64"))
	}
	return []jen.Code{
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "LOCAL_GET")).Block(
			drop(),
			jen.If(jen.Op("!").Id("l").Dot("loadLocal").Call(jen.Id("ctx"), jen.Id("f"), jen.Id("i0"), jen.Id("r0").Dot("ip"))).Block(jen.Return(jen.Lit(0), jen.False())),
			jen.Id("r4").Op("=").Id("f").Dot("locals").Index(jen.Id("i0")).Dot("reg"),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "GLOBAL_GET")).Block(
			drop(), reg(),
			jen.Id("ctx").Dot("assembler").Dot("Emit").Call(jen.Qual("github.com/siyul-park/minivm/asm/arm64", "LDR").Call(jen.Id("r4"), jen.Id("ctx").Dot("pin").Call(jen.Id("scratchGlobals")), jen.Int16().Parens(jen.Id("i1").Op("*").Lit(8)))),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "UPVAL_GET")).Block(
			drop(), reg(),
			jen.Id("ctx").Dot("assembler").Dot("Emit").Call(jen.Qual("github.com/siyul-park/minivm/asm/arm64", "LDR").Call(jen.Id("r4"), jen.Id("l").Dot("upvalBase").Call(jen.Id("ctx")), jen.Int16().Parens(jen.Id("i2").Op("*").Lit(8)))),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "CONST_GET")).Block(
			drop(), reg(),
			jen.Id("ctx").Dot("assembler").Dot("Emit").Call(jen.Qual("github.com/siyul-park/minivm/asm/arm64", "LDI").Call(jen.Id("r4"), jen.Uint64().Parens(jen.Id("r3"))).Op("...")),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "REF_NULL")).Block(
			drop(), reg(), jen.Id("ctx").Dot("assembler").Dot("Emit").Call(jen.Qual("github.com/siyul-park/minivm/asm/arm64", "LDI").Call(jen.Id("r4"), jen.Uint64().Parens(jen.Qual("github.com/siyul-park/minivm/types", "BoxedNull"))).Op("...")),
		),
		jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", "DUP")).Block(
			drop(),
			jen.Var().Id("ok").Bool(),
			jen.List(jen.Id("r4"), jen.Id("ok")).Op("=").Id("l").Dot("box").Call(jen.Id("ctx"), jen.Id("ctx").Dot("values").Index(jen.Len(jen.Id("ctx").Dot("values")).Op("-").Lit(1))),
			jen.If(jen.Op("!").Id("ok")).Block(jen.Return(jen.Lit(0), jen.False())),
		),
		jen.Default().Block(jen.Return(jen.Lit(0), jen.True())),
	}
}

func renderARM64Test(rules []rule) ([]byte, error) {
	var cases strings.Builder
	for _, rule := range rules {
		if !rule.arm64 {
			continue
		}
		fmt.Fprintf(&cases, "\t\t{name: %q, ops: []instr.Opcode{%s}},\n", testRuleName(rule), testOpcodes(rule.pattern))
	}
	return format.Source([]byte(fmt.Sprintf(`// Code generated by internal/cmd/genfusion; DO NOT EDIT.
//go:build arm64

package interp

import (
	"testing"

	"github.com/siyul-park/minivm/instr"
	"github.com/stretchr/testify/require"
)

func TestARM64Lowerer_FusionRules(t *testing.T) {
	tests := []struct {
		name string
		ops  []instr.Opcode
	}{
%s	}
	width := func(op instr.Opcode) int {
		width := 1
		for _, operand := range instr.TypeOf(op).Widths {
			width += operand
		}
		return width
	}
	l := arm64Lowerer{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ops := make([]step, len(tt.ops))
			ip := 0
			for i, op := range tt.ops {
				ops[i] = step{op: op, ip: ip}
				ip += width(op)
			}
			ctx := &lowering{tree: &tree{root: &trace{anchor: anchor{ip: -1}}}}
			require.Equal(t, len(tt.ops), l.match(ctx, ops, 0))
		})
	}
}

func TestARM64Lowerer_FusionRejectsUndeclaredPair(t *testing.T) {
	ops := []step{{op: instr.I32_CONST, ip: 0}, {op: instr.DROP, ip: 5}}
	ctx := &lowering{tree: &tree{root: &trace{anchor: anchor{ip: -1}}}}
	require.Zero(t, (arm64Lowerer{}).match(ctx, ops, 0))
}
`, cases.String())))
}

func formatARM64(file *jen.File) ([]byte, error) {
	data := append([]byte("//go:build arm64\n\n"), []byte(file.GoString())...)
	return formatGenerated(data)
}

// renderCall emits compile-time target resolution followed by target-specific
// final handlers. Source semantics are repeated in each handler; generated
// code has no source callback, runtime target switch, or yield scan.
func renderCall(rule rule, label string) ([]jen.Code, error) {
	if len(rule.pattern) != 2 || rule.pattern[0].op != instr.CONST_GET {
		return nil, fmt.Errorf("unsupported constant call pattern")
	}
	consumer := rule.pattern[1].op
	if consumer != instr.CALL && consumer != instr.RETURN_CALL && consumer != instr.CLOSURE_NEW {
		return nil, fmt.Errorf("unsupported constant call consumer %s", instr.TypeOf(consumer).Mnemonic)
	}

	code := []jen.Code{
		jen.Id("idx").Op(":=").Int().Parens(jen.Id("uint16").Parens(jen.Id("c").Dot("code").Index(jen.Id("c").Dot("ip").Op("+").Lit(1))).Op("|").Id("uint16").Parens(jen.Id("c").Dot("code").Index(jen.Id("c").Dot("ip").Op("+").Lit(2))).Op("<<").Lit(8)),
		jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
		jen.Id("boxed").Op(":=").Id("c").Dot("constants").Index(jen.Id("idx")),
		jen.If(jen.Id("boxed").Dot("Kind").Call().Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(reject(label)),
		jen.Id("addr").Op(":=").Id("boxed").Dot("Ref").Call(),
		jen.If(jen.Id("addr").Op("<").Lit(0).Op("||").Id("addr").Op(">=").Len(jen.Id("c").Dot("heap"))).Block(reject(label)),
	}

	switch consumer {
	case instr.CALL:
		code = append(code, renderCallSwitch(false, label))
	case instr.RETURN_CALL:
		code = append(code, renderCallSwitch(true, label))
	case instr.CLOSURE_NEW:
		code = append(code, renderClosureNew(label))
	}
	return code, nil
}

func renderCallSwitch(tail bool, label string) jen.Code {
	return jen.Switch(jen.Id("fn").Op(":=").Id("c").Dot("heap").Index(jen.Id("addr")).Assert(jen.Type())).Block(
		jen.Case(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")).Block(renderFunctionCall(tail, label)...),
		jen.Case(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Closure")).Block(renderClosureCall(tail, label)...),
		jen.Case(jen.Op("*").Id("HostFunction")).Block(renderHostCall(tail)...),
		jen.Default().Block(reject(label)),
	)
}

func renderFunctionCall(tail bool, label string) []jen.Code {
	guard := jen.If(jen.Id("addr").Op("<").Len(jen.Id("c").Dot("coros")).Op("&&").Id("c").Dot("coros").Index(jen.Id("addr"))).Block(reject(label))
	if tail {
		return append([]jen.Code{guard}, renderTailFrame(jen.Id("addr"), jen.Nil(), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("fn").Dot("Locals")))...)
	}
	return append([]jen.Code{guard}, renderFrameCall(jen.Id("addr"), jen.Nil(), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("fn").Dot("Locals")))...)
}

func renderClosureCall(tail bool, label string) []jen.Code {
	preflight := []jen.Code{
		jen.Id("tmpl").Op(",").Id("ok").Op(":=").Id("c").Dot("heap").Index(jen.Id("fn").Dot("Fn")).Assert(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")),
		jen.If(jen.Op("!").Id("ok")).Block(reject(label)),
		jen.If(jen.Int().Parens(jen.Id("fn").Dot("Fn")).Op("<").Len(jen.Id("c").Dot("coros")).Op("&&").Id("c").Dot("coros").Index(jen.Id("fn").Dot("Fn"))).Block(reject(label)),
	}
	if tail {
		return append(preflight, renderTailFrame(jen.Int().Parens(jen.Id("fn").Dot("Fn")), jen.Id("fn").Dot("Upvals"), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("tmpl").Dot("Locals")))...)
	}
	return append(preflight, renderFrameCall(jen.Int().Parens(jen.Id("fn").Dot("Fn")), jen.Id("fn").Dot("Upvals"), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("tmpl").Dot("Locals")))...)
}

func renderTailFrame(addr, upvals, ref, typ, locals jen.Code) []jen.Code {
	return []jen.Code{
		jen.Id("params").Op(":=").Len(jen.Add(typ).Dot("Params")),
		jen.Id("returns").Op(":=").Len(jen.Add(typ).Dot("Returns")),
		jen.Id("locals").Op(":=").Add(locals),
		jen.Id("c").Dot("ip").Op("+=").Lit(3),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			constantSourceOverflow(),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("fp").Op("==").Lit(1)).Block(
				jen.If(jen.Id("i").Dot("fp").Op("==").Len(jen.Id("i").Dot("frames"))).Block(jen.Panic(jen.Id("ErrFrameOverflow"))),
				jen.If(jen.Id("i").Dot("sp").Op("+").Id("locals").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
				jen.If(jen.Id("locals").Op(">").Lit(0)).Block(jen.Clear(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op(":").Id("i").Dot("sp").Op("+").Id("locals")))),
				jen.Id("f").Op(":=").Op("&").Id("i").Dot("frames").Index(jen.Id("i").Dot("fp")),
				jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Add(addr)),
				jen.Id("f").Dot("upvals").Op("=").Add(upvals),
				jen.Id("f").Dot("addr").Op("=").Add(addr),
				jen.Id("f").Dot("ref").Op("=").Add(ref),
				jen.Id("f").Dot("bp").Op("=").Id("i").Dot("sp").Op("-").Id("params"),
				jen.Id("f").Dot("returns").Op("=").Id("returns"),
				jen.Id("f").Dot("release").Op("=").False(),
				jen.Id("f").Dot("coro").Op("=").Lit(0),
				jen.Id("i").Dot("sp").Op("=").Id("f").Dot("bp").Op("+").Id("params").Op("+").Id("locals"),
				jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
				jen.Id("i").Dot("fp").Op("++"),
				jen.Id("i").Dot("fr").Op("=").Id("f"),
				jen.Return(),
			),
			jen.Id("f").Op(":=").Id("i").Dot("fr"),
			jen.Id("base").Op(":=").Id("f").Dot("bp"),
			jen.If(jen.Id("base").Op("+").Id("params").Op("+").Id("locals").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Copy(jen.Id("i").Dot("stack").Index(jen.Id("base").Op(":").Id("base").Op("+").Id("params")), jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("params").Op(":").Id("i").Dot("sp"))),
			jen.If(jen.Id("f").Dot("release")).Block(jen.Id("i").Dot("release").Call(jen.Id("f").Dot("ref"))),
			jen.If(jen.Id("locals").Op(">").Lit(0)).Block(jen.Clear(jen.Id("i").Dot("stack").Index(jen.Id("base").Op("+").Id("params").Op(":").Id("base").Op("+").Id("params").Op("+").Id("locals")))),
			jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Add(addr)),
			jen.Id("f").Dot("upvals").Op("=").Add(upvals),
			jen.Id("f").Dot("addr").Op("=").Add(addr),
			jen.Id("f").Dot("ref").Op("=").Add(ref),
			jen.Id("f").Dot("ip").Op("=").Lit(0),
			jen.Id("f").Dot("returns").Op("=").Id("returns"),
			jen.Id("f").Dot("release").Op("=").False(),
			jen.Id("f").Dot("coro").Op("=").Lit(0),
			jen.Id("i").Dot("sp").Op("=").Id("base").Op("+").Id("params").Op("+").Id("locals"),
		)),
	}
}

func renderFrameCall(addr, upvals, ref, typ, locals jen.Code) []jen.Code {
	return []jen.Code{
		jen.Id("params").Op(":=").Len(jen.Add(typ).Dot("Params")),
		jen.Id("returns").Op(":=").Len(jen.Add(typ).Dot("Returns")),
		jen.Id("locals").Op(":=").Add(locals),
		jen.Id("c").Dot("ip").Op("+=").Lit(3),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			constantSourceOverflow(),
			jen.If(jen.Id("i").Dot("fp").Op("==").Len(jen.Id("i").Dot("frames"))).Block(jen.Panic(jen.Id("ErrFrameOverflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("+").Id("locals").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.If(jen.Id("locals").Op(">").Lit(0)).Block(jen.Clear(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op(":").Id("i").Dot("sp").Op("+").Id("locals")))),
			jen.Id("f").Op(":=").Op("&").Id("i").Dot("frames").Index(jen.Id("i").Dot("fp")),
			jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Add(addr)),
			jen.Id("f").Dot("upvals").Op("=").Add(upvals),
			jen.Id("f").Dot("addr").Op("=").Add(addr),
			jen.Id("f").Dot("ref").Op("=").Add(ref),
			jen.Id("f").Dot("ip").Op("=").Lit(0),
			jen.Id("f").Dot("bp").Op("=").Id("i").Dot("sp").Op("-").Id("params"),
			jen.Id("f").Dot("returns").Op("=").Id("returns"),
			jen.Id("f").Dot("release").Op("=").False(),
			jen.Id("f").Dot("coro").Op("=").Lit(0),
			jen.Id("i").Dot("sp").Op("=").Id("f").Dot("bp").Op("+").Id("params").Op("+").Id("locals"),
			jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
			jen.Id("i").Dot("fp").Op("++"),
			jen.Id("i").Dot("fr").Op("=").Id("f"),
		)),
	}
}

func renderHostCall(tail bool) []jen.Code {
	body := []jen.Code{
		jen.Id("params").Op(":=").Len(jen.Id("fn").Dot("Typ").Dot("Params")),
		jen.Id("returns").Op(":=").Len(jen.Id("fn").Dot("Typ").Dot("Returns")),
		jen.Id("c").Dot("ip").Op("+=").Lit(3),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			constantSourceOverflow(),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("+").Id("returns").Op("-").Id("params").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("args").Op(":=").Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("params").Op(":").Id("i").Dot("sp")),
			jen.Id("out").Op(",").Id("err").Op(":=").Id("fn").Dot("Fn").Call(jen.Id("i"), jen.Id("args")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(jen.Panic(jen.Id("err"))),
			jen.Id("i").Dot("releaseArgs").Call(jen.Id("args"), jen.Id("out")),
			jen.Id("i").Dot("sp").Op("+=").Id("returns").Op("-").Id("params"),
			jen.Copy(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("returns").Op(":").Id("i").Dot("sp")), jen.Id("out")),
			jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
		)),
	}
	if tail {
		// Tail-host retirement remains explicit in the final handler; no
		// constant funcref was retained, so only arguments flow to releaseArgs.
		body[len(body)-1] = jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			constantSourceOverflow(),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("+").Id("returns").Op("-").Id("params").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("args").Op(":=").Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("params").Op(":").Id("i").Dot("sp")),
			jen.Id("out").Op(",").Id("err").Op(":=").Id("fn").Dot("Fn").Call(jen.Id("i"), jen.Id("args")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(jen.Panic(jen.Id("err"))),
			jen.Id("i").Dot("releaseArgs").Call(jen.Id("args"), jen.Id("out")),
			jen.Id("i").Dot("sp").Op("+=").Id("returns").Op("-").Id("params"),
			jen.Copy(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("returns").Op(":").Id("i").Dot("sp")), jen.Id("out")),
			jen.If(jen.Id("i").Dot("fp").Op(">").Lit(1)).Block(jen.Id("i").Dot("ret").Call()),
		))
	}
	return body
}

func renderClosureNew(label string) jen.Code {
	return jen.Switch(jen.Id("fn").Op(":=").Id("c").Dot("heap").Index(jen.Id("addr")).Assert(jen.Type())).Block(
		jen.Case(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")).Block(
			jen.Id("captures").Op(":=").Len(jen.Id("fn").Dot("Captures")),
			jen.Id("c").Dot("ip").Op("+=").Lit(3),
			jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
				constantSourceOverflow(),
				jen.If(jen.Id("i").Dot("sp").Op("<").Id("captures")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
				jen.Id("upvals").Op(":=").Append(jen.Index().Qual("github.com/siyul-park/minivm/types", "Boxed").Values(), jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("captures").Op(":").Id("i").Dot("sp")).Op("...")),
				jen.Id("i").Dot("retain").Call(jen.Id("addr")),
				jen.Id("closure").Op(":=").Qual("github.com/siyul-park/minivm/types", "NewClosure").Call(jen.Id("fn").Dot("Typ"), jen.Qual("github.com/siyul-park/minivm/types", "Ref").Parens(jen.Id("addr")), jen.Id("upvals")),
				jen.Id("i").Dot("sp").Op("-=").Id("captures"),
				jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Qual("github.com/siyul-park/minivm/types", "BoxRef").Call(jen.Id("i").Dot("keep").Call(jen.Id("closure"))),
				jen.Id("i").Dot("sp").Op("++"),
				jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
			)),
		),
		jen.Default().Block(reject(label)),
	)
}

func constantSourceOverflow() jen.Code {
	return jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow")))
}

func numericConsumer(op instr.Opcode) (int, string, bool) {
	if op == instr.I32_EQZ || op == instr.I64_EQZ {
		return 1, numericConsumerMethod(op), true
	}
	for _, family := range numericFamilies() {
		if slices.Contains(family.binary, op) || slices.Contains(family.compares, op) {
			return 2, numericConsumerMethod(op), true
		}
	}
	return 0, "", false
}

func numericConsumerMethod(op instr.Opcode) string {
	mnemonic := instr.TypeOf(op).Mnemonic
	prefix, suffix, _ := strings.Cut(mnemonic, ".")
	var name strings.Builder
	name.WriteString(prefix)
	for _, segment := range strings.Split(suffix, "_") {
		if segment == "" {
			continue
		}
		name.WriteString(strings.ToUpper(segment[:1]))
		name.WriteString(segment[1:])
	}
	return name.String()
}

func renderRefFusion(rule rule, total int, label string) ([]jen.Code, error) {
	pattern := rule.pattern
	if len(pattern) < 2 {
		return nil, fmt.Errorf("ref rule has no consumer")
	}
	if len(pattern) > 3 || len(pattern) == 3 && pattern[2].op != instr.BR_IF {
		return nil, fmt.Errorf("ref rule has unsupported trailing operations")
	}
	source := pattern[0].op
	consumer := pattern[1].op
	branch := len(pattern) == 3 && pattern[2].op == instr.BR_IF
	pre, body, err := renderRefSource(source, label)
	if err != nil {
		return nil, err
	}
	switch consumer {
	case instr.DROP:
		body = append(body, jen.Id("_").Op("=").Id("value"), jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(total))
	case instr.REF_IS_NULL:
		if branch {
			body = append(body, jen.Id("i").Dot("branchIf").Call(jen.Id("value").Dot("Ref").Call().Op("==").Lit(0), jen.Id("offset"), jen.Lit(total)))
		} else {
			body = append(body,
				jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Qual("github.com/siyul-park/minivm/types", "BoxI1").Call(jen.Id("value").Dot("Ref").Call().Op("==").Lit(0)),
				jen.Id("i").Dot("sp").Op("++"),
				jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(total),
			)
		}
	default:
		return nil, fmt.Errorf("unsupported ref consumer %s", instr.TypeOf(consumer).Mnemonic)
	}
	pre = append(pre,
		jen.Id("c").Dot("ip").Op("+=").Lit(opcodeWidth(source)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)),
	)
	return pre, nil
}

func renderRefSource(op instr.Opcode, label string) ([]jen.Code, []jen.Code, error) {
	overflow := jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow")))
	switch op {
	case instr.LOCAL_GET:
		return []jen.Code{
				jen.Id("idx").Op(":=").Int().Call(jen.Id("c").Dot("code").Index(jen.Id("start").Op("+").Lit(1))),
				refMetadata("locals", label),
			}, []jen.Code{
				overflow,
				jen.Id("addr").Op(":=").Id("i").Dot("fr").Dot("bp").Op("+").Id("idx"),
				jen.If(jen.Id("addr").Op(">=").Id("i").Dot("sp")).Block(jen.Panic(jen.Id("ErrSegmentationFault"))),
				jen.Id("value").Op(":=").Id("i").Dot("stack").Index(jen.Id("addr")),
			}, nil
	case instr.GLOBAL_GET:
		return []jen.Code{
				jen.Id("idx").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(1)),
				refMetadata("globals", label),
			}, []jen.Code{
				overflow,
				jen.If(jen.Id("idx").Op(">=").Len(jen.Id("i").Dot("globals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))),
				jen.Id("value").Op(":=").Id("i").Dot("globals").Index(jen.Id("idx")),
			}, nil
	case instr.UPVAL_GET:
		return []jen.Code{
				jen.Id("idx").Op(":=").Int().Call(jen.Id("c").Dot("code").Index(jen.Id("start").Op("+").Lit(1))),
				refMetadata("captures", label),
			}, []jen.Code{
				overflow,
				jen.If(jen.Id("idx").Op(">=").Len(jen.Id("i").Dot("fr").Dot("upvals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))),
				jen.Id("value").Op(":=").Id("i").Dot("fr").Dot("upvals").Index(jen.Id("idx")),
			}, nil
	case instr.CONST_GET:
		return []jen.Code{
			jen.Id("idx").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(1)),
			jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
			jen.Id("constant").Op(":=").Id("c").Dot("constants").Index(jen.Id("idx")),
			jen.If(jen.Id("constant").Dot("Kind").Call().Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(reject(label)),
			jen.Id("addr").Op(":=").Id("constant").Dot("Ref").Call(),
			jen.If(jen.Id("addr").Op("<").Lit(0).Op("||").Id("addr").Op(">=").Len(jen.Id("c").Dot("heap"))).Block(reject(label)),
			jen.If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").Id("c").Dot("heap").Index(jen.Id("addr")).Assert(jen.Qual("github.com/siyul-park/minivm/types", "String")), jen.Id("ok")).Block(reject(label)),
		}, []jen.Code{overflow, jen.Id("value").Op(":=").Id("constant")}, nil
	case instr.REF_NULL:
		return nil, []jen.Code{overflow, jen.Id("value").Op(":=").Qual("github.com/siyul-park/minivm/types", "BoxedNull")}, nil
	case instr.DUP:
		return nil, []jen.Code{
			jen.If(jen.Id("i").Dot("sp").Op("==").Lit(0)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			overflow,
			jen.Id("value").Op(":=").Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)),
		}, nil
	default:
		return nil, nil, fmt.Errorf("unsupported ref source %s", instr.TypeOf(op).Mnemonic)
	}
}

func refMetadata(field, label string) jen.Code {
	return jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot(field)).Op("||").Id("c").Dot(field).Index(jen.Id("idx")).Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(reject(label))
}

// renderThreadedIndex emits direct CONST/I32_CONST index specialization for
// ARRAY_GET and STRUCT_GET. The handler preserves producer overflow before
// consumer underflow, then delegates exact ownership/trap behavior to *GetAt.
func renderThreadedIndex(rule rule, totalWidth int, label string) ([]jen.Code, error) {
	if len(rule.pattern) != 2 {
		return nil, fmt.Errorf("index fusion needs two opcodes")
	}
	source := rule.pattern[0].op
	consumer := rule.pattern[1].op
	if consumer != instr.ARRAY_GET && consumer != instr.STRUCT_GET {
		return nil, fmt.Errorf("unsupported index consumer %s", instr.TypeOf(consumer).Mnemonic)
	}
	var pre []jen.Code
	switch source {
	case instr.I32_CONST:
		pre = append(pre,
			jen.Id("index").Op(":=").Int().Call(jen.Int32().Call(
				jen.Qual("github.com/siyul-park/minivm/instr", "Instruction").Call(jen.Id("c").Dot("code").Index(jen.Id("start").Op(":"))).Dot("Operand").Call(jen.Lit(0)),
			)),
		)
	case instr.CONST_GET:
		pre = append(pre,
			jen.Id("idx").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(1)),
			jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
			jen.Id("constant").Op(",").Id("ok").Op(":=").Qual("github.com/siyul-park/minivm/types", "Unbox").Call(jen.Id("c").Dot("constants").Index(jen.Id("idx"))).Assert(jen.Qual("github.com/siyul-park/minivm/types", "I32")),
			jen.If(jen.Op("!").Id("ok")).Block(reject(label)),
			jen.Id("index").Op(":=").Int().Call(jen.Id("constant")),
		)
	default:
		return nil, fmt.Errorf("unsupported index source %s", instr.TypeOf(source).Mnemonic)
	}
	method := "arrayGetAt"
	if consumer == instr.STRUCT_GET {
		method = "structGetAt"
	}
	body := []jen.Code{
		jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
		jen.If(jen.Id("i").Dot("sp").Op("==").Lit(0)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
		jen.Id("result").Op(":=").Id("i").Dot(method).Call(jen.Id("index")),
		jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Id("result"),
		jen.Id("i").Dot("sp").Op("++"),
		jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(totalWidth),
	}
	pre = append(pre,
		jen.Id("c").Dot("ip").Op("+=").Lit(opcodeWidth(source)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)),
	)
	return pre, nil
}

// renderNumericFusion emits preflight plus one concrete runtime handler for a
// normalized rule. Every source access is inline in that handler.
func renderNumericFusion(rule rule, totalWidth int, label string) ([]jen.Code, error) {
	pattern := rule.pattern
	branch := len(pattern) > 0 && pattern[len(pattern)-1].op == instr.BR_IF
	consumerAt := len(pattern) - 1
	if branch {
		consumerAt--
	}
	if consumerAt < 0 {
		return nil, fmt.Errorf("numeric rule has no consumer")
	}
	consumer := pattern[consumerAt].op
	arity, method, ok := numericConsumer(consumer)
	if !ok {
		return nil, fmt.Errorf("unsupported numeric consumer %s", instr.TypeOf(consumer).Mnemonic)
	}
	kind, _ := numericKind(consumer)
	sources := pattern[:consumerAt]
	if len(sources) > 2 {
		return nil, fmt.Errorf("numeric rule has %d sources", len(sources))
	}

	var pre, body []jen.Code
	var renderedSources []renderedNumericSource
	offset := 0
	for idx, source := range sources {
		rendered, err := renderThreadedNumericSource(source.op, idx, len(sources), offset, kind, label)
		if err != nil {
			return nil, err
		}
		pre = append(pre, rendered.pre...)
		renderedSources = append(renderedSources, rendered)
		offset += rendered.width
	}
	if len(renderedSources) == 2 {
		slow := []jen.Code{
			jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
		}
		slow = append(slow, renderedSources[0].load...)
		slow = append(slow, jen.Id("_").Op("=").Id(numericSourceName(0)))
		slow = append(slow, jen.If(add(jen.Id("i").Dot("sp"), 1).Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))))
		body = append(body, jen.If(jen.Id("i").Dot("sp").Op(">=").Len(jen.Id("i").Dot("stack")).Op("-").Lit(1)).Block(slow...))
	}
	for idx, rendered := range renderedSources {
		if len(renderedSources) != 2 {
			body = append(body, jen.If(add(jen.Id("i").Dot("sp"), idx).Op("==").Len(jen.Id("i").Dot("stack"))).Block(
				jen.Panic(jen.Id("ErrStackOverflow")),
			))
		}
		body = append(body, rendered.load...)
	}

	var operands []jen.Code
	switch len(sources) {
	case 0:
		body = append(body, jen.If(jen.Id("i").Dot("sp").Op("<").Lit(arity)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))))
		if arity == 1 {
			operands = []jen.Code{numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1))}
		} else {
			operands = []jen.Code{
				numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(2)),
				numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1)),
			}
		}
	case 1:
		body = append(body, jen.If(jen.Id("i").Dot("sp").Op("==").Lit(0)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))))
		operands = []jen.Code{numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1)), jen.Id(numericSourceName(len(sources) - 1))}
	case 2:
		operands = []jen.Code{jen.Id(numericSourceName(0)), jen.Id(numericSourceName(len(sources) - 1))}
	}
	if consumer == instr.I32_XOR || consumer == instr.I32_AND || consumer == instr.I32_OR {
		for idx := range sources {
			body = append(body, jen.Id("_").Op("=").Id(numericSourceName(idx)))
		}
		switch len(sources) {
		case 1:
			operands = []jen.Code{jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)), boxedNumericSource(sources[0].op, 0)}
		case 2:
			operands = []jen.Code{boxedNumericSource(sources[0].op, 0), boxedNumericSource(sources[1].op, 1)}
		}
	}
	if len(operands) != arity {
		return nil, fmt.Errorf("%s needs %d operands", instr.TypeOf(consumer).Mnemonic, arity)
	}
	body = append(body, jen.Id(numericSourceName(len(sources))).Op(":=").Id("i").Dot(method).Call(operands...))
	if branch {
		delta := len(sources) - len(operands)
		if delta > 0 {
			body = append(body, jen.Id("i").Dot("sp").Op("+=").Lit(delta))
		} else if delta < 0 {
			body = append(body, jen.Id("i").Dot("sp").Op("-=").Lit(-delta))
		}
		body = append(body, jen.Id("i").Dot("branchIf").Call(jen.Id(numericSourceName(len(sources))).Dot("Bool").Call(), jen.Id("offset"), jen.Lit(totalWidth)))
	} else {
		switch len(sources) {
		case 0:
			body = append(body, jen.Id("i").Dot("sp").Op("--"), jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)).Op("=").Id(numericSourceName(len(sources))))
		case 1:
			body = append(body, jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)).Op("=").Id(numericSourceName(len(sources))))
		case 2:
			body = append(body, jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Id(numericSourceName(len(sources))), jen.Id("i").Dot("sp").Op("++"))
		}
		body = append(body, jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(totalWidth))
	}
	pre = append(pre, jen.Id("c").Dot("ip").Op("+=").Lit(opcodeWidth(pattern[0].op)))
	pre = append(pre, jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)))
	return pre, nil
}

func renderThreadedNumericSource(op instr.Opcode, number, count, offset int, kind, label string) (renderedNumericSource, error) {
	width := opcodeWidth(op)
	name := numericSourceName(number)
	boxed := boxedNumericName(name)
	idx := fmt.Sprintf("i%d", number)
	addr := fmt.Sprintf("i%d", count+number)
	at := add(jen.Id("start"), offset)
	result := renderedNumericSource{width: width}
	switch op {
	case instr.LOCAL_GET, instr.UPVAL_GET:
		result.pre = append(result.pre, jen.Id(idx).Op(":=").Int().Call(jen.Id("c").Dot("code").Index(jen.Add(at).Op("+").Lit(1))))
	case instr.GLOBAL_GET, instr.CONST_GET:
		result.pre = append(result.pre, jen.Id(idx).Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Add(at).Op("+").Lit(1)))
	}
	expected := jen.Qual("github.com/siyul-park/minivm/types", "Kind"+kind)
	switch op {
	case instr.LOCAL_GET:
		result.pre = append(result.pre, numericMetadataCheck("locals", idx, expected, label))
		result.load = append(result.load, jen.Id(addr).Op(":=").Id("i").Dot("fr").Dot("bp").Op("+").Id(idx), jen.If(jen.Id(addr).Op(">=").Id("i").Dot("sp")).Block(jen.Panic(jen.Id("ErrSegmentationFault"))), jen.Id(boxed).Op(":=").Id("i").Dot("stack").Index(jen.Id(addr)), jen.Id(name).Op(":=").Add(numericBoxValue(kind, jen.Id(boxed))))
	case instr.GLOBAL_GET:
		result.pre = append(result.pre, numericMetadataCheck("globals", idx, expected, label))
		result.load = append(result.load, jen.If(jen.Id(idx).Op(">=").Len(jen.Id("i").Dot("globals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))), jen.Id(boxed).Op(":=").Id("i").Dot("globals").Index(jen.Id(idx)), jen.Id(name).Op(":=").Add(numericBoxValue(kind, jen.Id(boxed))))
	case instr.UPVAL_GET:
		result.pre = append(result.pre, numericMetadataCheck("captures", idx, expected, label))
		result.load = append(result.load, jen.If(jen.Id(idx).Op(">=").Len(jen.Id("i").Dot("fr").Dot("upvals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))), jen.Id(boxed).Op(":=").Id("i").Dot("fr").Dot("upvals").Index(jen.Id(idx)), jen.Id(name).Op(":=").Add(numericBoxValue(kind, jen.Id(boxed))))
	case instr.CONST_GET:
		result.pre = append(result.pre,
			jen.If(jen.Id(idx).Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
			jen.Id(boxed).Op(":=").Id("c").Dot("constants").Index(jen.Id(idx)),
		)
		if kind == "I64" {
			result.pre = append(result.pre,
				jen.Var().Id(name).Int64(),
				jen.Switch(jen.Id(boxed).Dot("Kind").Call()).Block(
					jen.Case(jen.Qual("github.com/siyul-park/minivm/types", "KindI64")).Block(jen.Id(name).Op("=").Id(boxed).Dot("I64").Call()),
					jen.Case(jen.Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(
						jen.Id("constantRef").Op(":=").Id(boxed).Dot("Ref").Call(),
						jen.If(jen.Id("constantRef").Op("<").Lit(0).Op("||").Id("constantRef").Op(">=").Len(jen.Id("c").Dot("heap"))).Block(reject(label)),
						jen.List(jen.Id("constantI64"), jen.Id("ok")).Op(":=").Id("c").Dot("heap").Index(jen.Id("constantRef")).Assert(jen.Qual("github.com/siyul-park/minivm/types", "I64")),
						jen.If(jen.Op("!").Id("ok")).Block(reject(label)),
						jen.Id(name).Op("=").Int64().Call(jen.Id("constantI64")),
					),
					jen.Default().Block(reject(label)),
				),
			)
		} else {
			result.pre = append(result.pre,
				jen.If(jen.Id(boxed).Dot("Kind").Call().Op("!=").Add(expected)).Block(reject(label)),
				jen.Id(name).Op(":=").Add(numericBoxValue(kind, jen.Id(boxed))),
			)
		}
	case instr.I32_CONST, instr.I64_CONST, instr.F32_CONST, instr.F64_CONST:
		result.pre = append(result.pre, jen.Id(name).Op(":=").Add(numericImmediate(kind, at)))
	default:
		return renderedNumericSource{}, fmt.Errorf("unsupported numeric source %s", instr.TypeOf(op).Mnemonic)
	}
	return result, nil
}

func boxedNumericSource(op instr.Opcode, number int) jen.Code {
	source := numericSourceName(number)
	name := boxedNumericName(source)
	if op == instr.I32_CONST {
		return jen.Qual("github.com/siyul-park/minivm/types", "BoxI32").Call(jen.Id(source))
	}
	return jen.Id(name)
}

func numericSourceName(number int) string {
	return fmt.Sprintf("v%d", number)
}

func boxedNumericName(source string) string {
	return "r" + strings.TrimPrefix(source, "v")
}

func numericMetadataCheck(field, idx string, expected jen.Code, label string) jen.Code {
	return jen.If(jen.Id(idx).Op(">=").Len(jen.Id("c").Dot(field)).Op("||").Id("c").Dot(field).Index(jen.Id(idx)).Dot("Repr").Call().Op("!=").Add(expected)).Block(reject(label))
}

func numericKind(op instr.Opcode) (string, bool) {
	prefix := strings.Split(instr.TypeOf(op).Mnemonic, ".")[0]
	switch prefix {
	case "i32":
		return "I32", true
	case "i64":
		return "I64", true
	case "f32":
		return "F32", true
	case "f64":
		return "F64", true
	}
	return "", false
}

func numericBoxValue(kind string, value jen.Code) jen.Code {
	if kind == "I64" {
		return jen.Id("i").Dot("borrowI64").Call(value)
	}
	return jen.Add(value).Dot(kind).Call()
}

func numericStackValue(kind string, index jen.Code) jen.Code {
	return numericBoxValue(kind, jen.Id("i").Dot("stack").Index(index))
}

func numericImmediate(kind string, at jen.Code) jen.Code {
	operand := jen.Qual("github.com/siyul-park/minivm/instr", "Instruction").Call(jen.Id("c").Dot("code").Index(jen.Add(at).Op(":"))).Dot("Operand").Call(jen.Lit(0))
	switch kind {
	case "I32":
		return jen.Int32().Call(operand)
	case "I64":
		return jen.Int64().Call(operand)
	case "F32":
		return jen.Qual("github.com/siyul-park/minivm/types", "Box").Call(jen.Uint64().Call(jen.Uint32().Call(operand)), jen.Qual("github.com/siyul-park/minivm/types", "KindF32")).Dot("F32").Call()
	default:
		return jen.Qual("github.com/siyul-park/minivm/types", "Boxed").Call(operand).Dot("F64").Call()
	}
}

func opcodeWidth(op instr.Opcode) int {
	width := 1
	for _, operand := range instr.TypeOf(op).Widths {
		width += operand
	}
	return width
}

func add(value jen.Code, offset int) *jen.Statement {
	if offset == 0 {
		return jen.Add(value)
	}
	return jen.Add(value).Op("+").Lit(offset)
}

func formatGenerated(source []byte) ([]byte, error) {
	data, err := format.Source(source)
	if err != nil {
		return nil, err
	}
	for _, path := range []string{
		"github.com/siyul-park/minivm/asm",
		"github.com/siyul-park/minivm/asm/arm64",
		"github.com/siyul-park/minivm/instr",
		"github.com/siyul-park/minivm/types",
	} {
		name := path[strings.LastIndexByte(path, '/')+1:]
		data = bytes.ReplaceAll(data, []byte(name+" \""+path+"\""), []byte("\""+path+"\""))
	}
	return data, nil
}
