package main

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/siyul-park/minivm/instr"
)

type output struct {
	path string
	data []byte
}

func generate() ([]output, error) {
	rules, err := expand(declarations()...)
	if err != nil {
		return nil, err
	}
	if err := validate(rules); err != nil {
		return nil, err
	}
	threaded, err := renderThreaded(rules)
	if err != nil {
		return nil, err
	}
	test, err := renderFusionTest(rules)
	if err != nil {
		return nil, err
	}
	return []output{
		{path: "interp/threaded.go", data: threaded},
		{path: "interp/threaded_test.go", data: test},
	}, nil
}

func renderThreaded(rules []rule) ([]byte, error) {
	file := jen.NewFile("interp")
	file.HeaderComment("Code generated by internal/cmd/genfusion; DO NOT EDIT.")

	renderType(file)
	fusions, err := renderFusions(rules)
	if err != nil {
		return nil, err
	}
	file.Var().Defs(
		jen.Id("threaded").Op("=").Add(renderOpcodes()),
		jen.Id("invalid").Op("=").Func().Params(jen.Id("_").Op("*").Id("Interpreter")).Block(jen.Panic(jen.Id("ErrUnknownOpcode"))),
		jen.Id("fusions").Op("=").Add(fusions),
	)
	renderInit(file)
	renderCompile(file)
	return format.Source([]byte(file.GoString()))
}

func renderType(file *jen.File) {
	file.Type().Id("threader").Struct(
		jen.Id("types").Index().Qual("github.com/siyul-park/minivm/types", "Type"),
		jen.Id("constants").Index().Qual("github.com/siyul-park/minivm/types", "Boxed"),
		jen.Id("heap").Index().Qual("github.com/siyul-park/minivm/types", "Value"),
		jen.Id("coros").Index().Bool(),
		jen.Id("locals").Index().Qual("github.com/siyul-park/minivm/types", "Kind"),
		jen.Id("globals").Index().Qual("github.com/siyul-park/minivm/types", "Kind"),
		jen.Id("captures").Index().Qual("github.com/siyul-park/minivm/types", "Kind"),
		jen.Id("code").Index().Byte(),
		jen.Id("ip").Int(),
		jen.Id("exact").Bool(),
	)
}

func renderOpcodes() jen.Code {
	table := jen.Index(jen.Lit(256)).Func().Params(jen.Id("c").Op("*").Id("threader")).Func().Params(jen.Id("i").Op("*").Id("Interpreter"))
	return table.ValuesFunc(func(group *jen.Group) {
		for opcode, lowering := range lowerings {
			if lowering == nil {
				continue
			}
			group.Line().Qual("github.com/siyul-park/minivm/instr", opcodeName(instr.Opcode(opcode))).Op(":").Add(lowering(&lower{}))
		}
	})
}

func renderInit(file *jen.File) {
	file.Func().Id("init").Params().Block(
		jen.For(jen.List(jen.Id("i"), jen.Id("fn")).Op(":=").Range().Id("threaded")).Block(
			jen.If(jen.Id("fn").Op("==").Nil()).Block(
				jen.Id("threaded").Index(jen.Id("i")).Op("=").Func().Params(jen.Id("c").Op("*").Id("threader")).Func().Params(jen.Op("*").Id("Interpreter")).Block(
					jen.Id("inst").Op(":=").Qual("github.com/siyul-park/minivm/instr", "Instruction").Call(jen.Id("c").Dot("code").Index(jen.Id("c").Dot("ip").Op(":"))),
					jen.Id("c").Dot("ip").Op("+=").Id("inst").Dot("Width").Call(),
					jen.Return(jen.Id("invalid")),
				),
			),
		),
	)
	file.Line()
}

func renderCompile(file *jen.File) {
	file.Func().Params(jen.Id("c").Op("*").Id("threader")).Id("Compile").Params(
		jen.Id("code").Index().Byte(),
		jen.Id("locals").Index().Qual("github.com/siyul-park/minivm/types", "Kind"),
		jen.Id("captures").Index().Qual("github.com/siyul-park/minivm/types", "Kind"),
	).Index().Func().Params(jen.Op("*").Id("Interpreter")).Block(
		jen.Id("c").Dot("code").Op("=").Id("code"),
		jen.Id("c").Dot("locals").Op("=").Id("locals"),
		jen.Id("c").Dot("captures").Op("=").Id("captures"),
		jen.Id("c").Dot("ip").Op("=").Lit(0),
		jen.Id("compiled").Op(":=").Make(jen.Index().Func().Params(jen.Op("*").Id("Interpreter")), jen.Len(jen.Id("code"))),
		jen.For(jen.Id("c").Dot("ip").Op("<").Len(jen.Id("code"))).Block(
			jen.Id("ip").Op(":=").Id("c").Dot("ip"),
			jen.If(jen.Op("!").Id("c").Dot("exact")).Block(
				jen.If(jen.Id("compile").Op(":=").Id("fusions").Index(jen.Id("code").Index(jen.Id("ip"))), jen.Id("compile").Op("!=").Nil()).Block(
					jen.If(jen.Id("fn").Op(":=").Id("compile").Call(jen.Id("c")), jen.Id("fn").Op("!=").Nil()).Block(
						jen.Id("compiled").Index(jen.Id("ip")).Op("=").Id("fn"),
						jen.Continue(),
					),
				),
			),
			jen.Id("compiled").Index(jen.Id("ip")).Op("=").Id("threaded").Index(jen.Id("code").Index(jen.Id("ip"))).Call(jen.Id("c")),
		),
		jen.For(jen.Id("ip").Op(":=").Lit(0), jen.Id("ip").Op("<").Len(jen.Id("code")), jen.Id("ip").Op("++")).Block(
			jen.If(jen.Id("compiled").Index(jen.Id("ip")).Op("==").Nil()).Block(
				jen.Id("compiled").Index(jen.Id("ip")).Op("=").Id("invalid"),
			),
		),
		jen.Return(jen.Id("compiled")),
	)
}

func renderFusionTest(rules []rule) ([]byte, error) {
	var cases strings.Builder
	for _, rule := range rules {
		kind, err := testRuleKind(rule)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&cases, "\t{name: %q, ops: []instr.Opcode{%s}, kind: types.%s},\n", testRuleName(rule), testOpcodes(rule.pattern), kind)
	}
	return format.Source([]byte(fmt.Sprintf(`// Code generated by internal/cmd/genfusion; DO NOT EDIT.

package interp

import (
	"context"
	"fmt"
	"testing"

	"github.com/siyul-park/minivm/instr"
	"github.com/siyul-park/minivm/program"
	"github.com/siyul-park/minivm/types"
	"github.com/stretchr/testify/require"
)

func TestFusionRules(t *testing.T) {
	type state struct {
		err   string
		ip    int
		bp    int
		fp    int
		sp    int
		stack []types.Boxed
		rc    []int
		free  []int
	}
	tests := []struct {
		name string
		ops  []instr.Opcode
		kind types.Kind
	}{
%s	}
	instruction := func(op instr.Opcode) instr.Instruction {
		switch op {
		case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.BR_IF:
			return instr.New(op, 0)
		case instr.I32_CONST, instr.I64_CONST, instr.F32_CONST, instr.F64_CONST:
			return instr.New(op, 2)
		default:
			return instr.New(op)
		}
	}
	constant := func(kind types.Kind) ([]types.Boxed, []types.Value, []bool) {
		switch kind {
		case types.KindI32:
			return []types.Boxed{types.BoxI32(2)}, nil, nil
		case types.KindI64:
			return []types.Boxed{types.BoxI64(2)}, nil, nil
		case types.KindF32:
			return []types.Boxed{types.BoxF32(2)}, nil, nil
		case types.KindF64:
			return []types.Boxed{types.BoxF64(2)}, nil, nil
		default:
			fn := types.NewFunctionBuilder(&types.FunctionType{}).MustBuild()
			return []types.Boxed{types.BoxRef(0)}, []types.Value{fn}, []bool{false}
		}
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			code := make([]instr.Instruction, len(tt.ops))
			for i, op := range tt.ops {
				code[i] = instruction(op)
			}
			prog := program.New(code)
			c := threader{code: prog.Code}
			var index instr.Opcode
			upval := false
			for _, op := range tt.ops {
				switch op {
				case instr.LOCAL_GET:
					c.locals = []types.Kind{tt.kind}
				case instr.GLOBAL_GET:
					c.globals = []types.Kind{tt.kind}
				case instr.UPVAL_GET:
					c.captures = []types.Kind{tt.kind}
					upval = true
				case instr.CONST_GET:
					c.constants, c.heap, c.coros = constant(tt.kind)
				case instr.ARRAY_GET, instr.STRUCT_GET:
					index = op
				}
			}
			compile := fusions[c.code[c.ip]]
			require.NotNil(t, compile)
			require.NotNil(t, compile(&c))

			var typ types.Type = types.TypeRef
			var value types.Value = types.Null
			boxed := types.BoxedNull
			switch tt.kind {
			case types.KindI32:
				typ, value = types.TypeI32, types.I32(2)
				boxed = types.BoxI32(2)
			case types.KindI64:
				typ, value = types.TypeI64, types.I64(2)
				boxed = types.BoxI64(2)
			case types.KindF32:
				typ, value = types.TypeF32, types.F32(2)
				boxed = types.BoxF32(2)
			case types.KindF64:
				typ, value = types.TypeF64, types.F64(2)
				boxed = types.BoxF64(2)
			default:
				value = types.NewFunctionBuilder(&types.FunctionType{}).Emit(instr.New(instr.RETURN)).MustBuild()
			}
			prog = program.New(code,
				program.WithLocals(typ),
				program.WithGlobals(typ),
				program.WithConstants(value),
			)
			if upval {
				seed := instr.New(instr.REF_NULL)
				switch tt.kind {
				case types.KindI32:
					seed = instr.New(instr.I32_CONST, 2)
				case types.KindI64:
					seed = instr.New(instr.I64_CONST, 2)
				case types.KindF32:
					seed = instr.New(instr.F32_CONST, 2)
				case types.KindF64:
					seed = instr.New(instr.F64_CONST, 2)
				}
				body := []instr.Instruction{seed, instr.New(instr.LOCAL_SET, 0)}
				body = append(body, code...)
				body = append(body, instr.New(instr.RETURN))
				fn := types.NewFunctionBuilder(&types.FunctionType{}).
					WithLocals(typ).
					WithCaptures(typ).
					Emit(body...).
					MustBuild()
				prog = program.New([]instr.Instruction{
					instr.New(instr.CONST_GET, 0),
					instr.New(instr.CONST_GET, 1),
					instr.New(instr.CLOSURE_NEW),
					instr.New(instr.CALL),
				},
					program.WithLocals(typ),
					program.WithGlobals(typ),
					program.WithConstants(value, fn),
				)
			}

			exact := New(prog, WithTick(1), WithThreshold(-1))
			defer exact.Close()
			require.NoError(t, exact.SetLocal(0, boxed))
			require.NoError(t, exact.SetGlobal(0, boxed))
			switch index {
			case instr.ARRAY_GET:
				require.NoError(t, exact.Push(types.NewArray(types.NewArrayType(types.TypeI32), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			case instr.STRUCT_GET:
				require.NoError(t, exact.Push(types.NewStruct(types.NewStructType(
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
				), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			}
			exactErr := exact.Run(context.Background())
			exactState := state{
				err:   fmt.Sprint(exactErr),
				ip:    exact.fr.ip,
				bp:    exact.fr.bp,
				fp:    exact.fp,
				sp:    exact.sp,
				stack: append([]types.Boxed(nil), exact.stack[:exact.sp]...),
				rc:    append([]int(nil), exact.rc...),
				free:  append([]int(nil), exact.free...),
			}

			fused := New(prog, WithThreshold(-1))
			defer fused.Close()
			require.NoError(t, fused.SetLocal(0, boxed))
			require.NoError(t, fused.SetGlobal(0, boxed))
			switch index {
			case instr.ARRAY_GET:
				require.NoError(t, fused.Push(types.NewArray(types.NewArrayType(types.TypeI32), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			case instr.STRUCT_GET:
				require.NoError(t, fused.Push(types.NewStruct(types.NewStructType(
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
				), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			}
			fusedErr := fused.Run(context.Background())
			fusedState := state{
				err:   fmt.Sprint(fusedErr),
				ip:    fused.fr.ip,
				bp:    fused.fr.bp,
				fp:    fused.fp,
				sp:    fused.sp,
				stack: append([]types.Boxed(nil), fused.stack[:fused.sp]...),
				rc:    append([]int(nil), fused.rc...),
				free:  append([]int(nil), fused.free...),
			}
			require.Equal(t, exactState, fusedState)
		})
	}
}
`, cases.String())))
}

func testRuleKind(rule rule) (string, error) {
	for i := len(rule.pattern) - 1; i >= 0; i-- {
		switch rule.pattern[i].op {
		case instr.ARRAY_GET, instr.STRUCT_GET:
			return "KindI32", nil
		}
		if kind, ok := numericKind(rule.pattern[i].op); ok {
			return "Kind" + kind, nil
		}
	}
	for _, operation := range rule.pattern {
		switch operation.op {
		case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.REF_NULL, instr.DUP, instr.CALL, instr.RETURN_CALL, instr.CLOSURE_NEW:
			return "KindRef", nil
		}
	}
	return "", fmt.Errorf("no test kind for %s", rule.pattern.key())
}

func testRuleName(rule rule) string {
	parts := make([]string, len(rule.pattern))
	for i, operation := range rule.pattern {
		parts[i] = operationName(operation)
	}
	return strings.Join(parts, "/")
}

func operationName(operation operation) string {
	name := instr.TypeOf(operation.op).Mnemonic
	if operation.guard == nil {
		return name
	}
	if operation.guard.negations == 1 {
		return name + "[not " + operation.guard.typeOf.String() + "]"
	}
	return name + "[" + operation.guard.typeOf.String() + "]"
}

func testOpcodes(pattern pattern) string {
	parts := make([]string, len(pattern))
	for i, operation := range pattern {
		parts[i] = "instr." + opcodeName(operation.op)
	}
	return strings.Join(parts, ", ")
}

func renderPattern(pattern pattern) jen.Code {
	total := pattern.width()
	condition := jen.Id("start").Op("+").Lit(total).Op("<=").Len(jen.Id("c").Dot("code"))
	offset := width(pattern[0].op)
	for _, operation := range pattern[1:] {
		condition = condition.Op("&&").Qual("github.com/siyul-park/minivm/instr", "Opcode").Call(jen.Id("c").Dot("code").Index(add(jen.Id("start"), offset))).Op("==").Qual("github.com/siyul-park/minivm/instr", opcodeName(operation.op))
		offset += width(operation.op)
	}
	return condition
}

func opcodeName(op instr.Opcode) string {
	return strings.ToUpper(strings.ReplaceAll(instr.TypeOf(op).Mnemonic, ".", "_"))
}

func renderFusionRule(value rule, total int, label string) ([]jen.Code, error) {
	consumer := value.pattern[len(value.pattern)-1].op
	if consumer == instr.BR_IF && len(value.pattern) > 1 {
		consumer = value.pattern[len(value.pattern)-2].op
	}
	lowering := lowerings[consumer]
	if lowering == nil {
		return nil, fmt.Errorf("no lowering for %s", instr.TypeOf(consumer).Mnemonic)
	}
	l := &lower{rule: &value, total: total, label: label}
	lowering(l)
	return l.code, l.err
}

func renderFusions(rules []rule) (jen.Code, error) {
	var groups [256][]rule
	for _, rule := range rules {
		groups[rule.pattern[0].op] = append(groups[rule.pattern[0].op], rule)
	}

	var entries []jen.Code
	for opcode, rules := range groups {
		if len(rules) == 0 {
			continue
		}
		body := []jen.Code{jen.Id("start").Op(":=").Id("c").Dot("ip")}
		for index, rule := range rules {
			label := fmt.Sprintf("l%d", index)
			total := rule.pattern.width()
			statements, err := renderFusionRule(rule, total, label)
			if err != nil {
				return nil, err
			}
			if rule.pattern[len(rule.pattern)-1].op == instr.BR_IF {
				offset := total - width(instr.BR_IF) + 1
				statements = append([]jen.Code{jen.Id("offset").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseI16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(offset))}, statements...)
			}
			body = append(body, jen.If(jen.Op("!").Parens(renderPattern(rule.pattern))).Block(jen.Goto().Id(label)))
			body = append(body, jen.Block(statements...))
			body = append(body, jen.Id(label).Op(":"))
		}
		body = append(body, jen.Return(jen.Nil()))
		entries = append(entries, jen.Qual("github.com/siyul-park/minivm/instr", opcodeName(instr.Opcode(opcode))).Op(":").Func().Params(jen.Id("c").Op("*").Id("threader")).Func().Params(jen.Op("*").Id("Interpreter")).Block(body...))
	}

	table := jen.Index(jen.Lit(256)).Func().Params(jen.Id("c").Op("*").Id("threader")).Func().Params(jen.Op("*").Id("Interpreter"))
	return table.ValuesFunc(func(group *jen.Group) {
		for _, entry := range entries {
			group.Line().Add(entry)
		}
	}), nil
}
