package main

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/siyul-park/minivm/instr"
)

type output struct {
	path string
	data []byte
}

type access struct {
	pre   []jen.Code
	check []jen.Code
	load  []jen.Code
	push  []jen.Code
	width int
}

func generate() ([]output, error) {
	rules, err := expand(declarations()...)
	if err != nil {
		return nil, err
	}
	if err := validate(rules); err != nil {
		return nil, err
	}
	data, err := renderThreaded(rules)
	if err != nil {
		return nil, err
	}
	test, err := renderThreadedTest(rules)
	if err != nil {
		return nil, err
	}
	outputs := []output{
		{path: "docs/fusion.md", data: renderDocs(rules)},
		{path: "interp/fusion_gen.go", data: data},
		{path: "interp/fusion_gen_test.go", data: test},
	}
	return outputs, nil
}

func renderDocs(rules []rule) []byte {
	counts := make(map[string]int)
	for _, rule := range rules {
		counts[operationName(rule.pattern[0])]++
	}
	sources := make([]string, 0, len(counts))
	for source := range counts {
		sources = append(sources, source)
	}
	slices.Sort(sources)
	var matrix strings.Builder
	for _, source := range sources {
		fmt.Fprintf(&matrix, "| `%s` | %d |\n", source, counts[source])
	}
	fmt.Fprintf(&matrix, "| Total | %d |\n", len(rules))

	doc := fmt.Sprintf(`<!-- Code generated by internal/cmd/genfusion; DO NOT EDIT. -->

# Fusion

How minivm generates producer-consumer fusion for the threaded interpreter.

## When to Read

Read this before changing threaded fusion rules, generated handlers, lookahead, or ref ownership inside a fused sequence.

## Source of Truth

| Concern | File |
|---|---|
| Rule declarations, validation, and this document | §internal/cmd/genfusion/§ |
| Threaded generated handlers | §interp/fusion_gen.go§ |
| ARM64 trace lowering | §interp/jit_arm64.go§ |
| Standalone semantics | §interp/threaded.go§ |
| Opcode metadata | §instr/type.go§ |

## Model

Fusion rules are passive generator data for the threaded interpreter. Products expand into concrete opcode patterns before validation and rendering. Generated matchers use opcode widths from §instr.Type§, choose the longest applicable specialization, and dispatch directly to closed renderers. Product identities and runtime match/action objects do not survive generation.

Standalone opcode execution is the semantic oracle. Fusion preserves results, stack and frame state, instruction pointers, traps and check order, control flow, and final ownership. NOP run compaction remains local to the NOP handler because it is dispatch compaction, not semantic producer-consumer fusion.

## Generated Support Matrix

Counts come from normalized concrete rules after product expansion.

| First operation | Threaded |
|---|---:|
%s
Rules cover ref consumption, constant calls and closure creation, numeric operations and comparisons, conditional branches, and constant aggregate indexes. Integer division and remainder use direct fused handlers that preserve standalone trap IP and stack state.

## Threaded Compilation

Threading calls one generated fusion matcher before standalone opcode dispatch. Matcher preflight uses a local cursor and mutates nothing on a miss. A match installs one direct handler and advances compile-time IP by only the first opcode width. Absorbed offsets are still threaded separately, so branches into them execute standalone handlers. Exact threading disables fusion.

Compile-time specialization resolves operands, declared slot kinds, constants, heap objects, and cached coroutine metadata. Final handlers do not dispatch source functions, decode operands, inspect concrete heap types, or rescan bytecode for yields.

## JIT Separation

The generator does not emit architecture-specific code or tests. ARM64 trace fusion is ordinary lowering code in §interp/jit_arm64.go§, next to the standalone operations it combines. This keeps JIT selection, guards, symbolic stack mutation, and emitted instructions in one implementation instead of mirroring them through generator metadata.

Threaded declarations are not a cross-backend registry. An ARM64 specialization is added only when trace lowering benefits from it and is tested through JIT behavior.

## Ref Ownership

RC elimination is local and proven by each closed renderer. A slot or constant source may be borrowed only when its ref is fully consumed inside the fused sequence. §REF_NULL§ may omit its balanced retain/release, and §DUP§ may avoid creating temporary ownership when its duplicate is consumed locally.

Borrowed refs never enter the VM stack, frame/global/upvalue storage, calls, yields, or control-flow boundaries. String constants remain standalone because loading interns them. Declared I64 slots retain numeric ownership rules even when a large current value is heap-promoted.

## Generation and Checks

§make generate§ refreshes threaded generated files and this document. Generated output has stable ordering and contains no timestamp or absolute path. §make check-generated§ reports stale output without rewriting it. §make check§ also verifies module tidiness, formatting, vet, race tests, native build, and Linux ARM64 production/test compilation.

## Maintenance Notes

Add a threaded pattern only when every expanded concrete combination has one supported renderer and locally obvious ownership. Reject ambiguous, shadowed, variable-width, stack-inconsistent, or ownership-unsafe patterns during generation. Do not add callbacks, code strings, ownership annotations, synthetic opcodes, runtime rule objects, or architecture-specific output.

Keep ARM64 trace fusion hand-written in §interp/jit_arm64.go§. Do not add architecture flags or renderers to this generator.

## Related Docs

- §docs/jit-internals.md§ - trace lowering, side exits, and ARM64 contracts
- §docs/memory-model.md§ - refcounts, heap roots, and ownership invariants
- §docs/instruction-set.md§ - opcode semantics and operand widths
`, matrix.String())
	return []byte(strings.ReplaceAll(doc, "§", "`"))
}

func renderThreadedTest(rules []rule) ([]byte, error) {
	var cases strings.Builder
	for _, rule := range rules {
		kind, err := testRuleKind(rule)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&cases, "\t{name: %q, ops: []instr.Opcode{%s}, kind: types.%s},\n", testRuleName(rule), testOpcodes(rule.pattern), kind)
	}
	return format.Source([]byte(fmt.Sprintf(`// Code generated by internal/cmd/genfusion; DO NOT EDIT.

package interp

import (
	"context"
	"fmt"
	"testing"

	"github.com/siyul-park/minivm/instr"
	"github.com/siyul-park/minivm/program"
	"github.com/siyul-park/minivm/types"
	"github.com/stretchr/testify/require"
)

func testFusionRules(t *testing.T) {
	type state struct {
		err   string
		ip    int
		bp    int
		fp    int
		sp    int
		stack []types.Boxed
		rc    []int
		free  []int
	}
	tests := []struct {
		name string
		ops  []instr.Opcode
		kind types.Kind
	}{
%s	}
	instruction := func(op instr.Opcode) instr.Instruction {
		switch op {
		case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.BR_IF:
			return instr.New(op, 0)
		case instr.I32_CONST, instr.I64_CONST, instr.F32_CONST, instr.F64_CONST:
			return instr.New(op, 2)
		default:
			return instr.New(op)
		}
	}
	constant := func(kind types.Kind) ([]types.Boxed, []types.Value, []bool) {
		switch kind {
		case types.KindI32:
			return []types.Boxed{types.BoxI32(2)}, nil, nil
		case types.KindI64:
			return []types.Boxed{types.BoxI64(2)}, nil, nil
		case types.KindF32:
			return []types.Boxed{types.BoxF32(2)}, nil, nil
		case types.KindF64:
			return []types.Boxed{types.BoxF64(2)}, nil, nil
		default:
			fn := types.NewFunctionBuilder(&types.FunctionType{}).MustBuild()
			return []types.Boxed{types.BoxRef(0)}, []types.Value{fn}, []bool{false}
		}
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			code := make([]instr.Instruction, len(tt.ops))
			for i, op := range tt.ops {
				code[i] = instruction(op)
			}
			prog := program.New(code)
			c := threader{code: prog.Code}
			var index instr.Opcode
			upval := false
			for _, op := range tt.ops {
				switch op {
				case instr.LOCAL_GET:
					c.locals = []types.Kind{tt.kind}
				case instr.GLOBAL_GET:
					c.globals = []types.Kind{tt.kind}
				case instr.UPVAL_GET:
					c.captures = []types.Kind{tt.kind}
					upval = true
				case instr.CONST_GET:
					c.constants, c.heap, c.coros = constant(tt.kind)
				case instr.ARRAY_GET, instr.STRUCT_GET:
					index = op
				}
			}
			require.NotNil(t, c.fusion())

			var typ types.Type = types.TypeRef
			var value types.Value = types.Null
			boxed := types.BoxedNull
			switch tt.kind {
			case types.KindI32:
				typ, value = types.TypeI32, types.I32(2)
				boxed = types.BoxI32(2)
			case types.KindI64:
				typ, value = types.TypeI64, types.I64(2)
				boxed = types.BoxI64(2)
			case types.KindF32:
				typ, value = types.TypeF32, types.F32(2)
				boxed = types.BoxF32(2)
			case types.KindF64:
				typ, value = types.TypeF64, types.F64(2)
				boxed = types.BoxF64(2)
			default:
				value = types.NewFunctionBuilder(&types.FunctionType{}).Emit(instr.New(instr.RETURN)).MustBuild()
			}
			prog = program.New(code,
				program.WithLocals(typ),
				program.WithGlobals(typ),
				program.WithConstants(value),
			)
			if upval {
				seed := instr.New(instr.REF_NULL)
				switch tt.kind {
				case types.KindI32:
					seed = instr.New(instr.I32_CONST, 2)
				case types.KindI64:
					seed = instr.New(instr.I64_CONST, 2)
				case types.KindF32:
					seed = instr.New(instr.F32_CONST, 2)
				case types.KindF64:
					seed = instr.New(instr.F64_CONST, 2)
				}
				body := []instr.Instruction{seed, instr.New(instr.LOCAL_SET, 0)}
				body = append(body, code...)
				body = append(body, instr.New(instr.RETURN))
				fn := types.NewFunctionBuilder(&types.FunctionType{}).
					WithLocals(typ).
					WithCaptures(typ).
					Emit(body...).
					MustBuild()
				prog = program.New([]instr.Instruction{
					instr.New(instr.CONST_GET, 0),
					instr.New(instr.CONST_GET, 1),
					instr.New(instr.CLOSURE_NEW),
					instr.New(instr.CALL),
				},
					program.WithLocals(typ),
					program.WithGlobals(typ),
					program.WithConstants(value, fn),
				)
			}

			exact := New(prog, WithTick(1), WithThreshold(-1))
			defer exact.Close()
			require.NoError(t, exact.SetLocal(0, boxed))
			require.NoError(t, exact.SetGlobal(0, boxed))
			switch index {
			case instr.ARRAY_GET:
				require.NoError(t, exact.Push(types.NewArray(types.NewArrayType(types.TypeI32), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			case instr.STRUCT_GET:
				require.NoError(t, exact.Push(types.NewStruct(types.NewStructType(
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
				), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			}
			exactErr := exact.Run(context.Background())
			exactState := state{
				err:   fmt.Sprint(exactErr),
				ip:    exact.fr.ip,
				bp:    exact.fr.bp,
				fp:    exact.fp,
				sp:    exact.sp,
				stack: append([]types.Boxed(nil), exact.stack[:exact.sp]...),
				rc:    append([]int(nil), exact.rc...),
				free:  append([]int(nil), exact.free...),
			}

			fused := New(prog, WithThreshold(-1))
			defer fused.Close()
			require.NoError(t, fused.SetLocal(0, boxed))
			require.NoError(t, fused.SetGlobal(0, boxed))
			switch index {
			case instr.ARRAY_GET:
				require.NoError(t, fused.Push(types.NewArray(types.NewArrayType(types.TypeI32), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			case instr.STRUCT_GET:
				require.NoError(t, fused.Push(types.NewStruct(types.NewStructType(
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
					types.NewStructField(types.TypeI32),
				), types.BoxI32(0), types.BoxI32(1), types.BoxI32(2))))
			}
			fusedErr := fused.Run(context.Background())
			fusedState := state{
				err:   fmt.Sprint(fusedErr),
				ip:    fused.fr.ip,
				bp:    fused.fr.bp,
				fp:    fused.fp,
				sp:    fused.sp,
				stack: append([]types.Boxed(nil), fused.stack[:fused.sp]...),
				rc:    append([]int(nil), fused.rc...),
				free:  append([]int(nil), fused.free...),
			}
			require.Equal(t, exactState, fusedState)
		})
	}
}
`, cases.String())))
}

func testRuleKind(rule rule) (string, error) {
	for i := len(rule.pattern) - 1; i >= 0; i-- {
		switch rule.pattern[i].op {
		case instr.ARRAY_GET, instr.STRUCT_GET:
			return "KindI32", nil
		}
		if kind, ok := numericKind(rule.pattern[i].op); ok {
			return "Kind" + kind, nil
		}
	}
	for _, operation := range rule.pattern {
		switch operation.op {
		case instr.LOCAL_GET, instr.GLOBAL_GET, instr.UPVAL_GET, instr.CONST_GET, instr.REF_NULL, instr.DUP, instr.CALL, instr.RETURN_CALL, instr.CLOSURE_NEW:
			return "KindRef", nil
		}
	}
	return "", fmt.Errorf("no test kind for %s", rule.pattern.key())
}

func testRuleName(rule rule) string {
	parts := make([]string, len(rule.pattern))
	for i, operation := range rule.pattern {
		parts[i] = operationName(operation)
	}
	return strings.Join(parts, "/")
}

func operationName(operation operation) string {
	name := instr.TypeOf(operation.op).Mnemonic
	if operation.guard == nil {
		return name
	}
	if operation.guard.negations == 1 {
		return name + "[not " + operation.guard.typeOf.String() + "]"
	}
	return name + "[" + operation.guard.typeOf.String() + "]"
}

func testOpcodes(pattern pattern) string {
	parts := make([]string, len(pattern))
	for i, operation := range pattern {
		parts[i] = "instr." + opcodeName(operation.op)
	}
	return strings.Join(parts, ", ")
}

// renderThreaded emits a small dispatcher, "fusion", that switches on the
// first opcode and delegates to one generated method per source opcode (for
// example "fusionLocalGet"). Splitting the handlers keeps each generated
// method a manageable size instead of one large multi-case switch.
func renderThreaded(rules []rule) ([]byte, error) {
	file := jen.NewFile("interp")
	file.HeaderComment("Code generated by internal/cmd/genfusion; DO NOT EDIT.")

	var groups [256][]rule
	for _, rule := range rules {
		groups[rule.pattern[0].op] = append(groups[rule.pattern[0].op], rule)
	}
	var opcodes []instr.Opcode
	for opcode, rules := range groups {
		if len(rules) > 0 {
			opcodes = append(opcodes, instr.Opcode(opcode))
		}
	}

	var cases []jen.Code
	for _, opcode := range opcodes {
		cases = append(cases, jen.Case(jen.Qual("github.com/siyul-park/minivm/instr", opcodeName(opcode))).Block(
			jen.Return(jen.Id("c").Dot(handler(opcode)).Call()),
		))
	}
	dispatch := []jen.Code{
		jen.Id("start").Op(":=").Id("c").Dot("ip"),
		jen.If(jen.Id("start").Op(">=").Len(jen.Id("c").Dot("code"))).Block(jen.Return(jen.Nil())),
		jen.Switch(jen.Qual("github.com/siyul-park/minivm/instr", "Opcode").Call(jen.Id("c").Dot("code").Index(jen.Id("start")))).Block(cases...),
		jen.Return(jen.Nil()),
	}
	file.Func().Params(jen.Id("c").Op("*").Id("threader")).Id("fusion").Params().Func().Params(jen.Op("*").Id("Interpreter")).Block(dispatch...)

	nextLabel := 0
	for _, opcode := range opcodes {
		body := []jen.Code{jen.Id("start").Op(":=").Id("c").Dot("ip")}
		for _, rule := range groups[opcode] {
			label := fmt.Sprintf("l%d", nextLabel)
			nextLabel++
			total := rule.pattern.width()
			statements, err := renderThreadedRule(rule, total, label)
			if err != nil {
				return nil, err
			}
			if rule.pattern[len(rule.pattern)-1].op == instr.BR_IF {
				offset := total - width(instr.BR_IF) + 1
				statements = append([]jen.Code{jen.Id("offset").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseI16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(offset))}, statements...)
			}
			body = append(body, jen.If(jen.Op("!").Parens(renderPattern(rule.pattern))).Block(jen.Goto().Id(label)))
			body = append(body, jen.Block(statements...))
			body = append(body, jen.Id(label).Op(":"))
		}
		body = append(body, jen.Return(jen.Nil()))
		file.Line()
		file.Func().Params(jen.Id("c").Op("*").Id("threader")).Id(handler(opcode)).Params().Func().Params(jen.Op("*").Id("Interpreter")).Block(body...)
	}
	return formatGenerated([]byte(file.GoString()))
}

// handler converts an opcode's mnemonic (for example "local.get")
// into the per-opcode dispatch method name (for example "fusionLocalGet").
func handler(op instr.Opcode) string {
	var name strings.Builder
	name.WriteString("fusion")
	for _, part := range strings.Split(opcodeName(op), "_") {
		if part == "" {
			continue
		}
		name.WriteString(strings.ToUpper(part[:1]))
		name.WriteString(strings.ToLower(part[1:]))
	}
	return name.String()
}

func renderThreadedRule(rule rule, total int, label string) ([]jen.Code, error) {
	last := rule.pattern[len(rule.pattern)-1].op
	consumer := last
	if last == instr.BR_IF && len(rule.pattern) > 1 {
		consumer = rule.pattern[len(rule.pattern)-2].op
	}
	if consumer == instr.CALL || consumer == instr.RETURN_CALL || consumer == instr.CLOSURE_NEW {
		return renderCall(rule, label)
	}
	if consumer == instr.DROP || consumer == instr.REF_IS_NULL {
		return renderRefFusion(rule, total, label)
	}
	if consumer == instr.ARRAY_GET || consumer == instr.STRUCT_GET {
		return renderThreadedIndex(rule, total, label)
	}
	if len(rule.pattern) == 2 && rule.pattern[0].op == instr.I32_CONST && last == instr.BR_IF {
		return renderI32ConstBranch(total), nil
	}
	if _, _, ok := numericConsumer(consumer); ok {
		return renderNumericFusion(rule, total, label)
	}
	return nil, fmt.Errorf("no threaded renderer for %s", instr.TypeOf(consumer).Mnemonic)
}

func renderI32ConstBranch(total int) []jen.Code {
	return []jen.Code{
		jen.Id("value").Op(":=").Add(immediate("I32", jen.Id("start"))),
		jen.Id("c").Dot("ip").Op("+=").Lit(width(instr.I32_CONST)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("i").Dot("branchIf").Call(jen.Id("value").Op("!=").Lit(0), jen.Id("offset"), jen.Lit(total)),
		)),
	}
}

func renderPattern(pattern pattern) jen.Code {
	total := pattern.width()
	condition := jen.Id("start").Op("+").Lit(total).Op("<=").Len(jen.Id("c").Dot("code"))
	offset := width(pattern[0].op)
	for _, operation := range pattern[1:] {
		condition = condition.Op("&&").Qual("github.com/siyul-park/minivm/instr", "Opcode").Call(jen.Id("c").Dot("code").Index(add(jen.Id("start"), offset))).Op("==").Qual("github.com/siyul-park/minivm/instr", opcodeName(operation.op))
		offset += width(operation.op)
	}
	return condition
}

func opcodeName(op instr.Opcode) string {
	return strings.ToUpper(strings.ReplaceAll(instr.TypeOf(op).Mnemonic, ".", "_"))
}

func (p pattern) width() int {
	total := 0
	for _, operation := range p {
		total += width(operation.op)
	}
	return total
}

// renderCall emits compile-time target resolution followed by target-specific
// final handlers. Source semantics are repeated in each handler; generated
// code has no source callback, runtime target switch, or yield scan.
func renderCall(rule rule, label string) ([]jen.Code, error) {
	if len(rule.pattern) != 2 || rule.pattern[0].op != instr.CONST_GET {
		return nil, fmt.Errorf("unsupported constant call pattern")
	}
	consumer := rule.pattern[1].op
	if consumer != instr.CALL && consumer != instr.RETURN_CALL && consumer != instr.CLOSURE_NEW {
		return nil, fmt.Errorf("unsupported constant call consumer %s", instr.TypeOf(consumer).Mnemonic)
	}

	code := []jen.Code{
		jen.Id("idx").Op(":=").Int().Parens(jen.Id("uint16").Parens(jen.Id("c").Dot("code").Index(jen.Id("c").Dot("ip").Op("+").Lit(1))).Op("|").Id("uint16").Parens(jen.Id("c").Dot("code").Index(jen.Id("c").Dot("ip").Op("+").Lit(2))).Op("<<").Lit(8)),
		jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
		jen.Id("boxed").Op(":=").Id("c").Dot("constants").Index(jen.Id("idx")),
		jen.If(jen.Id("boxed").Dot("Kind").Call().Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(reject(label)),
		jen.Id("addr").Op(":=").Id("boxed").Dot("Ref").Call(),
		jen.If(jen.Id("addr").Op("<").Lit(0).Op("||").Id("addr").Op(">=").Len(jen.Id("c").Dot("heap"))).Block(reject(label)),
	}

	switch consumer {
	case instr.CALL:
		code = append(code, renderCallSwitch(false, label))
	case instr.RETURN_CALL:
		code = append(code, renderCallSwitch(true, label))
	case instr.CLOSURE_NEW:
		code = append(code, renderClosureNew(label))
	}
	return code, nil
}

func renderCallSwitch(tail bool, label string) jen.Code {
	return jen.Switch(jen.Id("fn").Op(":=").Id("c").Dot("heap").Index(jen.Id("addr")).Assert(jen.Type())).Block(
		jen.Case(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")).Block(renderFunctionCall(tail, label)...),
		jen.Case(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Closure")).Block(renderClosureCall(tail, label)...),
		jen.Case(jen.Op("*").Id("HostFunction")).Block(renderHostCall(tail)...),
		jen.Default().Block(reject(label)),
	)
}

func renderFunctionCall(tail bool, label string) []jen.Code {
	guard := jen.If(jen.Id("addr").Op("<").Len(jen.Id("c").Dot("coros")).Op("&&").Id("c").Dot("coros").Index(jen.Id("addr"))).Block(reject(label))
	if tail {
		return append([]jen.Code{guard}, renderTailFrame(jen.Id("addr"), jen.Nil(), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("fn").Dot("Locals")))...)
	}
	return append([]jen.Code{guard}, renderFrameCall(jen.Id("addr"), jen.Nil(), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("fn").Dot("Locals")))...)
}

func renderClosureCall(tail bool, label string) []jen.Code {
	preflight := []jen.Code{
		jen.Id("tmpl").Op(",").Id("ok").Op(":=").Id("c").Dot("heap").Index(jen.Id("fn").Dot("Fn")).Assert(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")),
		jen.If(jen.Op("!").Id("ok")).Block(reject(label)),
		jen.If(jen.Int().Parens(jen.Id("fn").Dot("Fn")).Op("<").Len(jen.Id("c").Dot("coros")).Op("&&").Id("c").Dot("coros").Index(jen.Id("fn").Dot("Fn"))).Block(reject(label)),
	}
	if tail {
		return append(preflight, renderTailFrame(jen.Int().Parens(jen.Id("fn").Dot("Fn")), jen.Id("fn").Dot("Upvals"), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("tmpl").Dot("Locals")))...)
	}
	return append(preflight, renderFrameCall(jen.Int().Parens(jen.Id("fn").Dot("Fn")), jen.Id("fn").Dot("Upvals"), jen.Id("addr"), jen.Id("fn").Dot("Typ"), jen.Len(jen.Id("tmpl").Dot("Locals")))...)
}

func renderTailFrame(addr, upvals, ref, typ, locals jen.Code) []jen.Code {
	return []jen.Code{
		jen.Id("params").Op(":=").Len(jen.Add(typ).Dot("Params")),
		jen.Id("returns").Op(":=").Len(jen.Add(typ).Dot("Returns")),
		jen.Id("locals").Op(":=").Add(locals),
		jen.Id("c").Dot("ip").Op("+=").Lit(3),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			overflow(),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("fp").Op("==").Lit(1)).Block(
				jen.If(jen.Id("i").Dot("fp").Op("==").Len(jen.Id("i").Dot("frames"))).Block(jen.Panic(jen.Id("ErrFrameOverflow"))),
				jen.If(jen.Id("i").Dot("sp").Op("+").Id("locals").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
				jen.If(jen.Id("locals").Op(">").Lit(0)).Block(jen.Clear(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op(":").Id("i").Dot("sp").Op("+").Id("locals")))),
				jen.Id("f").Op(":=").Op("&").Id("i").Dot("frames").Index(jen.Id("i").Dot("fp")),
				jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Add(addr)),
				jen.Id("f").Dot("upvals").Op("=").Add(upvals),
				jen.Id("f").Dot("addr").Op("=").Add(addr),
				jen.Id("f").Dot("ref").Op("=").Add(ref),
				jen.Id("f").Dot("bp").Op("=").Id("i").Dot("sp").Op("-").Id("params"),
				jen.Id("f").Dot("returns").Op("=").Id("returns"),
				jen.Id("f").Dot("release").Op("=").False(),
				jen.Id("f").Dot("coro").Op("=").Lit(0),
				jen.Id("i").Dot("sp").Op("=").Id("f").Dot("bp").Op("+").Id("params").Op("+").Id("locals"),
				jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
				jen.Id("i").Dot("fp").Op("++"),
				jen.Id("i").Dot("fr").Op("=").Id("f"),
				jen.Return(),
			),
			jen.Id("f").Op(":=").Id("i").Dot("fr"),
			jen.Id("base").Op(":=").Id("f").Dot("bp"),
			jen.If(jen.Id("base").Op("+").Id("params").Op("+").Id("locals").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Copy(jen.Id("i").Dot("stack").Index(jen.Id("base").Op(":").Id("base").Op("+").Id("params")), jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("params").Op(":").Id("i").Dot("sp"))),
			jen.If(jen.Id("f").Dot("release")).Block(jen.Id("i").Dot("release").Call(jen.Id("f").Dot("ref"))),
			jen.If(jen.Id("locals").Op(">").Lit(0)).Block(jen.Clear(jen.Id("i").Dot("stack").Index(jen.Id("base").Op("+").Id("params").Op(":").Id("base").Op("+").Id("params").Op("+").Id("locals")))),
			jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Add(addr)),
			jen.Id("f").Dot("upvals").Op("=").Add(upvals),
			jen.Id("f").Dot("addr").Op("=").Add(addr),
			jen.Id("f").Dot("ref").Op("=").Add(ref),
			jen.Id("f").Dot("ip").Op("=").Lit(0),
			jen.Id("f").Dot("returns").Op("=").Id("returns"),
			jen.Id("f").Dot("release").Op("=").False(),
			jen.Id("f").Dot("coro").Op("=").Lit(0),
			jen.Id("i").Dot("sp").Op("=").Id("base").Op("+").Id("params").Op("+").Id("locals"),
		)),
	}
}

func renderFrameCall(addr, upvals, ref, typ, locals jen.Code) []jen.Code {
	return []jen.Code{
		jen.Id("params").Op(":=").Len(jen.Add(typ).Dot("Params")),
		jen.Id("returns").Op(":=").Len(jen.Add(typ).Dot("Returns")),
		jen.Id("locals").Op(":=").Add(locals),
		jen.Id("c").Dot("ip").Op("+=").Lit(3),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			overflow(),
			jen.If(jen.Id("i").Dot("fp").Op("==").Len(jen.Id("i").Dot("frames"))).Block(jen.Panic(jen.Id("ErrFrameOverflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("+").Id("locals").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.If(jen.Id("locals").Op(">").Lit(0)).Block(jen.Clear(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op(":").Id("i").Dot("sp").Op("+").Id("locals")))),
			jen.Id("f").Op(":=").Op("&").Id("i").Dot("frames").Index(jen.Id("i").Dot("fp")),
			jen.Id("f").Dot("code").Op("=").Id("i").Dot("code").Index(jen.Add(addr)),
			jen.Id("f").Dot("upvals").Op("=").Add(upvals),
			jen.Id("f").Dot("addr").Op("=").Add(addr),
			jen.Id("f").Dot("ref").Op("=").Add(ref),
			jen.Id("f").Dot("ip").Op("=").Lit(0),
			jen.Id("f").Dot("bp").Op("=").Id("i").Dot("sp").Op("-").Id("params"),
			jen.Id("f").Dot("returns").Op("=").Id("returns"),
			jen.Id("f").Dot("release").Op("=").False(),
			jen.Id("f").Dot("coro").Op("=").Lit(0),
			jen.Id("i").Dot("sp").Op("=").Id("f").Dot("bp").Op("+").Id("params").Op("+").Id("locals"),
			jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
			jen.Id("i").Dot("fp").Op("++"),
			jen.Id("i").Dot("fr").Op("=").Id("f"),
		)),
	}
}

func renderHostCall(tail bool) []jen.Code {
	body := []jen.Code{
		jen.Id("params").Op(":=").Len(jen.Id("fn").Dot("Typ").Dot("Params")),
		jen.Id("returns").Op(":=").Len(jen.Id("fn").Dot("Typ").Dot("Returns")),
		jen.Id("c").Dot("ip").Op("+=").Lit(3),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			overflow(),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("+").Id("returns").Op("-").Id("params").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("args").Op(":=").Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("params").Op(":").Id("i").Dot("sp")),
			jen.Id("out").Op(",").Id("err").Op(":=").Id("fn").Dot("Fn").Call(jen.Id("i"), jen.Id("args")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(jen.Panic(jen.Id("err"))),
			jen.Id("i").Dot("releaseArgs").Call(jen.Id("args"), jen.Id("out")),
			jen.Id("i").Dot("sp").Op("+=").Id("returns").Op("-").Id("params"),
			jen.Copy(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("returns").Op(":").Id("i").Dot("sp")), jen.Id("out")),
			jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
		)),
	}
	if tail {
		// Tail-host retirement remains explicit in the final handler; no
		// constant funcref was retained, so only arguments flow to releaseArgs.
		body[len(body)-1] = jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
			overflow(),
			jen.If(jen.Id("i").Dot("sp").Op("<").Id("params")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			jen.If(jen.Id("i").Dot("sp").Op("+").Id("returns").Op("-").Id("params").Op(">").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
			jen.Id("args").Op(":=").Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("params").Op(":").Id("i").Dot("sp")),
			jen.Id("out").Op(",").Id("err").Op(":=").Id("fn").Dot("Fn").Call(jen.Id("i"), jen.Id("args")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(jen.Panic(jen.Id("err"))),
			jen.Id("i").Dot("releaseArgs").Call(jen.Id("args"), jen.Id("out")),
			jen.Id("i").Dot("sp").Op("+=").Id("returns").Op("-").Id("params"),
			jen.Copy(jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("returns").Op(":").Id("i").Dot("sp")), jen.Id("out")),
			jen.If(jen.Id("i").Dot("fp").Op(">").Lit(1)).Block(jen.Id("i").Dot("ret").Call()),
		))
	}
	return body
}

func renderClosureNew(label string) jen.Code {
	return jen.Switch(jen.Id("fn").Op(":=").Id("c").Dot("heap").Index(jen.Id("addr")).Assert(jen.Type())).Block(
		jen.Case(jen.Op("*").Qual("github.com/siyul-park/minivm/types", "Function")).Block(
			jen.Id("captures").Op(":=").Len(jen.Id("fn").Dot("Captures")),
			jen.Id("c").Dot("ip").Op("+=").Lit(3),
			jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(
				overflow(),
				jen.If(jen.Id("i").Dot("sp").Op("<").Id("captures")).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
				jen.Id("upvals").Op(":=").Append(jen.Index().Qual("github.com/siyul-park/minivm/types", "Boxed").Values(), jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Id("captures").Op(":").Id("i").Dot("sp")).Op("...")),
				jen.Id("i").Dot("retain").Call(jen.Id("addr")),
				jen.Id("closure").Op(":=").Qual("github.com/siyul-park/minivm/types", "NewClosure").Call(jen.Id("fn").Dot("Typ"), jen.Qual("github.com/siyul-park/minivm/types", "Ref").Parens(jen.Id("addr")), jen.Id("upvals")),
				jen.Id("i").Dot("sp").Op("-=").Id("captures"),
				jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Qual("github.com/siyul-park/minivm/types", "BoxRef").Call(jen.Id("i").Dot("keep").Call(jen.Id("closure"))),
				jen.Id("i").Dot("sp").Op("++"),
				jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(4),
			)),
		),
		jen.Default().Block(reject(label)),
	)
}

func overflow() jen.Code {
	return jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow")))
}

func numericConsumer(op instr.Opcode) (int, string, bool) {
	if op == instr.I32_EQZ || op == instr.I64_EQZ {
		return 1, methodOf(op), true
	}
	for _, family := range families() {
		if slices.Contains(family.binary, op) || slices.Contains(family.compares, op) {
			return 2, methodOf(op), true
		}
	}
	return 0, "", false
}

func methodOf(op instr.Opcode) string {
	mnemonic := instr.TypeOf(op).Mnemonic
	prefix, suffix, _ := strings.Cut(mnemonic, ".")
	var name strings.Builder
	name.WriteString(prefix)
	for _, segment := range strings.Split(suffix, "_") {
		if segment == "" {
			continue
		}
		name.WriteString(strings.ToUpper(segment[:1]))
		name.WriteString(segment[1:])
	}
	return name.String()
}

func renderRefFusion(rule rule, total int, label string) ([]jen.Code, error) {
	pattern := rule.pattern
	if len(pattern) < 2 {
		return nil, fmt.Errorf("ref rule has no consumer")
	}
	if len(pattern) > 3 || len(pattern) == 3 && pattern[2].op != instr.BR_IF {
		return nil, fmt.Errorf("ref rule has unsupported trailing operations")
	}
	source := pattern[0].op
	consumer := pattern[1].op
	branch := len(pattern) == 3 && pattern[2].op == instr.BR_IF
	pre, body, value, err := renderRefSource(source, label)
	if err != nil {
		return nil, err
	}
	switch consumer {
	case instr.DROP:
		body = append(body, jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(total))
	case instr.REF_IS_NULL:
		body = append(body, jen.Id("value").Op(":=").Add(value))
		if branch {
			body = append(body, jen.Id("i").Dot("branchIf").Call(jen.Id("value").Dot("Ref").Call().Op("==").Lit(0), jen.Id("offset"), jen.Lit(total)))
		} else {
			body = append(body,
				jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Qual("github.com/siyul-park/minivm/types", "BoxI1").Call(jen.Id("value").Dot("Ref").Call().Op("==").Lit(0)),
				jen.Id("i").Dot("sp").Op("++"),
				jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(total),
			)
		}
	default:
		return nil, fmt.Errorf("unsupported ref consumer %s", instr.TypeOf(consumer).Mnemonic)
	}
	pre = append(pre,
		jen.Id("c").Dot("ip").Op("+=").Lit(width(source)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)),
	)
	return pre, nil
}

func renderRefSource(op instr.Opcode, label string) ([]jen.Code, []jen.Code, jen.Code, error) {
	overflow := jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow")))
	switch op {
	case instr.LOCAL_GET:
		return []jen.Code{
				jen.Id("idx").Op(":=").Int().Call(jen.Id("c").Dot("code").Index(jen.Id("start").Op("+").Lit(1))),
				refMetadata("locals", label),
			}, []jen.Code{
				overflow,
				jen.Id("addr").Op(":=").Id("i").Dot("fr").Dot("bp").Op("+").Id("idx"),
				jen.If(jen.Id("addr").Op(">=").Id("i").Dot("sp")).Block(jen.Panic(jen.Id("ErrSegmentationFault"))),
			}, jen.Id("i").Dot("stack").Index(jen.Id("addr")), nil
	case instr.GLOBAL_GET:
		return []jen.Code{
				jen.Id("idx").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(1)),
				refMetadata("globals", label),
			}, []jen.Code{
				overflow,
				jen.If(jen.Id("idx").Op(">=").Len(jen.Id("i").Dot("globals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))),
			}, jen.Id("i").Dot("globals").Index(jen.Id("idx")), nil
	case instr.UPVAL_GET:
		return []jen.Code{
				jen.Id("idx").Op(":=").Int().Call(jen.Id("c").Dot("code").Index(jen.Id("start").Op("+").Lit(1))),
				refMetadata("captures", label),
			}, []jen.Code{
				overflow,
				jen.If(jen.Id("idx").Op(">=").Len(jen.Id("i").Dot("fr").Dot("upvals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))),
			}, jen.Id("i").Dot("fr").Dot("upvals").Index(jen.Id("idx")), nil
	case instr.CONST_GET:
		return []jen.Code{
			jen.Id("idx").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(1)),
			jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
			jen.Id("constant").Op(":=").Id("c").Dot("constants").Index(jen.Id("idx")),
			jen.If(jen.Id("constant").Dot("Kind").Call().Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(reject(label)),
			jen.Id("addr").Op(":=").Id("constant").Dot("Ref").Call(),
			jen.If(jen.Id("addr").Op("<").Lit(0).Op("||").Id("addr").Op(">=").Len(jen.Id("c").Dot("heap"))).Block(reject(label)),
			jen.If(jen.List(jen.Id("_"), jen.Id("ok")).Op(":=").Id("c").Dot("heap").Index(jen.Id("addr")).Assert(jen.Qual("github.com/siyul-park/minivm/types", "String")), jen.Id("ok")).Block(reject(label)),
		}, []jen.Code{overflow}, jen.Id("constant"), nil
	case instr.REF_NULL:
		return nil, []jen.Code{overflow}, jen.Qual("github.com/siyul-park/minivm/types", "BoxedNull"), nil
	case instr.DUP:
		return nil, []jen.Code{
			jen.If(jen.Id("i").Dot("sp").Op("==").Lit(0)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
			overflow,
		}, jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)), nil
	default:
		return nil, nil, nil, fmt.Errorf("unsupported ref source %s", instr.TypeOf(op).Mnemonic)
	}
}

func refMetadata(field, label string) jen.Code {
	return jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot(field)).Op("||").Id("c").Dot(field).Index(jen.Id("idx")).Op("!=").Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(reject(label))
}

// renderThreadedIndex emits direct CONST/I32_CONST index specialization for
// ARRAY_GET and STRUCT_GET. The handler preserves producer overflow before
// consumer underflow, then delegates exact ownership/trap behavior to *GetAt.
func renderThreadedIndex(rule rule, totalWidth int, label string) ([]jen.Code, error) {
	if len(rule.pattern) != 2 {
		return nil, fmt.Errorf("index fusion needs two opcodes")
	}
	source := rule.pattern[0].op
	consumer := rule.pattern[1].op
	if consumer != instr.ARRAY_GET && consumer != instr.STRUCT_GET {
		return nil, fmt.Errorf("unsupported index consumer %s", instr.TypeOf(consumer).Mnemonic)
	}
	var pre []jen.Code
	switch source {
	case instr.I32_CONST:
		pre = append(pre,
			jen.Id("index").Op(":=").Int().Call(jen.Int32().Call(
				jen.Qual("github.com/siyul-park/minivm/instr", "Instruction").Call(jen.Id("c").Dot("code").Index(jen.Id("start").Op(":"))).Dot("Operand").Call(jen.Lit(0)),
			)),
		)
	case instr.CONST_GET:
		pre = append(pre,
			jen.Id("idx").Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Id("start").Op("+").Lit(1)),
			jen.If(jen.Id("idx").Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
			jen.Id("constant").Op(",").Id("ok").Op(":=").Qual("github.com/siyul-park/minivm/types", "Unbox").Call(jen.Id("c").Dot("constants").Index(jen.Id("idx"))).Assert(jen.Qual("github.com/siyul-park/minivm/types", "I32")),
			jen.If(jen.Op("!").Id("ok")).Block(reject(label)),
			jen.Id("index").Op(":=").Int().Call(jen.Id("constant")),
		)
	default:
		return nil, fmt.Errorf("unsupported index source %s", instr.TypeOf(source).Mnemonic)
	}
	method := "arrayGetAt"
	if consumer == instr.STRUCT_GET {
		method = "structGetAt"
	}
	body := []jen.Code{
		jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))),
		jen.If(jen.Id("i").Dot("sp").Op("==").Lit(0)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
		jen.Id("result").Op(":=").Id("i").Dot(method).Call(jen.Id("index")),
		jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Id("result"),
		jen.Id("i").Dot("sp").Op("++"),
		jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(totalWidth),
	}
	pre = append(pre,
		jen.Id("c").Dot("ip").Op("+=").Lit(width(source)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)),
	)
	return pre, nil
}

// renderNumericFusion emits preflight plus one concrete runtime handler for a
// normalized rule. Every source access is inline in that handler.
func renderNumericFusion(rule rule, totalWidth int, label string) ([]jen.Code, error) {
	pattern := rule.pattern
	branch := len(pattern) > 0 && pattern[len(pattern)-1].op == instr.BR_IF
	consumerAt := len(pattern) - 1
	if branch {
		consumerAt--
	}
	if consumerAt < 0 {
		return nil, fmt.Errorf("numeric rule has no consumer")
	}
	consumer := pattern[consumerAt].op
	arity, method, ok := numericConsumer(consumer)
	if !ok {
		return nil, fmt.Errorf("unsupported numeric consumer %s", instr.TypeOf(consumer).Mnemonic)
	}
	kind, _ := numericKind(consumer)
	sources := pattern[:consumerAt]
	if len(sources) > 2 {
		return nil, fmt.Errorf("numeric rule has %d sources", len(sources))
	}
	if traps(consumer) {
		return renderIntegerFusion(pattern, sources, method, kind, label)
	}

	var pre, body []jen.Code
	var renderedSources []access
	boxed := consumer == instr.I32_XOR || consumer == instr.I32_AND || consumer == instr.I32_OR
	offset := 0
	for idx, source := range sources {
		rendered, err := renderNumericSource(source.op, idx, len(sources), offset, kind, boxed, false, label)
		if err != nil {
			return nil, err
		}
		pre = append(pre, rendered.pre...)
		renderedSources = append(renderedSources, rendered)
		offset += rendered.width
	}
	// Each source contributes its stack-slot overflow check, then its own
	// bounds/metadata check, then its load, in the same flat order the
	// standalone opcodes would trap: source 0 fully validates and loads
	// before source 1's checks run. Every check is emitted exactly once.
	for idx, rendered := range renderedSources {
		body = append(body, jen.If(add(jen.Id("i").Dot("sp"), idx).Op("==").Len(jen.Id("i").Dot("stack"))).Block(
			jen.Panic(jen.Id("ErrStackOverflow")),
		))
		body = append(body, rendered.check...)
		body = append(body, rendered.load...)
	}

	var operands []jen.Code
	switch len(sources) {
	case 0:
		body = append(body, jen.If(jen.Id("i").Dot("sp").Op("<").Lit(arity)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))))
		if arity == 1 {
			operands = []jen.Code{numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1))}
		} else {
			operands = []jen.Code{
				numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(2)),
				numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1)),
			}
		}
	case 1:
		body = append(body, jen.If(jen.Id("i").Dot("sp").Op("==").Lit(0)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))))
		operands = []jen.Code{numericStackValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1)), jen.Id(val(len(sources) - 1))}
	case 2:
		operands = []jen.Code{jen.Id(val(0)), jen.Id(val(len(sources) - 1))}
	}
	if boxed {
		switch len(sources) {
		case 1:
			operands = []jen.Code{jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)), jen.Id(box(val(0)))}
		case 2:
			operands = []jen.Code{jen.Id(box(val(0))), jen.Id(box(val(1)))}
		}
	}
	if len(operands) != arity {
		return nil, fmt.Errorf("%s needs %d operands", instr.TypeOf(consumer).Mnemonic, arity)
	}
	body = append(body, jen.Id(val(len(sources))).Op(":=").Id("i").Dot(method).Call(operands...))
	if branch {
		delta := len(sources) - len(operands)
		if delta > 0 {
			body = append(body, jen.Id("i").Dot("sp").Op("+=").Lit(delta))
		} else if delta < 0 {
			body = append(body, jen.Id("i").Dot("sp").Op("-=").Lit(-delta))
		}
		body = append(body, jen.Id("i").Dot("branchIf").Call(jen.Id(val(len(sources))).Dot("Bool").Call(), jen.Id("offset"), jen.Lit(totalWidth)))
	} else {
		switch len(sources) {
		case 0:
			body = append(body, jen.Id("i").Dot("sp").Op("--"), jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)).Op("=").Id(val(len(sources))))
		case 1:
			body = append(body, jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)).Op("=").Id(val(len(sources))))
		case 2:
			body = append(body, jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Id(val(len(sources))), jen.Id("i").Dot("sp").Op("++"))
		}
		body = append(body, jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(totalWidth))
	}
	pre = append(pre, jen.Id("c").Dot("ip").Op("+=").Lit(width(pattern[0].op)))
	pre = append(pre, jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)))
	return pre, nil
}

func renderIntegerFusion(pattern, sources pattern, method, kind, label string) ([]jen.Code, error) {
	var pre, body []jen.Code
	offset := 0
	for number, source := range sources {
		rendered, err := renderNumericSource(source.op, number, len(sources), offset, kind, false, true, label)
		if err != nil {
			return nil, err
		}
		pre = append(pre, rendered.pre...)
		body = append(body, rendered.push...)
		offset += rendered.width
	}
	body = append(body,
		jen.If(jen.Id("i").Dot("sp").Op("<").Lit(2)).Block(jen.Panic(jen.Id("ErrStackUnderflow"))),
		jen.Id("rhs").Op(":=").Add(numericConsumedValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(1))),
		jen.Id("lhs").Op(":=").Add(numericConsumedValue(kind, jen.Id("i").Dot("sp").Op("-").Lit(2))),
		jen.Id("result").Op(":=").Id("i").Dot(method).Call(jen.Id("lhs"), jen.Id("rhs")),
		jen.Id("i").Dot("sp").Op("--"),
		jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp").Op("-").Lit(1)).Op("=").Id("result"),
		jen.Id("i").Dot("fr").Dot("ip").Op("++"),
	)
	pre = append(pre,
		jen.Id("c").Dot("ip").Op("+=").Lit(width(pattern[0].op)),
		jen.Return(jen.Func().Params(jen.Id("i").Op("*").Id("Interpreter")).Block(body...)),
	)
	return pre, nil
}

func traps(op instr.Opcode) bool {
	switch op {
	case instr.I32_DIV_S, instr.I32_DIV_U, instr.I32_REM_S, instr.I32_REM_U,
		instr.I64_DIV_S, instr.I64_DIV_U, instr.I64_REM_S, instr.I64_REM_U:
		return true
	default:
		return false
	}
}

func renderNumericSource(op instr.Opcode, number, count, offset int, kind string, raw, materialize bool, label string) (access, error) {
	width := width(op)
	name := val(number)
	boxed := box(name)
	idx := fmt.Sprintf("i%d", number)
	addr := fmt.Sprintf("i%d", count+number)
	at := add(jen.Id("start"), offset)
	result := access{width: width}
	switch op {
	case instr.LOCAL_GET, instr.UPVAL_GET:
		result.pre = append(result.pre, jen.Id(idx).Op(":=").Int().Call(jen.Id("c").Dot("code").Index(jen.Add(at).Op("+").Lit(1))))
	case instr.GLOBAL_GET, instr.CONST_GET:
		result.pre = append(result.pre, jen.Id(idx).Op(":=").Qual("github.com/siyul-park/minivm/instr", "ParseU16").Call(jen.Id("c").Dot("code"), jen.Add(at).Op("+").Lit(1)))
	}
	expected := jen.Qual("github.com/siyul-park/minivm/types", "Kind"+kind)
	switch op {
	case instr.LOCAL_GET:
		result.pre = append(result.pre, check("locals", idx, expected, label))
		result.check = append(result.check, jen.If(jen.Id("i").Dot("fr").Dot("bp").Op("+").Id(idx).Op(">=").Id("i").Dot("sp")).Block(jen.Panic(jen.Id("ErrSegmentationFault"))))
		result.load = append(result.load, jen.Id(addr).Op(":=").Id("i").Dot("fr").Dot("bp").Op("+").Id(idx), jen.Id(boxed).Op(":=").Id("i").Dot("stack").Index(jen.Id(addr)))
	case instr.GLOBAL_GET:
		result.pre = append(result.pre, check("globals", idx, expected, label))
		result.check = append(result.check, jen.If(jen.Id(idx).Op(">=").Len(jen.Id("i").Dot("globals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))))
		result.load = append(result.load, jen.Id(boxed).Op(":=").Id("i").Dot("globals").Index(jen.Id(idx)))
	case instr.UPVAL_GET:
		result.pre = append(result.pre, check("captures", idx, expected, label))
		result.check = append(result.check, jen.If(jen.Id(idx).Op(">=").Len(jen.Id("i").Dot("fr").Dot("upvals"))).Block(jen.Panic(jen.Id("ErrSegmentationFault"))))
		result.load = append(result.load, jen.Id(boxed).Op(":=").Id("i").Dot("fr").Dot("upvals").Index(jen.Id(idx)))
	case instr.CONST_GET:
		result.pre = append(result.pre,
			jen.If(jen.Id(idx).Op(">=").Len(jen.Id("c").Dot("constants"))).Block(reject(label)),
			jen.Id(boxed).Op(":=").Id("c").Dot("constants").Index(jen.Id(idx)),
		)
		if kind == "I64" {
			var inline, reference jen.Code
			constant := "constantI64"
			if materialize {
				inline = jen.Null()
				reference = jen.Null()
				constant = "_"
			} else {
				result.pre = append(result.pre, jen.Var().Id(name).Int64())
				inline = jen.Id(name).Op("=").Id(boxed).Dot("I64").Call()
				reference = jen.Id(name).Op("=").Int64().Call(jen.Id("constantI64"))
			}
			result.pre = append(result.pre,
				jen.Switch(jen.Id(boxed).Dot("Kind").Call()).Block(
					jen.Case(jen.Qual("github.com/siyul-park/minivm/types", "KindI64")).Block(inline),
					jen.Case(jen.Qual("github.com/siyul-park/minivm/types", "KindRef")).Block(
						jen.Id("constantRef").Op(":=").Id(boxed).Dot("Ref").Call(),
						jen.If(jen.Id("constantRef").Op("<").Lit(0).Op("||").Id("constantRef").Op(">=").Len(jen.Id("c").Dot("heap"))).Block(reject(label)),
						jen.List(jen.Id(constant), jen.Id("ok")).Op(":=").Id("c").Dot("heap").Index(jen.Id("constantRef")).Assert(jen.Qual("github.com/siyul-park/minivm/types", "I64")),
						jen.If(jen.Op("!").Id("ok")).Block(reject(label)),
						reference,
					),
					jen.Default().Block(reject(label)),
				),
			)
		} else {
			result.pre = append(result.pre,
				jen.If(jen.Id(boxed).Dot("Kind").Call().Op("!=").Add(expected)).Block(reject(label)),
			)
		}
	case instr.I32_CONST, instr.I64_CONST, instr.F32_CONST, instr.F64_CONST:
		if raw {
			result.pre = append(result.pre, jen.Id(box(name)).Op(":=").Qual("github.com/siyul-park/minivm/types", "BoxI32").Call(immediate(kind, at)))
		} else {
			result.pre = append(result.pre, jen.Id(name).Op(":=").Add(immediate(kind, at)))
		}
	default:
		return access{}, fmt.Errorf("unsupported numeric source %s", instr.TypeOf(op).Mnemonic)
	}
	if !raw && op != instr.I32_CONST && op != instr.I64_CONST && op != instr.F32_CONST && op != instr.F64_CONST && !(op == instr.CONST_GET && kind == "I64") {
		result.load = append(result.load, jen.Id(name).Op(":=").Add(numericBoxValue(kind, jen.Id(box(name)))))
	}
	result.push = append(result.push, jen.If(jen.Id("i").Dot("sp").Op("==").Len(jen.Id("i").Dot("stack"))).Block(jen.Panic(jen.Id("ErrStackOverflow"))))
	result.push = append(result.push, result.check...)
	switch op {
	case instr.LOCAL_GET:
		result.push = append(result.push, jen.Id(addr).Op(":=").Id("i").Dot("fr").Dot("bp").Op("+").Id(idx), jen.Id(box(name)).Op(":=").Id("i").Dot("stack").Index(jen.Id(addr)))
	case instr.GLOBAL_GET:
		result.push = append(result.push, jen.Id(box(name)).Op(":=").Id("i").Dot("globals").Index(jen.Id(idx)))
	case instr.UPVAL_GET:
		result.push = append(result.push, jen.Id(box(name)).Op(":=").Id("i").Dot("fr").Dot("upvals").Index(jen.Id(idx)))
	case instr.CONST_GET:
		result.push = append(result.push, jen.Id(box(name)).Op(":=").Id(boxed))
	case instr.I32_CONST:
		result.push = append(result.push, jen.Id(box(name)).Op(":=").Qual("github.com/siyul-park/minivm/types", "BoxI32").Call(jen.Id(name)))
	case instr.I64_CONST:
		result.push = append(result.push, jen.Id(box(name)).Op(":=").Id("i").Dot("boxI64").Call(jen.Id(name)))
	}
	if kind == "I64" && op != instr.I64_CONST {
		result.push = append(result.push, jen.Id("i").Dot("retainBox").Call(jen.Id(box(name))))
	}
	result.push = append(result.push,
		jen.Id("i").Dot("stack").Index(jen.Id("i").Dot("sp")).Op("=").Id(box(name)),
		jen.Id("i").Dot("sp").Op("++"),
		jen.Id("i").Dot("fr").Dot("ip").Op("+=").Lit(width),
	)
	return result, nil
}

func val(number int) string {
	return fmt.Sprintf("v%d", number)
}

func box(source string) string {
	return "r" + strings.TrimPrefix(source, "v")
}

func check(field, idx string, expected jen.Code, label string) jen.Code {
	return jen.If(jen.Id(idx).Op(">=").Len(jen.Id("c").Dot(field)).Op("||").Id("c").Dot(field).Index(jen.Id(idx)).Dot("Repr").Call().Op("!=").Add(expected)).Block(reject(label))
}

func reject(label string) jen.Code {
	if label != "" {
		return jen.Goto().Id(label)
	}
	return jen.Return(jen.Nil())
}

func numericKind(op instr.Opcode) (string, bool) {
	prefix := strings.Split(instr.TypeOf(op).Mnemonic, ".")[0]
	switch prefix {
	case "i32":
		return "I32", true
	case "i64":
		return "I64", true
	case "f32":
		return "F32", true
	case "f64":
		return "F64", true
	}
	return "", false
}

func numericBoxValue(kind string, value jen.Code) jen.Code {
	if kind == "I64" {
		return jen.Id("i").Dot("borrowI64").Call(value)
	}
	return jen.Add(value).Dot(kind).Call()
}

func numericStackValue(kind string, index jen.Code) jen.Code {
	return numericBoxValue(kind, jen.Id("i").Dot("stack").Index(index))
}

func numericConsumedValue(kind string, index jen.Code) jen.Code {
	value := jen.Id("i").Dot("stack").Index(index)
	if kind == "I64" {
		return jen.Id("i").Dot("unboxI64").Call(value)
	}
	return value.Dot(kind).Call()
}

func immediate(kind string, at jen.Code) jen.Code {
	operand := jen.Qual("github.com/siyul-park/minivm/instr", "Instruction").Call(jen.Id("c").Dot("code").Index(jen.Add(at).Op(":"))).Dot("Operand").Call(jen.Lit(0))
	switch kind {
	case "I32":
		return jen.Int32().Call(operand)
	case "I64":
		return jen.Int64().Call(operand)
	case "F32":
		return jen.Qual("github.com/siyul-park/minivm/types", "Box").Call(jen.Uint64().Call(jen.Uint32().Call(operand)), jen.Qual("github.com/siyul-park/minivm/types", "KindF32")).Dot("F32").Call()
	default:
		return jen.Qual("github.com/siyul-park/minivm/types", "Boxed").Call(operand).Dot("F64").Call()
	}
}

func width(op instr.Opcode) int {
	width := 1
	for _, operand := range instr.TypeOf(op).Widths {
		width += operand
	}
	return width
}

func add(value jen.Code, offset int) *jen.Statement {
	if offset == 0 {
		return jen.Add(value)
	}
	return jen.Add(value).Op("+").Lit(offset)
}

func formatGenerated(source []byte) ([]byte, error) {
	data, err := format.Source(source)
	if err != nil {
		return nil, err
	}
	for _, path := range []string{
		"github.com/siyul-park/minivm/instr",
		"github.com/siyul-park/minivm/types",
	} {
		name := path[strings.LastIndexByte(path, '/')+1:]
		data = bytes.ReplaceAll(data, []byte(name+" \""+path+"\""), []byte("\""+path+"\""))
	}
	return data, nil
}
